完成MTQQ模块的翻译
vertx-china/vertx-china.github.io pull request #100
Opened 2021-02-01 06:14 UTC by Linindoo

因为我本地无法预览，所以需要校对的时候预览下效果是否达到预期

2021-02-01 07:52 UTC, okou19900722 requested changes

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +== 使用 Vert.x MQTT
```suggestion
[[_using_vert_x_mqtt]]
== 使用 Vert.x MQTT
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +这个组件已经在Vertx栈中正式发布了，现在只需要在构建描述符中添加如下内容即可使用
```suggestion
这个组件已经在Vertx栈中正式发布了，现在只需要在构建描述符中添加如下内容即可使用：
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
>  * Maven (in your `pom.xml`):
```suggestion
* Maven （在 `pom.xml` 文件中）：
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> += Vert.x MQTT 服务端
```suggestion
[[_vert_x_mqtt_server]]
= Vert.x MQTT 服务端
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +== 开始
```suggestion
[[_getting_started]]
== 开始
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 处理客户端连接/断开
```suggestion
[[_handling_client_connectiondisconnection]]
=== 处理客户端连接/断开
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 支持使用SSL / TLS 处理客户端连接/断开连接
```suggestion
[[_handling_client_connectiondisconnection_with_ssltls_support]]
=== 支持使用SSL / TLS 处理客户端连接/断开连接
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 处理客户端 订阅/退订 请求
```suggestion
[[_handling_client_subscriptionunsubscription_request]]
=== 处理客户端 订阅/退订 请求
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 处理客户端发布的消息
```suggestion
[[_handling_client_published_message]]
=== 处理客户端发布的消息
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 发布消息到客户端
```suggestion
[[_publish_message_to_the_client]]
=== 发布消息到客户端
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 客户端保活通知
```suggestion
[[_be_notified_by_client_keep_alive]]
=== 客户端保活通知
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 关闭服务端
```suggestion
[[_closing_the_server]]
=== 关闭服务端
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 在verticles中自动清理
```suggestion
[[_automatic_clean_up_in_verticles]]
=== 在verticles中自动清理
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 扩展：共享MQTT服务器
```suggestion
[[_scaling_sharing_mqtt_servers]]
=== 扩展：共享MQTT服务器
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> += Vert.x MQTT 客户端
```suggestion
[[_vert_x_mqtt_client]]
= Vert.x MQTT 客户端
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +== 开始
```suggestion
[[_getting_started_2]]
== 开始
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 连接建立/连接断开
```suggestion
[[_connectdisconnect]]
=== 连接建立/连接断开
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 订阅主题消息
```suggestion
[[_subscribe_to_a_topic]]
=== 订阅主题消息
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 发布主题消息
```suggestion
[[_publishing_message_to_a_topic]]
=== 发布主题消息
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 与服务端保持连接
```suggestion
[[_keep_connection_with_server_alive]]
=== 与服务端保持连接
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +=== 通知时机
```suggestion
[[_be_notified_when]]
=== 通知时机
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +这个组件提供了一个服务，它能处理远程link:http://mqtt.org/[MQTT] 连接，通信和信息交换。
```suggestion
这个组件提供了一个服务，它能处理远程 link:http://mqtt.org/[MQTT] 连接，通信和信息交换。
```

2021-02-01 07:52 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +
```suggestion
```

2021-02-02 00:29 UTC, okou19900722 approved these changes

2021-02-02 00:31 UTC, okou19900722 commented
还有 `docs/metadata/3.9.0.jsx` 中mqtt相关的模块说明翻译一下

2021-02-02 03:29 UTC, chengenzhao requested changes

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 2(EXACTLY_ONCE),endpoint 需要使用 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReceived-int-[publishReceived]` 方法回复一个PUBREC消息给客户端。
```suggestion
如果Qos等级是 2（EXACTLY_ONCE），endpoint 需要使用 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReceived-int-[publishReceived]` 方法回复一个PUBREC消息给客户端。
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 1(AT_LEAST_ONCE),endpoint 需要使用`link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishAcknowledge-int-[publishAcknowledge]`方法回复一个PUBACK消息给客户端
```suggestion
如果Qos等级是 1（AT_LEAST_ONCE），endpoint 需要使用`link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishAcknowledge-int-[publishAcknowledge]`方法回复一个PUBACK消息给客户端
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 0(AT_MOST_ONCE),endpoint就没有必要回复客户端了。
```suggestion
如果Qos等级是 0（AT_MOST_ONCE），endpoint就没有必要回复客户端了。
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +在这种情况下，这个endpoint同时也要通过 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReleaseHandler-io.vertx.core.Handler-[publishReleaseHandler]` 指定一个handler来处理来自客户端的PUBREL(远程客户端接收到endpoint发送的PUBREC后发
```suggestion
在这种情况下，这个endpoint同时也要通过 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReleaseHandler-io.vertx.core.Handler-[publishReleaseHandler]` 指定一个handler来处理来自客户端的PUBREL（远程客户端接收到endpoint发送的PUBREC后发送的）消息
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 0(AT_MOST_ONCE),endpoint 就不会收到任何客户端的响应
```suggestion
如果Qos等级是 0（AT_MOST_ONCE），endpoint 就不会收到任何客户端的响应
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 1(AT_LEAST_ONCE), endpoint需要处理客户端的PUBACK消息,为了收到最后的确认消息，需要使用 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishAcknowledgeHandler-io.vertx.core.Handler-[publishAcknowledgeHandler]` 指
```suggestion
如果Qos等级是 1（AT_LEAST_ONCE），endpoint需要处理客户端的PUBACK消息,为了收到最后的确认消息，需要使用 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishAcknowledgeHandler-io.vertx.core.Handler-[publishAcknowledgeHandler]` 指定一个handler来接收。
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果Qos等级是 2(EXACTLY_ONCE)， endpoint 需要处理客户端的PUBREC消息，可以通过 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReceivedHandler-io.vertx.core.Handler-[publishReceivedHandler]` 方法指定一个handler来实现。
```suggestion
如果Qos等级是 2（EXACTLY_ONCE），endpoint 需要处理客户端的PUBREC消息，可以通过 `link:../../apidocs/io/vertx/mqtt/MqttEndpoint.html#publishReceivedHandler-io.vertx.core.Handler-[publishReceivedHandler]` 方法指定一个handler来实现。
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +但是当传入的连接到达时，会被Vert.x使用轮转算法分发到不同的核上运行的handlers上。
```suggestion
但是当传入的连接到达时，会被Vert.x使用轮转算法分发到不同的核上运行的处理器（handlers）上。
```

2021-02-02 03:29 UTC, chengenzhao commented on docs/translation/vertx-mqtt/java/index.adoc
> +这个组件提供了一个符合3.1.1版本规范的 link:http://mqtt.org/[MQTT] 客户端，他的API提供了一系列方法来处理连接建立/连接断开，发布消息（完整支持3种不同等级的Qos）以及主题订阅
```suggestion
这个组件提供了一个符合3.1.1版本规范的 link:http://mqtt.org/[MQTT] 客户端，它的API提供了一系列方法来处理连接建立/断开，发布消息（完整支持3种不同等级的Qos）以及主题订阅
```

2021-02-04 12:45 UTC, okou19900722 requested changes
还有 `docs/metadata/3.9.0.jsx` 中mqtt相关的模块说明翻译一下

https://github.com/vertx-china/vertx-web-site/blob/2825acab6613cea56727edaadb9b58e20bf53926/docs/metadata/3.9.0.jsx#L318-L326

2021-02-04 12:46 UTC, merged