fix #67 web open api
vertx-china/vertx-china.github.io pull request #101
Opened 2021-02-01 07:14 UTC by fofofofoxier

fix #67 web open api

2021-02-01 07:37 UTC, okou19900722 requested changes

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
> +[[_map_authenticationhandler_to_openAPI_security_schemes]]
```suggestion
[[_map_authenticationhandler_to_openapi_security_schemes]]
```

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
> +`link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html[RouterBuilder]` 是这个模块的主要元素：它提供来挂载请求处理器的接口并且生成最终的 `link:../../apidocs/io/vertx/ext/web/Router.html[Router]`
```suggestion
`link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html[RouterBuilder]` 是这个模块的主要元素：它提供用来挂载请求处理器的接口并且生成最终的 `link:../../apidocs/io/vertx/ext/web/Router.html[Router]`
```

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
> +要为一个operation来挂载一个处理器，则用 `link:../../apidocs/io/vertx/ext/web/openapi/Operation.html#handler-io.vertx.core.Handler-[handler]` ，要挂载一个失败处理器，则用 `link:../../apidocs/io/vertx/ext/web/openapi/Operation.htm
```suggestion
使用 `link:../../apidocs/io/vertx/ext/web/openapi/Operation.html#handler-io.vertx.core.Handler-[handler]` 为一个operation来挂载处理器，
使用 `link:../../apidocs/io/vertx/ext/web/openapi/Operation.html#failureHandler-io.vertx.core.Handler-[failureHandler]` 来挂载失败处理器。
```

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
> +* Maven (在您的 `pom.xml` 文件):
```suggestion
* Maven (在您的 `pom.xml` 文件)：
```

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
> +* Gradle (在您的 `build.gradle` 文件):
```suggestion
* Gradle (在您的 `build.gradle` 文件)：
```

2021-02-01 07:37 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
>  It fails if there is a missing `AuthenticationHandler` required by a configured operation.
忘记翻译了？

2021-02-01 09:24 UTC, fofofofoxier commented on docs/translation/vertx-web-openapi/java/index.adoc
>  It fails if there is a missing `AuthenticationHandler` required by a configured operation.
眼误，看走了眼

2021-02-02 13:37 UTC, okou19900722 approved these changes

2021-02-04 12:46 UTC, okou19900722 requested changes
翻译一下
https://github.com/vertx-china/vertx-web-site/blob/3cd3e1eabb86fe38e2a922ca55d866e18a74436d/docs/metadata/4.0.0.jsx#L85-L95

2021-02-04 13:50 UTC, fofofofoxier commented
已补充 https://github.com/vertx-china/vertx-web-site/pull/101#pullrequestreview-583354553

2021-02-06 02:39 UTC, Leibnizhu requested changes

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +* 在 OpenAPI风格和Vert.x风格之间路径的转换
```suggestion
* 在 OpenAPI 风格和 Vert.x 风格之间转换路径
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +要使用Vert.x OpenAPI，您需要添加如下依赖
```suggestion
要使用Vert.x OpenAPI，您需要添加如下依赖：
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +`link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html[RouterBuilder]` 是这个模块的主要元素：它提供用来挂载请求处理器的接口并且生成最终的 `link:../../apidocs/io/vertx/ext/web/Router.html[Router]`
```suggestion
`link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html[RouterBuilder]` 是这个模块的主要元素，它提供了用来挂载请求处理器的接口，并且生成最终的 `link:../../apidocs/io/vertx/ext/web/Router.html[Router]`
```
增加可读性

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +要使用 Vert.x Web OpenAPI ，您必须用 `link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html#create-io.vertx.core.Vertx-java.lang.String-io.vertx.core.Handler-[RouterBuilder.create]` 方法和您的接口协议来实例化 `l
```suggestion
要使用 Vert.x Web OpenAPI ，您必须用 `link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html#create-io.vertx.core.Vertx-java.lang.String-io.vertx.core.Handler-[RouterBuilder.create]` 方法并传入您的接口协议来实例化 `link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html[RouterBuilder]`
```
只是建议：“with your contract”原义的确是“和你的接口协议”，但这里更多是“附加”的意思，也就是作为传参。

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +您可以配置 `link:../../apidocs/io/vertx/ext/web/openapi/OpenAPILoaderOptions.html[OpenAPILoaderOptions]` 用以获取私有的远程约束：
```suggestion
您可以通过配置 `link:../../apidocs/io/vertx/ext/web/openapi/OpenAPILoaderOptions.html[OpenAPILoaderOptions]` 以获取私有的远程约束：
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +为了获取协议中定义的 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operationObject[Operation] ，您需要用 `link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html#operation-java.l
```suggestion
为了获取协议中定义的 https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#operationObject[Operation] ，您需要用 `link:../../apidocs/io/vertx/ext/web/openapi/RouterBuilder.html#operation-java.lang.String-[operation]` 方法。
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +您可以 ** 在一个operation当中添加多个处理器 **，而不覆盖已经存在的处理器。
```suggestion
您可以 **在一个 operation 当中添加多个处理器** ，而不覆盖已经存在的处理器。
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +== 未实现错误
```suggestion
== 未实现的错误
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +==请求体处理器
```suggestion
== 请求体处理器
```

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +== 未实现错误
这附近二十来行，在github看起来有点错乱，仔细对比好象又没问题……

2021-02-06 02:39 UTC, Leibnizhu commented on docs/translation/vertx-web-openapi/java/index.adoc
> +- 否则 就是一个表单请求
```suggestion
- 否则是一个表单请求
```

2021-02-07 01:47 UTC, Leibnizhu approved these changes

2021-02-07 02:28 UTC, okou19900722 commented on docs/translation/vertx-web-openapi/java/index.adoc
```suggestion
```

2021-02-07 02:31 UTC, merged