完成 vertx-lang-kotlin-coroutines 的翻译
vertx-china/vertx-china.github.io pull request #103
Opened 2021-02-01 13:09 UTC by cpdyj

感谢您协助校对

2021-02-01 14:04 UTC, cpdyj commented
纠结，有些东西这么翻译不符合汉语习惯啊······

2021-02-02 00:57 UTC, okou19900722 requested changes

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +`vertx-lang-kotlin-coroutines` 使用 _协程_。协程是一种非常轻量级的、不对应到内核线程的线程，
```suggestion
`vertx-lang-kotlin-coroutines` 使用 _协程_ 。协程是一种非常轻量级的、不对应到内核线程的线程，
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +因此当一个_协程_需要“阻塞”时，它会_挂起_并释放当前的内核线程，
```suggestion
因此当一个 _协程_ 需要“阻塞”时，它会 _挂起_ 并释放当前的内核线程，
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +脱离 https://kotlinlang.org/docs/reference/coroutines.html#experimental-status-of-coroutines[实验]状态
```suggestion
脱离 https://kotlinlang.org/docs/reference/coroutines.html#experimental-status-of-coroutines[实验] 状态
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
>   with the value that was given to the handler.
```suggestion
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +Vert.x 中的许多异步操作的最后一个参数是一个 `Handler<AsyncResult<T>>`。
```suggestion
Vert.x 中的许多异步操作的最后一个参数是一个 `Handler<AsyncResult<T>>` 。
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
>  `try`/`catch` constructs:
```suggestion
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +由于 Vert.x 4 提供了基于 future 的 API，那些扩展方法仍会存在，但将被_弃用_。
```suggestion
由于 Vert.x 4 提供了基于 future 的 API，那些扩展方法仍会存在，但将被 _弃用_ 。
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +通道类似于 Java 的 `BlockingQueue`，不同之处在于它不是阻塞的，而是在如下情况中挂起协程：
```suggestion
通道类似于 Java 的 `BlockingQueue` ，不同之处在于它不是阻塞的，而是在如下情况中挂起协程：
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +* 向一个满了的通道中写入值
```suggestion
- 向一个满了的通道中写入值
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +* 从一个空的通道中读取值
```suggestion
- 从一个空的通道中读取值
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +解析请求行只需简单地在通道上调用 `receive`。
```suggestion
解析请求行只需简单地在通道上调用 `receive` 。
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +Vert.x 适用于任何协程构建器，只要 `CoroutineScope` 实例是有效的：`launch`, `async`, `produce`, ... . 以下重要事项必须被注意：
```suggestion
Vert.x 适用于任何协程构建器，只要 `CoroutineScope` 实例是有效的：`launch` ， `async` ， `produce` …… 。 以下重要事项必须被注意：
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
>  - The `runBlocking` doesn't need a `CoroutineScope` and must not be used from a Vert.x event loop thread.
```suggestion
```

2021-02-02 00:57 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +可以在这里了解更多：https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md[Guide to reactive streams with coroutines]
```suggestion
可以在这里了解更多： https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md[Guide to reactive streams with coroutines]
```

2021-02-02 00:59 UTC, okou19900722 approved these changes

2021-02-02 01:01 UTC, okou19900722 approved these changes

2021-02-02 01:01 UTC, okou19900722 commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +可以在这里了解更多：https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md[Guide to reactive streams with coroutines]
```suggestion
可以在这里了解更多： https://github.com/Kotlin/kotlinx.coroutines/blob/master/reactive/coroutines-guide-reactive.md[Guide to reactive streams with coroutines]
```

2021-02-02 03:23 UTC, chengenzhao approved these changes
主要是一些换行没有填入，这样跟翻译原文的行数就不一致了
还有一些原文留在文中没有删除

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +Vert.x API 有许多地方使用 handlers 处理事件流。
```suggestion
Vert.x API 有许多地方使用处理器（handlers）处理事件流。
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +由于 Vert.x 4 提供了基于 future 的 API，那些扩展方法仍会存在，但将被 _弃用_ 。
```suggestion
由于 Vert.x 4 提供了基于 future 的 API，那些扩展方法仍会存在，
但将被 _弃用_ 。
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +如下是一个初始版本的解析器，只处理 HTTP 的请求行
```suggestion
如下是一个初始版本的解析器，仅处理 HTTP 的请求行
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +最终终止解析器来处理一个可选的请求体
```suggestion
最终我们用处理一个可选的请求体来终止解析器
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +`SendChannel#send` 和 `WriteStream#write` 都是非阻塞操作，然而不同于 `SendChannel#send` 可以在通道满时暂停执行，不使用通道的情况看起来像
```suggestion
`SendChannel#send` 和 `WriteStream#write` 都是非阻塞操作，然而不同于
`SendChannel#send` 可以在通道满时暂停执行，不使用通道的情况看起来像
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +取消是 https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-is-cooperative[协作的]
```suggestion
取消操作是 https://github.com/Kotlin/kotlinx.coroutines/blob/master/coroutines-guide.md#cancellation-is-cooperative[协作的]
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +也可以使用 `withTimeout` 计划一个超时值
```suggestion
也可以使用 `withTimeout` 安排一个超时值
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +Vert.x 适用于任何协程构建器，只要 `CoroutineScope` 实例是有效的：`launch` ， `async` ， `produce` …… 。 以下重要事项必须被注意：
```suggestion
Vert.x 适用于任何协程构建器，只要 `CoroutineScope` 实例是有效的：`launch` ， `async` ， `produce` …… 。
以下重要事项必须被注意：
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +Vert.x 集成被设计成完全与 Kotlin 协程互操作的
```suggestion
Vert.x 集成被设计成可与 Kotlin 协程全面互通
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
>  * `kotlinx.coroutines.experimental.sync.Mutex` are executed on the event loop thread when using the vertx dispatcher
```suggestion
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +模块 `vertx-lang-kotlin-coroutines` 没有与 RxJava 的特定集成，然而 Kotlin 协程提供了 RxJava 的集成，它与 `vertx-lang-kotlin-coroutines` 一同工作良好。
```suggestion
模块 `vertx-lang-kotlin-coroutines` 没有与 RxJava 的特定集成，然而 Kotlin 协程提供了 RxJava 的集成，
它与 `vertx-lang-kotlin-coroutines` 一同工作良好。
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +以上所有的代码都假设被运行在一个 `CoroutineVerticle` 实现中，但是也可以通过替换所有的 `<builder> { .. }` 为
```suggestion
以上所有的代码都被假设运行在一个 `CoroutineVerticle` 实现中，但是也可以通过替换所有的 `<builder> { .. }` 为
```

2021-02-02 03:23 UTC, chengenzhao commented on docs/translation/vertx-lang-kotlin-coroutines/kotlin/index.adoc
> +`GlobalScope.<builder> { .. }` 来使用应用作用域。
```suggestion
`GlobalScope.<builder> { .. }` 来使用应用的作用域。
```

2021-02-02 03:32 UTC, chengenzhao requested changes

2021-02-02 03:32 UTC, chengenzhao commented on docs/metadata/4.0.0.jsx
> +    description: `Vert.x 对 Kotlin 协程的支持，提供如 async/await 或 Go-like 通道 的强大支持。使你可以如熟悉的顺序风格一样编写 Verticle 代码`,
```suggestion
    description: `Vert.x 对 Kotlin 协程的支持，提供如 async/await 或 类似 Go 通道的强大支持。使您可以如熟悉的顺序风格一样编写 Verticle 代码`,
```

2021-02-02 12:25 UTC, okou19900722 approved these changes

2021-02-02 12:25 UTC, okou19900722 commented on docs/metadata/4.0.0.jsx
> +    description: `Vert.x 对 Kotlin 协程的支持，提供如 async/await 或 类似 Go 通道的强大支持。使您可以如熟悉的顺序风格一样编写 Verticle 代码`,
```suggestion
    description: "Vert.x 对 Kotlin 协程的支持，提供如 async/await 或 类似 Go 通道的强大支持。使您可以如熟悉的顺序风格一样编写 Verticle 代码",
```

2021-02-02 12:59 UTC, chengenzhao approved these changes

2021-02-02 12:59 UTC, merged