fix #55
vertx-china/vertx-china.github.io pull request #104
Opened 2021-02-03 13:23 UTC by fofofofoxier

fix #55

2021-02-03 13:39 UTC, okou19900722 approved these changes

2021-02-03 13:39 UTC, okou19900722 commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +=== 代码生成
```suggestion
[[_code_generation]]
=== 代码生成
```

2021-02-03 13:39 UTC, okou19900722 commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +_codegen_ 注解执行器在编译期间生成这些类，这是Java编译器的特性，所以 _不能有额外步骤_ ，这仅仅需要在构建时保证配置的正确性：
```suggestion
_codegen_ 注解执行器在编译期间生成这些类，这是Java编译器的特性，所以 _不需要额外步骤_ ，这仅仅需要在构建时保证配置的正确性：
```

2021-02-04 02:50 UTC, fofofofoxier commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +（译者注：原文为 anemic json row mapping，即anemic mapping，指单纯的属性映射，无行为）
@okou19900722 @chengenzhao @Leibnizhu @wkgcass 此处译注是否合理

2021-02-04 02:50 UTC, fofofofoxier commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +（译者注：原文为 anemic json parameters mapping，即anemic mapping，指单纯的属性映射，无行为）
@okou19900722 @chengenzhao @wkgcass @Leibnizhu 此处译注是否合理

2021-02-04 05:34 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +（译者注：原文为 anemic json parameters mapping，即anemic mapping，指单纯的属性映射，无行为）
我觉得可以

2021-02-04 05:34 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +（译者注：原文为 anemic json row mapping，即anemic mapping，指单纯的属性映射，无行为）
我觉得可以

2021-02-04 12:42 UTC, okou19900722 commented
翻译一下
https://github.com/vertx-china/vertx-web-site/blob/3cd3e1eabb86fe38e2a922ca55d866e18a74436d/docs/metadata/4.0.0.jsx#L193-L204

2021-02-04 12:43 UTC, okou19900722 requested changes
翻译一下
 https://github.com/vertx-china/vertx-web-site/blob/3cd3e1eabb86fe38e2a922ca55d866e18a74436d/docs/metadata/4.0.0.jsx#L193-L204

2021-02-04 13:02 UTC, dreamlikeoceanlmy commented
我是dreamlike，https://juejin.cn/post/6925383527328382983的作者，我觉得没问题

2021-02-04 13:10 UTC, dreamlikeoceanlmy approved these changes

2021-02-04 13:50 UTC, fofofofoxier commented
已补充 https://github.com/vertx-china/vertx-web-site/pull/104#pullrequestreview-583351888

2021-02-05 00:49 UTC, okou19900722 approved these changes

2021-02-05 02:35 UTC, chengenzhao requested changes

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +JSON 行映射是一个简单的模板映射，它用 `link:../../apidocs/io/vertx/sqlclient/Row.html#toJson--[toJson]` 来在数据行和JSON对象之间进行映射。
```suggestion
JSON 行映射是一个简单的模板映射，它用 `link:../../apidocs/io/vertx/sqlclient/Row.html#toJson--[toJson]` 将数据行映射成JSON对象。
```

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +行映射是通过用每行key/value pair来创建 `JsonObject` 实现的，然后
```suggestion
行映射是通过用键值对（key/value pair）来创建 `JsonObject` 实现的，然后
```

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +SQL Client Templates 组建可以为Vert.x数据对象生成映射方法。
```suggestion
SQL Client Templates 组件可为Vert.x数据对象生成映射方法。
```

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +一个Vert.x数据对象是一个 `@DataObject` 注解修饰过的普通的Java Bean。
```suggestion
一个Vert.x数据对象是一个被 `@DataObject` 注解修饰的普通的Java Bean。
```

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +与 `userName` 列绑定。
```suggestion
绑定 `userName` 列。
```

2021-02-05 02:35 UTC, chengenzhao commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +- `link:../../apidocs/io/vertx/codegen/format/LowerCamelCase.html[LowerCamelCase]` : `firstName` - 类似 camel case 但是开头字母小写，这是默认方式。
```suggestion
- `link:../../apidocs/io/vertx/codegen/format/LowerCamelCase.html[LowerCamelCase]` : `firstName` - 类似驼峰命名法但是小写字母开头，这是默认方式。
```

2021-02-08 05:38 UTC, Leibnizhu requested changes

2021-02-08 05:38 UTC, Leibnizhu commented on docs/metadata/4.0.0.jsx
> +    description: `一个轻量级的库，旨在增强SQL查询
这样换行会在 “查询” 和 “和数据” 之间多一个空格的。  
改成在逗号那里换行吧：
```suggestion
    description: `一个轻量级的库，
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +一个 SQL template 接收 _被命名的_ 参数，因此，默认情况下，它会接收一个map作为参数载体，而非接收元组（tuple）作为参数。
```suggestion
一个 SQL template 接收 _已命名的_ 参数，因此，默认情况下，它会接收一个map作为参数载体，而非接收元组（tuple）作为参数。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +模板语法使用 `#{XXX}` 的语法（ `{XXX}` 是一个有效的 https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8[java identifier] 字符串）
没翻译 “(without the keyword restriction).”。  
指的是 java的关键/保留词？如果是的话，不能忽略，这句话还是有点用的。  
另外：  
```suggestion
模板语法使用 `#{XXX}` 的语法，其中 `{XXX}` 是一个有效的 https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-3.8[java identifier] 字符串
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您可以用反斜杠来转义任何 `\#` 字符串，例如 `\#{foo}` ，会被解析成 `#{foo}` 字符串而不是名为 `foo` 的参数。
```suggestion
您可以用反斜杠（`\`）来转义 `#` 字符，例如 `\#{foo}` 会被解析成 `#{foo}` 字符串，而不是名为 `foo` 的参数。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +模板接收一个 `Map<String, Object>` 作为默认输入参数。
```suggestion
模板默认接收一个 `Map<String, Object>` 作为输入参数。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您可以提供一个自定义的Mapper：
```suggestion
您可以提供一个自定义的映射（Mapper）：
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您需要添加Jackson数据绑定依赖：
```suggestion
您需要添加 jackson-databind 依赖：
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您可以用 `java.time` 包中的类型 例如 `LocalDateTime` ：
```suggestion
您可以用 `java.time` 包中的类型，例如 `LocalDateTime` ：
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +一个Vert.x数据对象是一个被 `@DataObject` 注解修饰的普通的Java Bean。
```suggestion
Vert.x 数据对象是指被 `@DataObject` 注解修饰的普通 Java Bean。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +_codegen_ 注解执行器在编译期间生成这些类，这是Java编译器的特性，所以 _不需要额外步骤_ ，这仅仅需要在构建时保证配置的正确性：
```suggestion
_codegen_ 注解执行器在编译期间生成这些类。
这是Java编译器的特性，所以 _不需要额外步骤_ ，仅需要在构建时保证配置的正确性：
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +按您所需，也可以用普通jar包，但是您需要额外声明注解执行器。maven示例：
```suggestion
如果需要，也可以用普通jar包，但是您需要额外声明注解执行器。
Maven 示例：
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +拜 `link:../../apidocs/io/vertx/sqlclient/templates/annotations/Column.html[@Column]` 注解所赐，您可以用自定义名称。
```suggestion
通过 `link:../../apidocs/io/vertx/sqlclient/templates/annotations/Column.html[@Column]` 注解，您可以用自定义名称。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您可以用注解修饰 属性、getter、setter方法。
```suggestion
您可以用注解修饰属性、getter、setter方法。
```

2021-02-08 05:38 UTC, Leibnizhu commented on docs/translation/vertx-sql-client-templates/java/index.adoc
> +您可以用注解修饰 属性、getter、setter方法。
```suggestion
您可以用注解修饰属性、getter、setter方法。
```

2021-02-08 10:13 UTC, Leibnizhu approved these changes

2021-02-08 10:14 UTC, merged