翻译了下 vertx-core/Kotlin 的文档
vertx-china/vertx-china.github.io pull request #105
Opened 2021-02-03 14:13 UTC by cpdyj

看板上显示已经完成了，看到没翻译就顺手弄了，没提前打招呼（

2021-02-03 14:13 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> +Vert.x 核心 API 以及启用 JavaScript 支持：
我是真没搞懂为啥这里是 JavaScript 支持，可能原来的文档就是错的？

2021-02-03 14:24 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> +// 这个 json 构建器用于构建 JSON 结构
这话说的我好难受哟

2021-02-04 07:32 UTC, chengenzhao commented on docs/translation/vertx-core/kotlin/index.adoc
> +// 这个 json 构建器用于构建 JSON 结构
```suggestion
// 该 json 建造器声明了一个 JSON 结构
```

2021-02-04 07:33 UTC, chengenzhao commented
等4.0.1文档 merge 过来之后，就可以merge这个

2021-02-04 10:17 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +如果你使用 Maven 或者 Gradle， 可以通过将以下依赖添加到项目描述中的 _dependencies_ 节来使用
```suggestion
如果你使用 Maven 或者 Gradle， 可以通过添加以下依赖来使用 
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +如果你使用 Maven 或者 Gradle， 可以通过将以下依赖添加到项目描述中的 _dependencies_ 节来使用
此处不必完整翻译，言简意赅，原则上保证中文语法通顺即可

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +使用 Kotlin 编写一个 Verticle 的方式与 Java 相同，继承 `link:../../apidocs/io/vertx/core/AbstractVerticle.html[AbstractVerticle]`
```suggestion
使用 Kotlin 编写一个 Verticle 的方式与 Java 相同，即继承 `link:../../apidocs/io/vertx/core/AbstractVerticle.html[AbstractVerticle]`
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +`link:../../apidocs/io/vertx/core/json/JsonObject.html[JsonObject]` 类用来表达 JSON 对象，
```suggestion
`link:../../apidocs/io/vertx/core/json/JsonObject.html[JsonObject]` 类用来表示 JSON 对象，
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +类用来表达数组，可以参考 Java 文档获得更多信息。
```suggestion
类用来表示数组，可以参考 Java 文档获得更多信息。
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 在对象接收者上执行 put 函数
此处原文没有体现 ‘put 函数‘ 语义，我不是很懂kotlin，如果表意达到，则忽略此评论

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +// 这个 json 构建器用于构建 JSON 结构
```suggestion
// 这个 json 构建器用于声明 JSON 结构
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 直接用值作为变长参数
```suggestion
 // 直接用变长的值数组作为参数
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 一个值的可迭代对象
```suggestion
 // 一个可迭代的值集合
```

2021-02-04 10:32 UTC, fofofofoxier commented on docs/translation/vertx-core/kotlin/index.adoc
> +// 这个 json 构建器用于构建 JSON 结构
```suggestion
// 这个 json 构建器用于声明 JSON 结构
```

2021-02-04 14:29 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 在对象接收者上执行 put 函数
> 此处原文没有体现 ‘put 函数‘ 语义，我不是很懂kotlin，如果表意达到，则忽略此评论

emmm很纠结，虽然注释没这么说，但是代码确实是这样的，我不知道怎么把这话说的更准确

2021-02-04 14:32 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> +Vert.x 核心 API 以及启用 JavaScript 支持：
@okou19900722 这里真的没问题吗

2021-02-04 14:34 UTC, Leibnizhu commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 在对象接收者上执行 put 函数
是不是可以执行其他函数，只是这个示例刚好是`put`函数？

2021-02-04 14:35 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 在对象接收者上执行 put 函数
嗯，可以执行什么都行

2021-02-04 14:37 UTC, cpdyj commented on docs/translation/vertx-core/kotlin/index.adoc
> + // 在对象接收者上执行 put 函数
我改动了以下，改成了 `在对象接收者上附加函数`

2021-02-05 00:46 UTC, okou19900722 commented on docs/translation/vertx-core/kotlin/index.adoc
> +Vert.x 核心 API 以及启用 JavaScript 支持：
https://github.com/vert-x3/vertx-lang-kotlin/commit/dc3a3f624101a011ab15fca6265cca54d9be6707#diff-9033b03bed40024b2a0fef9f7bca4e868e4bce6b69f017df402d5696d9a88fb0

这好像是文档第一次提交，里面就是 `JavaScript`，估计是从 `vertx-lang-js`拷贝过来的

2021-02-06 03:53 UTC, okou19900722 requested changes

2021-02-06 03:53 UTC, okou19900722 commented on docs/translation/vertx-core/kotlin/index.adoc
> +Vert.x 核心 API 以及启用 JavaScript 支持：
官方文档我已经提交了更新，并且合并了，这里改成Kotlin了
```suggestion
Vert.x 核心 API 以及启用 Kotlin支持：
```

2021-02-09 05:05 UTC, Leibnizhu commented on docs/translation/vertx-core/kotlin/index.adoc
> +Vert.x 核心 API 以及启用 Kotlin支持：
test

2021-02-09 05:08 UTC, Leibnizhu commented on docs/translation/vertx-core/kotlin/index.adoc
> +* Maven （在 `pom.xml` 文件中）：
```suggestion
* Maven （在 `pom.xml` 文件中）： 
```

2021-02-09 05:09 UTC, Leibnizhu commented on docs/translation/vertx-core/kotlin/index.adoc
> +* Gradle （在 `build.gradle` 文件中）：
```suggestion
* Gradle （在 `build.gradle` 文件中）： 
```

2021-02-09 06:01 UTC, merged