Redis client
vertx-china/vertx-china.github.io pull request #107
Opened 2021-02-04 16:18 UTC by zxj5470

2021-02-05 11:20 UTC, dreamlike-ocean commented on docs/translation/vertx-redis-client/java/index.adoc
> +该模块允许在 Redis 中保存、检索、搜索和删除数据。Redis 是一个开源的、先进的键值存储数据库。
retrieved我觉得应该取“获取"的意思，如果是检索是不是和后面的搜索意思重复了

2021-02-05 11:20 UTC, dreamlike-ocean commented on docs/translation/vertx-redis-client/java/index.adoc
> +例如，该模块提供了一个干净的 API 来执行命令，而不需要自己手写命令。
我认为"简洁"比”干净“更好

2021-02-05 11:20 UTC, dreamlikeoceanlmy commented on docs/translation/vertx-redis-client/java/index.adoc
> +需要注意的是，没有获取或返回任何连接都是由连接池处理的。
需要注意的是，连接是不需要手动获取或者归还的，这些连接都是被连接池管理的
我觉得加几个字意思会更通畅

2021-02-05 11:20 UTC, dreamlikeoceanlmy commented on docs/translation/vertx-redis-client/java/index.adoc
> +常见的配置是将连接池的最大大小设置为可用CPU核心数，并允许请求从连接池中获取连接以进行排队：
并允许排队从连接池里面获取连接

2021-02-05 11:20 UTC, dreamlikeoceanlmy commented on docs/translation/vertx-redis-client/java/index.adoc
> +通过丢弃客户端，我们可以确保所有旧的飞行响应都会丢失，而所有新的响应都会在新的连接上。
通过弃用旧客户端，我们可以确保所有没有处理的响应都被抛弃
这个翻译是我的直觉

2021-02-06 00:33 UTC, okou19900722 requested changes

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 使用 Vert.x-Redis
```suggestion
[[_using_vert_x_redis]]
== 使用 Vert.x-Redis
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 连接到 Redis
```suggestion
[[_connecting_to_redis]]
== 连接到 Redis
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 连接字符串
```suggestion
[[_connection_string]]
== 连接字符串
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 执行命令
```suggestion
[[_running_commands]]
== 执行命令
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 高可用模式
```suggestion
[[_high_availability_mode]]
== 高可用模式
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 集群模式
```suggestion
[[_cluster_mode]]
== 集群模式
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 发布/订阅模式
```suggestion
[[_pubsub_mode]]
== 发布/订阅模式
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 域套接字
```suggestion
[[_domain_sockets]]
== 域套接字
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 连接池
```suggestion
[[_connection_pooling]]
== 连接池
```

2021-02-06 00:33 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +== 出错时重连
```suggestion
[[_implementing_reconnect_on_error]]
== 出错时重连
```

2021-02-06 03:15 UTC, Leibnizhu requested changes

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +该模块允许在 Redis 中保存、检索、搜索和删除数据。Redis 是一个开源的、先进的键值存储数据库。
```suggestion
该模块允许在 Redis 中保存、查询、搜索和删除数据。Redis 是一个开源的、先进的键值存储数据库。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +它通常被称为数据结构服务器，因为键可以包含字符串、散列、列表、集合和排序集合。
存疑，这里“contains”应该是指 键可以“容纳” ；且，众所周知redis的key还是string，value才有这些不同数据类型。  
翻译为 “键可以包含....” 欠妥。建议：  
```suggestion
它通常被称为数据结构服务器，因为 Reids 的键可以存储字符串、散列、列表、集合和排序集合。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +* 基数统计 HyperLogLog - Commands to approximating the number of distinct elements in a multiset, a HyperLogLog.
这里漏了翻译

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +用以下代码获得连接
```suggestion
用以下代码获得连接：
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +配置中存在 `password` 或者 `select` 数据库，在连接时命令会自动执行。
```suggestion
配置中包含 `password` 且/或 `select` 数据库，
在成功建立连接后，这两个命令会自动执行。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +  // 客户端处理 REDIS URLs.
“The select database as per spec is the numerical path of the URL and the password is the password field of the URL authority”没翻译

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +返回的对象是泛型类型，它允许从基本的 redis 类型转换为您的语言类型。
```suggestion
返回的对象是泛型类型，它允许从基本的 redis 类型转换为您的编程语言类型。
```
“语言”有歧义

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +例如，如果您的 response 类型为`INTEGER`，则可以通过任意数值基元类型 `int`、`long` 获取该值。
```suggestion
例如，如果返回对象类型为`INTEGER`，则可以通过任意数值基本类型获取该值，如 `int`、`long` 等等。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +客户端将在后台监听哨兵的事件。当哨兵通知我们切换了主机时，就会向客户端发送一个异常，您可以决定下一步做什么。
```suggestion
客户端将在后台监听哨兵的事件。当哨兵通知我们切换了主机时，
就会向客户端发送一个异常，您可以决定下一步做什么。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +在这种情况下，配置需要知道群集的一个或多个成员。
```suggestion
在这种情况下，配置需要知道集群的一个或多个成员。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +此列表用于向群集请求当前配置，这意味着如果列出的任何成员不可用，则将跳过该成员。
```suggestion
此成员列表用于向集群请求当前配置，这意味着列表中不可用的成员将被跳过。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +在群集模式下将建立到每个节点的连接。
```suggestion
在集群模式下将建立到每个节点的连接。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +在此模式下操作的客户端会尽量识别执行的命令使用哪个槽，以便在正确的节点上执行它。
```suggestion
在此模式下操作的客户端会尽量识别执行的命令使用哪个槽（slot），以便在正确的节点上执行它。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +请注意，高可用模式和群集模式报告的服务器地址始终位于 TCP 地址上，而不是域套接字上。
```suggestion
请注意，高可用模式和集群模式报告的服务器地址始终位于 TCP 地址上，而不是域套接字上。
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +* `poolCleanerInterval` 清除连接的时间间隔 默认为`-1`(禁用)
```suggestion
* `poolCleanerInterval` 清除连接的时间间隔 默认为 `-1` (禁用)
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +* `maxPoolWaiting` 在队列上获取连接的最大等待处理程序数 (默认值为`24`)
```suggestion
* `maxPoolWaiting` 在队列上获取连接的最大等待处理程序数 (默认值为 `24`)
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +* `poolRecycleTimeout` 保持连接池池中打开的连接等待然后关闭的超时时间 (默认 `15_000`)
```suggestion
* `poolRecycleTimeout` 连接池中打开的连接保持等待到关闭的超时时间 (默认 `15_000`)
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +连接池对于避免自定义连接管理非常有用，例如，您可以只使用：
```suggestion
连接池非常有用，无需自己管理连接，例如，您只需要：
```

2021-02-06 03:15 UTC, Leibnizhu commented on docs/translation/vertx-redis-client/java/index.adoc
> +常见的配置是将连接池的最大大小设置为可用CPU核心数，并允许请求从连接池中获取连接以进行排队：
@dreamlikeoceanlmy 修改意见可以使用“Insert a suggestion”*（⌘+g）

2021-02-06 13:01 UTC, zxj5470 reviewed
review change

2021-02-06 13:04 UTC, okou19900722 requested changes

2021-02-06 13:04 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
> +* 集群 Cluster - 与集群管理相关的命令, 使用这些命令需要注意 redis server 版本 &gt;=3.0.0 。
```suggestion
* 集群 Cluster - 与集群管理相关的命令, 使用这些命令需要注意 redis server 版本 >=3.0.0 。
```

2021-02-06 13:04 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
>  domain docket:
这两行已经翻译了，忘记删除了吧

2021-02-06 13:04 UTC, zxj5470 reviewed
correct review change

2021-02-06 13:23 UTC, zxj5470 reviewed
review changes

2021-02-06 13:35 UTC, zxj5470 reviewed
review changes

2021-02-06 13:55 UTC, zxj5470 commented on docs/translation/vertx-redis-client/java/index.adoc
> +* 基数统计 HyperLogLog - Commands to approximating the number of distinct elements in a multiset, a HyperLogLog.
Commands to approximating the number of distinct elements in a multiset, a HyperLogLog.
基数统计。对可重复集合中统计不重复元素的命令。

2021-02-06 13:55 UTC, zxj5470 commented on docs/translation/vertx-redis-client/java/index.adoc
> +  // 客户端处理 REDIS URLs.
选用的数据库规范是URL的数字路径，密码是URL授权的密码字段。

2021-02-06 13:58 UTC, zxj5470 reviewed
submit review

2021-02-07 00:46 UTC, okou19900722 requested changes

2021-02-07 00:46 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
>  In order to give the user full flexibility, this decision should not be performed by the client. However a simple
已翻译，未删除

2021-02-07 00:46 UTC, okou19900722 commented on docs/translation/vertx-redis-client/java/index.adoc
>  Most of the examples shown connecting to a TCP sockets, however it is also possible to use Redis connecting to a UNIX
已翻译，未删除

2021-02-07 01:47 UTC, Leibnizhu approved these changes

2021-02-08 09:58 UTC, fofofofoxier commented on docs/translation/vertx-redis-client/java/index.adoc
> +在这种情况下，配置需要知道集群的一个或多个成员。
```suggestion
在这种情况下，需要配置一个或多个集群成员。
```
此处感觉不太合中文文法习惯，仅为建议。

2021-02-08 15:32 UTC, zxj5470 reviewed
review change

2021-02-09 02:30 UTC, fofofofoxier approved these changes

2021-02-09 02:33 UTC, merged