Feature vertx config
vertx-china/vertx-china.github.io pull request #118
Opened 2021-02-10 01:35 UTC by fofofofoxier

Feature vertx config #20

2021-02-10 01:50 UTC, chengenzhao requested changes

2021-02-10 01:50 UTC, chengenzhao commented on docs/metadata/3.9.0.jsx
> +    description: "一个用于配置Vert.x应用的可扩展方式",
```suggestion
    description: "一种用于配置Vert.x应用可扩展方式。",
```

2021-02-10 01:50 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
> +则添加如下依赖：
```suggestion
需在您的 build 描述中添加如下 _依赖_ ：
```

2021-02-10 01:50 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
>  * Maven (in your `pom.xml`):
```suggestion
* Maven（在您的 `pom.xml` 文件中）：
```

2021-02-10 01:50 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
>  * Maven (in your `pom.xml`):
还有gradle的build那个

2021-02-10 01:50 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
> +`link:../../apidocs/io/vertx/config/ConfigRetriever.html[ConfigRetriever]` 来使用这个配置中心：
```suggestion
`link:../../apidocs/io/vertx/config/ConfigRetriever.html[ConfigRetriever]` 以使用该配置中心：
```

2021-02-10 01:53 UTC, chengenzhao requested changes

2021-02-10 01:53 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +* Maven (在您的 `pom.xml` 文件):
```suggestion
* Maven（在您的 `pom.xml` 文件）：
```

2021-02-10 01:53 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +* Gradle (在您的 `build.gradle` 文件):
```suggestion
* Gradle（在您的 `build.gradle` 文件）：
```

2021-02-10 01:53 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +`link:../../apidocs/io/vertx/config/ConfigRetriever.html[ConfigRetriever]` 来使用这个配置中心：
```suggestion
`link:../../apidocs/io/vertx/config/ConfigRetriever.html[ConfigRetriever]` 以使用该配置中心：
```

2021-02-10 18:28 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
> +==== 设置配置中心
```suggestion
[[_configuring_the_store_5]]
==== 设置配置中心
```

2021-02-19 01:41 UTC, chengenzhao requested changes

2021-02-19 01:41 UTC, chengenzhao commented on docs/metadata/3.9.0.jsx
> +    description: "一种用于配置Vert.x应用的可扩展方式。",
```suggestion
    description: "一种适用于 Vert.x 配置的扩展方式。",
```

2021-02-23 09:39 UTC, chengenzhao approved these changes

2021-02-24 05:50 UTC, Leibnizhu requested changes

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +Consul配置中心扩展了 Vert.x Configuration Retriever 并
```suggestion
Consul配置中心扩展了 Vert.x Configuration Retriever ，
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +提供了从 https://www.consul.io[Consul] 获取配置的方法。
```suggestion
并提供了从 https://www.consul.io[Consul] 获取配置的方法。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +Consul配置中心扩展了 Vert.x Configuration Retriever 并
换行位置避免在中文中间，会导致多余的空格。

逗号是我觉得加个断句默读起来顺一点。

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +要使用Consul配置中心
```suggestion
使用Consul配置中心
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +要使用Consul配置中心
中文习惯。  
另外这里换行自己改下吧

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +需在您的构建描述中添加如下 _依赖_ ：
```suggestion
需在您的项目构建配置中添加如下 _依赖_ ：
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +以下为指定Consul配置中心所需的参数：
```suggestion
以下为设置 Consul 配置中心所需的参数：
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +用 `config.getString(key)` 来获取原始数据。默认为 `true` 。
在”用“后面换行，自己改下吧

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/consul-store.adoc
> +`raw-data`:: 如果 `raw-data` 为 `true` ，则值不会被转换，并且您可以
```suggestion
`raw-data`:: 如果 `raw-data` 为 `true` ，则配置值不会进行类型转换，并且您可以
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +git配置中心是对 Vert.x Configuration Retriever 的扩展，用于
一样的换行问题，逗号后面换行，自己改下

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +要使用Git配置中心，则
换行问题。可以本地预览看看。

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +* `idRsaKeyPath` ：私有仓库的 ssh uri
```suggestion
* `idRsaKeyPath` ：私有仓库所需的 ssh rsa 密钥 uri
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +合（与配置中心的目录配置意义相同）
换行，括号前换行

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +您也可以配置 `branch` 参数 （默认为 `master` ）来使用
```suggestion
您也可以配置要使用的分支（ `branch` 参数，默认为 `master` ），以及
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +`远程` 仓库（默认为 `origin` ）
```suggestion
远程仓库名（ `remote` 参数，默认为 `origin` ）
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +如果本地的 `path` 参数不存在，那么配置中心会clone远程仓库到
```suggestion
如果本地的仓库目录（由 `path` 参数指定）不存在，那么配置中心会 clone 远程仓库到这个本地目录。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +这个本地目录。然后它会读取符合不同filesets的文件。
```suggestion
然后它会读取符合 `fileset` 配置的文件。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +如果本地的 `path` 参数存在，它会尝试更新（如果需要，则切换分支）。如果更新失败
```suggestion
如果本地的仓库目录（由 `path` 参数指定）存在，它会尝试更新（按需切换分支）。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +则配置获取失败。
```suggestion
如果更新失败，则视为获取配置失败。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/git-store.adoc
> +配置中心会周期性更新git仓库来检查配置是否跟更新。
```suggestion
配置中心会周期性更新 git 仓库来检查配置是否更新。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/hocon-format.adoc
> +对 HOCON格式(https://github.com/typesafehub/config/blob/master/HOCON.md) 的支持
继续，换行问题

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/hocon-format.adoc
> +它支持json、properties、macros……
```suggestion
它支持 json、properties、macros 等格式
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +Vert.x Config 提供了一种配置您的Vert.x应用的方式。
```suggestion
您可以使用 Vert.x Config 配置 Vert.x 应用。
```
原来翻译也正确，但感觉不通顺

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +**Config Retriever** 实例化并被Vert.x应用所使用。它配置了一系列配置中心（Configuration store）
```suggestion
**Config Retriever** 的实例化，并用于 Vert.x 应用。
它配置了一系列配置中心（Configuration store）
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +默认情况下，Config Retriever被下列配置中心所配置（以此
括号前换行

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +默认情况下，Config Retriever被下列配置中心所配置（以此
另外这句话”被……所配置“不通顺。
可以考虑：
```suggestion
默认情况下，Config Retriever 可以使用下列配置中心进行配置
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +`可选的（optional）` 。如果正在从一个可选的配置中心中获取（或处理）配置的时候，捕获到一个失败事件，那么这个失败事件会
换行注意下

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +`可选的（optional）` 。如果正在从一个可选的配置中心中获取（或处理）配置的时候，捕获到一个失败事件，那么这个失败事件会
下面不再提示换行问题了，自己检查下。

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +一旦你拥有了 Config Retriever 示例， 按如下
```suggestion
获取 Config Retriever 示例后，可按如下
```
”一旦“一般有贬义

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +获取到的配置允许：
```suggestion
获取到的配置可用于：
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +更多信息可见于 extensions，并且您可以也自己实现
这里”可见于 extensions“啥意思

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +大整型数时，这很有用。
没用过vertx-config，但我怀疑这里 ” when manipulating large integers“，是指操作”大量“整形数，而不是”大的“整形数？用raw是为了避免解析数字字符串带来的开销？对于单个的整形数，数值本身大小对解析开销有影响但不大，所以怀疑是”大量“的整形数（另外注意这里”integers“是复数形式）。  
不过再读了下感觉又不像，不是很确定。 @chengenzhao

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +大整型数时，这很有用。
同上

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +提醒Vert.x不要转换它的值。这在操作大整型数字时很有用。这些值可以
同上

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/kubernetes-store.adoc
> +Kubernetes ConfigMap 配置中心扩展了 Vert.x Configuration Retriever 并提供了 对于 Kubernetes 的 ConfigMap 和 Secrets 的支持。所以，配置是从k8s里的configMap或者secret对象中读取的。
```suggestion
Kubernetes ConfigMap 配置中心扩展了 Vert.x Configuration Retriever 并提供了 对于 Kubernetes 的 ConfigMap 和 Secrets 的支持。
所以，配置是从 k8s 里的 configMap 或者 secret 对象中读取的。
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +
```suggestion
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +
多了空行

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +1000 ms by default.
```suggestion
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
>  * `maxRetries`: the number of connection attempt, 3 by default
漏了没删？

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +这项配置必须需要 `configuration` 属性来指示zk服务的connection _string_ ，还要 `path` 属性来
这里有点奇怪？参照上面代码，应该是用 `connection` 属性吧？确认下？
```suggestion
这项配置必须需要 `connection ` 属性指定zk服务的连接 _字符串_ （译者注：英文逗号隔开的多个zk服务节点），
```

2021-02-24 05:50 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +指示节点的路径
```suggestion
以及 `path` 属性指定包含配置项的节点（znode）的路径。
```

2021-02-25 01:42 UTC, chengenzhao approved these changes

2021-02-25 01:42 UTC, chengenzhao commented on docs/translation/vertx-config/java/zookeeper-store.adoc
>  * `maxRetries`: the number of connection attempt, 3 by default
```suggestion
```

2021-02-25 01:42 UTC, chengenzhao commented on docs/translation/vertx-config/java/zookeeper-store.adoc
>  * `baseSleepTimeBetweenRetries`: the amount of milliseconds to wait between retries (exponential backoff strategy).
```suggestion
```

2021-02-25 01:43 UTC, Leibnizhu commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +额外您可以配置：
```suggestion
您还可以额外配置：
```

2021-02-25 01:45 UTC, chengenzhao commented on docs/translation/vertx-config/java/zookeeper-store.adoc
> +这项配置必须需要 `configuration` 属性来指示zk服务的connection _string_ ，还要 `path` 属性来
```suggestion
这项配置必须需要 `connection` 属性来指示zk服务的connection _string_ ，以及 `path` 属性来
```

2021-02-25 01:48 UTC, chengenzhao approved these changes

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +git配置中心是对 Vert.x Configuration Retriever 的扩展，用于
```suggestion
git配置中心是对 Vert.x Configuration Retriever 的扩展，
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +从Git仓库获取配置。
```suggestion
用于从Git仓库获取配置。
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +要使用Git配置中心，则
```suggestion
要使用Git配置中心，
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +添加如下依赖：
```suggestion
则添加如下依赖：
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +* `fileset` ：指定要读取的文件集
```suggestion
* `fileset` ：指定要读取的文件集合
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/git-store.adoc
> +合（与配置中心的目录配置意义相同）
```suggestion
（与配置中心的目录配置意义相同）
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/hocon-format.adoc
> +对 HOCON格式(https://github.com/typesafehub/config/blob/master/HOCON.md) 的支持
```suggestion
（https://github.com/typesafehub/config/blob/master/HOCON.md）的支持
```

2021-02-25 01:48 UTC, chengenzhao commented on docs/translation/vertx-config/java/hocon-format.adoc
> +Hocon 配置格式扩展了 Vert.x Configuration Retriever 并提供了
```suggestion
Hocon 配置格式扩展了 Vert.x Configuration Retriever 并提供了对 HOCON 格式
```

2021-02-25 01:49 UTC, chengenzhao approved these changes

2021-02-25 01:49 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
> +`raw-data`:: 如果 `raw-data` 为 `true` ，则配置值不会进行类型转换，并且您可以
```suggestion
`raw-data`:: 如果 `raw-data` 为 `true` ，则配置值不会进行类型转换，并且您可以用
```

2021-02-25 01:49 UTC, chengenzhao commented on docs/translation/vertx-config/java/consul-store.adoc
> +用 `config.getString(key)` 来获取原始数据。默认为 `true` 。
```suggestion
`config.getString(key)` 来获取原始数据，默认为 `true` 。
```

2021-02-25 01:54 UTC, chengenzhao approved these changes

2021-02-25 01:54 UTC, chengenzhao commented on docs/translation/vertx-config/java/index.adoc
> +如下可见更多关于覆盖规则和可用配置中心的细节信息。每一种配置中心都可以标记为
```suggestion
如下可见更多关于覆盖规则和可用配置中心的细节信息。每一种配置中心都可以标记为`可选的（optional）` 。
```

2021-02-25 01:54 UTC, chengenzhao commented on docs/translation/vertx-config/java/index.adoc
> +`可选的（optional）` 。如果正在从一个可选的配置中心中获取（或处理）配置的时候，捕获到一个失败事件，那么这个失败事件会
```suggestion
如果正在从一个可选的配置中心中获取（或处理）配置的时候，捕获到一个失败事件，那么这个失败事件会被日志所记录，但是执行过程并没有失败。
```

2021-02-25 01:54 UTC, chengenzhao commented on docs/translation/vertx-config/java/index.adoc
> +被日志所记录，但是执行过程并没有失败。相反的，会返回一个空的Json object （即： `{}` ）。
```suggestion
相反会返回一个空的 Json object（即：`{}`）。
```

2021-02-25 05:20 UTC, Leibnizhu commented on docs/metadata/3.9.0.jsx
> +    description: "一种适用于 Vert.x 配置的扩展方式。",
```suggestion
    description: "为 Vert.x 应用提供了一种可扩展的配置方式。",
```

2021-02-25 05:24 UTC, Leibnizhu commented on docs/translation/vertx-config/java/index.adoc
> +更多信息可见于 extensions，您可以也自己实现.
```suggestion
更多可用的配置中心请参考本文后续介绍的扩展，您可以也自己实现.
```

2021-02-25 05:44 UTC, Leibnizhu approved these changes

2021-02-25 05:45 UTC, Leibnizhu commented
![image](https://user-images.githubusercontent.com/13050963/109109068-a2b86200-776f-11eb-8efd-39b21e5c89ef.png)
这个地方（一共三四处，一样的）斟酌下，其他地方没问题了

2021-02-25 06:58 UTC, merged