vertx-pg-client 中文翻译
vertx-china/vertx-china.github.io pull request #121
Opened 2021-02-15 03:12 UTC by CatCodeMe

- 请大佬雅正

2021-02-19 03:05 UTC, okou19900722 requested changes

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 用法
```suggestion
[[_usage]]
== 用法
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 开始使用
```suggestion
[[_getting_started]]
== 开始使用
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 连接PostgreSQL
```suggestion
[[_connecting_to_postgresql]]
== 连接PostgreSQL
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 重连
```suggestion
[[_connect_retries]]
== 重连
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 配置
```suggestion
[[_configuration]]
== 配置
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
>  === data object
```suggestion
[[_data_object]]
=== data object
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== 连接uri
```suggestion
[[_connection_uri]]
=== 连接uri
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== 环境变量
```suggestion
[[_environment_variables]]
=== 环境变量
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== SASL SCRAM-SHA-256 鉴权机制.
```suggestion
[[_sasl_scram_sha_256_authentication_mechanism]]
=== SASL SCRAM-SHA-256 鉴权机制.
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/queries.adoc
> +== 执行查询
```suggestion
[[_running_queries]]
== 执行查询
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/queries.adoc
> +=== 预查询
```suggestion
[[_prepared_queries]]
=== 预查询
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/queries.adoc
> +=== 批处理
```suggestion
[[_batches]]
=== 批处理
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/connections.adoc
> +== 使用连接
```suggestion
[[_using_connections]]
== 使用连接
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/connections.adoc
> +=== 获取一条连接
```suggestion
[[_getting_a_connection]]
=== 获取一条连接
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/connections.adoc
> +=== 简化的连接API
```suggestion
[[_simplified_connection_api]]
=== 简化的连接API
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +== 事务
```suggestion
[[_using_transactions]]
== 事务
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +=== 连接中使用事务操作
```suggestion
[[_transactions_with_connections]]
=== 连接中使用事务操作
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +=== 简化版事务API
```suggestion
[[_simplified_transaction_api]]
=== 简化版事务API
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +== 游标和流式操作
```suggestion
[[_cursors_and_streaming]]
== 游标和流式操作
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 跟踪查询
```suggestion
[[_tracing_queries]]
== 跟踪查询
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== PostgreSQL 类型映射
```suggestion
[[_postgresql_type_mapping]]
== PostgreSQL 类型映射
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== JSON
```suggestion
[[_handling_json]]
=== JSON
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== 数字类型(Numeric)
```suggestion
[[_handling_numeric]]
=== 数字类型(Numeric)
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 数组
```suggestion
[[_handling_arrays]]
== 数组
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 日期/时间类型(Date/Time)的最值
```suggestion
[[_handling_datetime_infinity]]
== 日期/时间类型(Date/Time)的最值
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 自定义类型
```suggestion
[[_handling_custom_types]]
== 自定义类型
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 文本检索
```suggestion
[[_handling_text_search]]
== 文本检索
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 枚举类型
```suggestion
[[_handling_enumerated_types]]
== 枚举类型
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 使用Java枚举类型
```suggestion
[[_using_java_enum_types]]
== 使用Java枚举类型
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== Collector式查询
```suggestion
[[_collector_queries]]
== Collector式查询
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 发布/订阅
```suggestion
[[_pubsub]]
== 发布/订阅
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 取消请求
```suggestion
[[_cancelling_request]]
== 取消请求
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 使用 SSL/TLS
```suggestion
[[_using_ssltls]]
== 使用 SSL/TLS
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/index.adoc
> +== 使用代理
```suggestion
[[_using_a_proxy]]
== 使用代理
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
>  == RxJava 2 API
```suggestion
[[_rxjava_2_api]]
== RxJava 2 API
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +=== 连接
```suggestion
[[_connection]]
=== 连接
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +=== 事务
```suggestion
[[_transaction]]
=== 事务
```

2021-02-19 03:05 UTC, okou19900722 commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +=== 流式操作
```suggestion
[[_streaming]]
=== 流式操作
```

2021-02-19 03:07 UTC, CatCodeMe commented
正在本地加锚点

2021-02-19 03:09 UTC, CatCodeMe commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
>  == RxJava 2 API
第一行的大标题就不用加了吧。后续的正文行数就该对不上了

2021-02-23 08:28 UTC, chengenzhao requested changes

2021-02-23 08:28 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/connections.adoc
> +这样会从连接池里拿到一条连接, 并使用当前连接执行目标操作.
```suggestion
这样会从连接池里拿到一条连接, 并使用当前连接执行目标操作。
```

2021-02-23 08:28 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/connections.adoc
> +这样会从连接池里拿到一条连接, 并使用当前连接执行目标操作.
句点.需要统一更换成。

2021-02-23 08:28 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override.adoc
> +可以从连接池里拿到一条连接:
```suggestion
可以从连接池里拿到一条连接：
```

2021-02-23 08:28 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override.adoc
> +可以从连接池里拿到一条连接:
:也需要统一更换成：

2021-02-23 08:28 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override.adoc
> +=== 事务
```suggestion
[[_transaction]]
=== 事务
```

2021-02-23 08:48 UTC, chengenzhao requested changes

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +游标释放时需要同时执行关闭操作:
```suggestion
游标释放时需要同时执行关闭操作：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +stream API也可以用于游标, 尤其是在Rx版的客户端, 可能更为方便.
```suggestion
stream API也可以用于游标，尤其是在Rx版的客户端，可能更为方便。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +上边的stream会批量读取 `50` 行并同时将其转换为流, 当这些行记录被传递给处理器时,
```suggestion
上边的stream会批量读取 `50` 行并同时将其转换为流，当这些行记录被传递给处理器时，
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +会以此类推地读取下一批的 `50` 行记录.
```suggestion
会以此类推地读取下一批的 `50` 行记录。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +stream支持重启或暂停, 已经加载到的行记录将会被保留在内存里直到被传递给处理器, 此时
```suggestion
stream支持重启或暂停，已经加载到的行记录将会被保留在内存里直到被传递给处理器，此时
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/cursor.adoc
> +游标也将终止遍历.
```suggestion
游标也将终止遍历。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +客户端
```suggestion
客户端。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +客户端是响应式和非阻塞的, 可以仅仅使用一条线程来处理大量的数据库连接
```suggestion
客户端是响应式和非阻塞的, 可以仅仅使用一条线程来处理大量的数据库连接。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +在 _dependencies_ 里添加如下依赖来引入响应式PostgreSQL客户端:
```suggestion
在 _dependencies_ 里添加如下依赖来引入响应式PostgreSQL客户端：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +* Maven (在您的 `pom.xml` 文件里):
```suggestion
* Maven（在您的 `pom.xml` 文件里）：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +* Gradle (在您的 `build.gradle` 文件里):
```suggestion
* Gradle（在您的 `build.gradle` 文件里）：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +池化PostgreSQL客户端使用连接池去执行数据库操作,
```suggestion
池化PostgreSQL客户端使用连接池去执行数据库操作，
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +所有操作都会遵循从池里拿到连接、执行、释放连接到池里这三个步骤
```suggestion
所有操作都会遵循从池里拿到连接、执行、释放连接到池里这三个步骤。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以传入一个连接池到正在运行的Vert.x实例里:
```suggestion
您可以传入一个连接池到正在运行的Vert.x实例里：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +如果不再需要连接池, 您需要释放它:
```suggestion
如果不再需要连接池，您需要将其释放：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +当您想要在同一条连接上执行多个操作时, 您需要使用客户端
```suggestion
当您想要在同一条连接上执行多个操作时，您需要使用客户端
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以很方便地从连接池里拿到一条连接:
```suggestion
您可以很方便地从连接池里拿到一条连接：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +为了连接可以重用, 一旦当前连接上的操作已经完成, 您需要关闭并释放连接到连接池里.
```suggestion
为了连接可以重用，一旦当前连接上的操作已经完成，您需要关闭并释放连接到连接池里。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +某些情况下您希望通过Unix domain socket类型的连接来提升性能, 我们通过Vert.x本机传输支持了这种方式.
```suggestion
某些情况下您希望通过Unix domain socket类型的连接来提升性能，我们通过Vert.x本机传输支持了这种方式。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +首先确保您已经在classpath下添加了 `netty-transport-native` 这个必须的依赖, 同时开启了Unix domain socket功能(pg)选项.
```suggestion
首先确保您已经在classpath下添加了 `netty-transport-native` 这个必须的依赖，同时开启了Unix domain socket功能(pg)选项。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +更多详情可以在这里找到 https://vertx.io/docs/vertx-core/java/#_native_transports[Vert.x documentation].
```suggestion
更多详情可以在这里找到 https://vertx.io/docs/vertx-core/java/#_native_transports[Vert.x documentation]。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +如下有几种配置客户端的可选方案
```suggestion
有如下几种配置客户端的可选方案。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +通过指定 `PgConnectOptions` 数据对象是一种简单的客户端的配置方式
```suggestion
通过指定 `PgConnectOptions` 数据对象是一种简单的客户端的配置方式。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +比如, 您可以通过添加 `search_path` 属性来配置一个默认的schema.
```suggestion
例如，您可以通过添加 `search_path` 属性来配置一个默认的schema。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +关于可用属性的更多信息可以在这里找到 https://www.postgresql.org/docs/current/runtime-config-client.html[PostgreSQL Manuals].
```suggestion
关于可用属性的更多信息可以在这里找到 https://www.postgresql.org/docs/current/runtime-config-client.html[PostgreSQL Manuals]。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +除了使用 `PgConnectionOptions` 对象, 我们也提供了另一种基于URI的可选配置方案
```suggestion
除了使用 `PgConnectionOptions` 对象, 我们也提供了另一种基于URI的可选配置方案：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +关于连接uri字符串格式的更多信息可以在这里找到 https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING[PostgreSQL Manuals]
```suggestion
关于连接uri字符串格式的更多信息可以在这里找到 https://www.postgresql.org/docs/9.6/static/libpq-connect.html#LIBPQ-CONNSTRING[PostgreSQL Manuals]。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +注意: 通过URI配置的属性将会覆盖默认的配置属性.
```suggestion
注意：通过URI配置的属性将会覆盖默认的配置属性。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您也可以使用环境变量来设置连接的属性值, 以此来避免硬编码数据库连接信息.
```suggestion
您也可以使用环境变量来设置连接的属性值，以此来避免硬编码数据库连接信息。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以参考 https://www.postgresql.org/docs/9.6/static/libpq-envars.html[官方文档]来了解更多详情.
```suggestion
您可以参考 https://www.postgresql.org/docs/9.6/static/libpq-envars.html[官方文档]来了解更多详情。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +目前支持下列这些配置参数:
```suggestion
目前支持下列这些配置参数：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +如果您没有在连接时指定连接对象或者URI字符串, 此时将会使用到环境变量.
```suggestion
如果您没有在连接时指定连接对象或者URI字符串，此时将会使用环境变量。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +=== SASL SCRAM-SHA-256 鉴权机制.
```suggestion
=== SASL SCRAM-SHA-256 鉴权机制。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +为了使用 sasl SCRAM-SHA-256鉴权, 需要在 _dependencies_ 里添加如下依赖:
```suggestion
为了使用 sasl SCRAM-SHA-256鉴权，需要在 _dependencies_ 里添加如下依赖：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +* Maven (在您的 `pom.xml` 文件里):
```suggestion
* Maven（在您的 `pom.xml` 文件里）：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +* Gradle (在您的 `build.gradle` 文件里):
```suggestion
* Gradle（在您的 `build.gradle` 文件里）：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +注意 SCRAM-SHA-256-PLUS(在Postgresql 11加入)当前版本客户端暂不支持.
```suggestion
注意 SCRAM-SHA-256-PLUS（在Postgresql 11中加入）当前版本客户端暂不支持。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以使用 'RETURNING' 从查询里拿到生成的key:
```suggestion
您可以使用 'RETURNING' 从查询里拿到生成的key：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +注意: PostreSQL会在事务结束后销毁游标, 因而游标API应该在事务内使用,
```suggestion
Note: PostreSQL会在事务结束后销毁游标，因而游标API应该在事务内使用，
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +否则您将可能收到 `34000` PostgreSQL错误码.
```suggestion
否则您将可能收到 `34000` PostgreSQL错误码。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +Tuple(元组)在解码时使用上述类型映射关系存储解码出的值, 并且在合法的条件下可以动态转换为实际类型的值:
```suggestion
Tuple（元组）在解码时使用上述类型映射关系存储解码出的值，并且在合法的条件下可以动态转换为实际类型的值：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +Tuple(元组)编码时使用上述关系作为类型间的映射关系, 除非类型为数字, 在这种情况下将会使用 `java.lang.Number`:
```suggestion
Tuple（元组）编码时使用上述关系作为类型间的映射关系，除非类型为数字，在这种情况下将会使用 `java.lang.Number`：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +上述类型的数组形式也是支持的.
```suggestion
上述类型的数组形式也是支持的。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +PostgreSQL的 `JSON` 和 `JSONB`  用下列的java类型表示:
```suggestion
PostgreSQL的 `JSON` 和 `JSONB`  用下列的java类型表示：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +java的 `link:../../apidocs/io/vertx/sqlclient/data/Numeric.html[Numeric]` 用来表示PostgreSQL的 `NUMERIC` 类型.
```suggestion
java的 `link:../../apidocs/io/vertx/sqlclient/data/Numeric.html[Numeric]` 用来表示PostgreSQL的 `NUMERIC` 类型。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +数组可以用在 `link:../../apidocs/io/vertx/sqlclient/Tuple.html[Tuple]` 和 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]`:
```suggestion
数组可以用在 `link:../../apidocs/io/vertx/sqlclient/Tuple.html[Tuple]` 和 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]`：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +PostgreSQL定义了几个特殊的值用来表示这些最值.
```suggestion
PostgreSQL定义了几个特殊的值用来表示这些最值。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +相应类型的最大/最小值由这些常量 https://www.postgresql.org/docs/9.0/datatype-datetime.html[特殊值] 表示.
```suggestion
相应类型的最大/最小值由这些常量 https://www.postgresql.org/docs/9.0/datatype-datetime.html[特殊值] 表示。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +发送和从Postgres接收的自定义类型都由字符串来表示.
```suggestion
发送和从Postgres接收的自定义类型都由字符串来表示。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +PostgreSQL的 https://www.postgresql.org/docs/9.1/datatype-enum.html[枚举类型] 被映射为java的字符串.
```suggestion
PostgreSQL的 https://www.postgresql.org/docs/9.1/datatype-enum.html[枚举类型] 被映射为java的字符串。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +映射为下列这些列类型:
```suggestion
映射为下列这些列类型：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +String and PostgreSQL enumerated types 对应Java枚举类的 `name()` 方法的返回值.
```suggestion
String and PostgreSQL enumerated types 对应Java枚举类的 `name()` 方法的返回值。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +Numbers类型对应Java枚举类的 `ordinal()` 方法的返回值.
```suggestion
Numbers类型对应Java枚举类的 `ordinal()` 方法的返回值。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以将Java collector与查询API结合使用:
```suggestion
您可以将Java collector与查询API结合使用：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +pg客户端在处理collector时, 只会用一个row用于处理整个集合.
```suggestion
pg客户端在处理collector时，只会用一个row用于处理整个集合。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +collector式查询的结果集处理过程中不能再拿到 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]` 的引用, 因为
```suggestion
collector式查询的结果集处理过程中不能再拿到 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]` 的引用，因为
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +从row集合里得到一个字符串:
```suggestion
从row集合里得到一个字符串：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +接收PostgreSQL的通知消息:
```suggestion
接收PostgreSQL的通知消息：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +处理单条连接上的订阅的通道(channel)管理器:
```suggestion
处理单条连接上的订阅的通道（channel）管理器：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +channel()方法的参数即通道名称(接收端)需要和PostgreSQL发送通知时的通道名称保持一致.
```suggestion
channel（通道）方法的参数即通道名称（接收端）需要和PostgreSQL发送通知时的通道名称保持一致。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +注意这里和SQL中的通道名称的形式不同, 在 `link:../../apidocs/io/vertx/pgclient/pubsub/PgSubscriber.html[PgSubscriber]`
```suggestion
注意这里和SQL中的通道名称的形式不同，在 `link:../../apidocs/io/vertx/pgclient/pubsub/PgSubscriber.html[PgSubscriber]`
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +内部会把待提交的通道名称预处理为带引号的形式:
```suggestion
内部会把待提交的通道名称预处理为带引号的形式：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以自定义一个方法来实现重连, 该方法的参数为 `retries` (重试次数),
```suggestion
您可以自定义一个方法来实现重连，该方法的参数为 `retries` （重试次数），
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +返回值为 `amountOfTime` (重试间隔):
```suggestion
返回值为 `amountOfTime`（重试间隔）：
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +* 当 `amountOfTime < 0`: 不重试, 并关闭订阅
```suggestion
* 当 `amountOfTime < 0`: 不重试，并关闭订阅
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +默认的策略是不重连.
```suggestion
默认的策略是不重连。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +PostgreSQL 支持取消正在运行的请求. 您可以使用 `link:../../apidocs/io/vertx/pgclient/PgConnection.html#cancelRequest-io.vertx.core.Handler-[cancelRequest]` 正在运行的请求. 取消请求的操作在执行时将和PostgreSQL服务端新建一条连接、执行取消请求、关闭这条连接.
```suggestion
PostgreSQL 支持取消正在运行的请求. 您可以使用 `link:../../apidocs/io/vertx/pgclient/PgConnection.html#cancelRequest-io.vertx.core.Handler-[cancelRequest]` 正在运行的请求. 取消请求的操作在执行时将和PostgreSQL服务端新建一条连接、执行取消请求、关闭这条连接。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +> 取消请求可能不会起作用 -- 如果请求到达时, 服务端已经处理完了当前查询请求, 此时取消操作不会起作用. 反之, 取消请求得以执行, 目标命令执行提前终止并返回一条错误消息.
```suggestion
> 取消请求可能不会起作用——如果请求到达时，服务端已经处理完了当前查询请求，此时取消操作不会起作用。反之，取消请求得以执行，目标命令执行提前终止并返回一条错误消息。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +更多详细信息可以在这里找到 https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.9[official documentation].
```suggestion
更多详细信息可以在这里找到 https://www.postgresql.org/docs/11/protocol-flow.html#id-1.10.5.7.9[official documentation]。
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +为客户端连接添加SSL的操作, 您可以参考Vert.x的
```suggestion
为客户端连接添加SSL的操作，您可以参考Vert.x的
```

2021-02-23 08:48 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +`NetClient` 的 `link:../../apidocs/io/vertx/pgclient/PgConnectOptions.html[PgConnectOptions]` 配置操作.
```suggestion
`NetClient` 的 `link:../../apidocs/io/vertx/pgclient/PgConnectOptions.html[PgConnectOptions]` 配置操作。
```

2021-02-23 09:03 UTC, chengenzhao approved these changes

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +当前版本客户端支持全部的PostgreSql https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION[SSL模式]配置, 您可以通过 `sslmode` 配置它们.客户端默认不启用SSL模式.
```suggestion
当前版本客户端支持全部的PostgreSql https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION[SSL模式]配置，您可以通过 `sslmode` 配置它们。客户端默认不启用SSL模式。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +`ssl` 参数仅作为一种设置 `sslmode` 的快捷方式. `setSsl(true)` 等价于 `setSslMode(VERIFY_CA)` , `setSsl(false)` 等价于 `setSslMode(DISABLE)`.
```suggestion
`ssl` 参数仅作为一种设置 `sslmode` 的快捷方式。 `setSsl(true)` 等价于 `setSslMode(VERIFY_CA)`，`setSsl(false)` 等价于 `setSslMode(DISABLE)`。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +更多详细信息可以在这里找到 http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation].
```suggestion
更多详细信息可以在这里找到 http://vertx.io/docs/vertx-core/java/#ssl[Vert.x documentation]。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +您可以配置客户端使用HTTP/1.x 连接, SOCKS4a 或 SOCKS5 代理.
```suggestion
您可以配置客户端使用HTTP/1.x 连接，SOCKS4a 或 SOCKS5 代理。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +更多信息可以在这里找到 http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation].
```suggestion
更多信息可以在这里找到 http://vertx.io/docs/vertx-core/java/#_using_a_proxy_for_client_connections[Vert.x documentation]。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override.adoc
> +Rx风格的API支持RxJava 1 和 RxJava 2, 下边的例子使用的是 RxJava 2.
```suggestion
Rx风格的API支持RxJava 1 和 RxJava 2，下边的例子使用的是 RxJava 2。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +Rx风格的API支持 RxJava 1 and RxJava 2, 下边的例子使用的是 RxJava 2.
```suggestion
Rx风格的API支持 RxJava 1 and RxJava 2，下边的例子使用的是 RxJava 2。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +简化版的连接API可以让您很容易地使用connection对象,  `withConnection`
```suggestion
简化版的连接API可以让您很容易地使用connection对象，`withConnection`
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +方法会从连接池里拿到一条连接:
```suggestion
方法会从连接池里获取到一条连接：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +简化版的事务API可以让您很容易地编写异步事务处理流,  `withTransaction`
```suggestion
简化版的事务API可以让您很容易地编写异步事务处理流，`withTransaction`
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +方法会为您启动和提交事务:
```suggestion
方法会为您启动和提交事务：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +RxJava 2 支持 `Observable` 和 `Flowable` 类型, 这些类型可以从 `link:../../apidocs/io/vertx/reactivex/sqlclient/PreparedQuery.html[PreparedQuery]`
```suggestion
RxJava 2 支持 `Observable` 和 `Flowable` 类型，这些类型可以从 `link:../../apidocs/io/vertx/reactivex/sqlclient/PreparedQuery.html[PreparedQuery]`
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +里获取到:
```suggestion
里获取到：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/override/rxjava2.adoc
> +下边是使用 `Flowable` 的例子:
```suggestion
下边是使用 `Flowable` 的例子：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +当您不需要事务或者只是执行一个单次查询操作, 您可以直接在连接池里执行查询;
```suggestion
当您不需要事务或者只是执行一个单次查询操作，您可以直接在连接池里执行查询；
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +连接池会使用某一条连接执行并给您返回结果.
```suggestion
连接池会使用某一条连接执行并给您返回结果。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +下边是如何执行一个简单的查询的例子:
```suggestion
下边是如何执行一个简单的查询的例子：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +执行预查询也是一样的操作.
```suggestion
执行预查询也是一样的操作。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +SQL字符通过位置引用实际的参数, 并使用数据库的语法 {PREPARED_PARAMS}
```suggestion
SQL字符通过位置引用实际的参数，并使用数据库的语法 {PREPARED_PARAMS}
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +或者 _UPDATE_/_INSERT_ 类型的查询:
```suggestion
或者 _UPDATE_/_INSERT_ 类型的查询：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +Row对象(`link:../../apidocs/io/vertx/sqlclient/Row.html[Row]`) 可以让您通过索引位置获取相应的数据
```suggestion
Row对象（`link:../../apidocs/io/vertx/sqlclient/Row.html[Row]`）可以让您通过索引位置获取相应的数据
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +客户端在此处没有做特殊处理, 无论您的SQL文本时什么, 列名都将使用数据库表中的名称标识.
```suggestion
客户端在此处没有做特殊处理，无论您的SQL文本时什么，列名都将使用数据库表中的名称标识。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +您可以使用缓存过的预处理语句去执行一次性的预查询:
```suggestion
您可以使用缓存过的预处理语句去执行一次性的预查询：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/queries.adoc
> +您也可以创建 `PreparedStatement` 并自主地管理它的生命周期.
```suggestion
您也可以创建 `PreparedStatement` 并自主地管理它的生命周期。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/tracing.adoc
> +您可以通过 `link:../../apidocs/io/vertx/sqlclient/SqlConnectOptions.html#setTracingPolicy-io.vertx.core.tracing.TracingPolicy-[setTracingPolicy]` 方法来调整tracing策略,
```suggestion
您可以通过 `link:../../apidocs/io/vertx/sqlclient/SqlConnectOptions.html#setTracingPolicy-io.vertx.core.tracing.TracingPolicy-[setTracingPolicy]` 方法来调整tracing策略，
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/tracing.adoc
> +默认的 tracing 策略时 `link:../../apidocs/io/vertx/core/tracing/TracingPolicy.html#PROPAGATE[PROPAGATE]`, 客户端
```suggestion
默认的 tracing 策略时 `link:../../apidocs/io/vertx/core/tracing/TracingPolicy.html#PROPAGATE[PROPAGATE]`，客户端
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/tracing.adoc
> +在一个活跃trace里只创建一个span.
```suggestion
在一个活跃trace里只创建一个span。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/tracing.adoc
> +e.g 您可以设置为 `link:../../apidocs/io/vertx/core/tracing/TracingPolicy.html#ALWAYS[ALWAYS]`,
```suggestion
例如您可以设置为 `link:../../apidocs/io/vertx/core/tracing/TracingPolicy.html#ALWAYS[ALWAYS]`，
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/tracing.adoc
> +客户端将始终上报span:
```suggestion
客户端将始终上报span：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +== 事务
```suggestion
== 使用事务
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +您可以使用SQL语法 `BEGIN`/`COMMIT`/`ROLLBACK` 来执行事务操作, 同时您必须使用
```suggestion
您可以使用SQL语法 `BEGIN`/`COMMIT`/`ROLLBACK` 来执行事务操作，同时您必须使用
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +`link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 并自己管理当前连接
```suggestion
`link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 并自己管理当前连接。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +或者您也可以使用 `link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 的事务API:
```suggestion
或者您也可以使用 `link:../../apidocs/io/vertx/sqlclient/SqlConnection.html[SqlConnection]` 的事务API：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +当数据库服务端返回当前事务已失败(比如常见的 _current transaction is aborted, commands ignored until end of transaction block_)
```suggestion
当数据库服务端返回当前事务已失败（比如常见的 _current transaction is aborted, commands ignored until end of transaction block_）
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +, 事务已回滚和 `link:../../apidocs/io/vertx/sqlclient/Transaction.html#completion--[completion]` 方法的返回值future返回了
```suggestion
，事务已回滚和 `link:../../apidocs/io/vertx/sqlclient/Transaction.html#completion--[completion]` 方法的返回值future返回了
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +`link:../../apidocs/io/vertx/sqlclient/TransactionRollbackException.html[TransactionRollbackException]` 异常时:
```suggestion
`link:../../apidocs/io/vertx/sqlclient/TransactionRollbackException.html[TransactionRollbackException]` 异常时：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +当您使用连接池时, 您可以调用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#withTransaction-java.util.function.Function-io.vertx.core.Handler-[withTransaction]` 方法
```suggestion
当您使用连接池时，您可以调用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#withTransaction-java.util.function.Function-io.vertx.core.Handler-[withTransaction]` 方法
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +并传递待执行的事务操作作为参数.
```suggestion
并传递待执行的事务操作作为参数。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +这将会从连接池里拿到一条连接, 开启事务并调用待执行操作, 配合客户端一起执行该事务范围内
```suggestion
这将会从连接池里拿到一条连接，开启事务并调用待执行操作，配合客户端一起执行该事务范围内
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +的所有操作.
```suggestion
的所有操作。
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +待执行操作需要返回一个future来表示可能产生的结果:
```suggestion
待执行操作需要返回一个future来表示可能产生的结果：
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +- 当future成功时, 客户端会提交该事务
```suggestion
- 当future成功时，客户端提交该事务
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +- 当future失败时, 客户端会回滚该事务
```suggestion
- 当future失败时，客户端回滚该事务
```

2021-02-23 09:03 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/transactions.adoc
> +事务操作完成后, 连接会被释放回连接池, 并且可以获取到最终的操作结果.
```suggestion
事务操作完成后，连接会被释放回连接池，并且可以获取到最终的操作结果。
```

2021-02-23 09:06 UTC, chengenzhao approved these changes

2021-02-23 09:06 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/index.adoc
> +注意：通过URI配置的属性将会覆盖默认的配置属性。
```suggestion
Note：通过URI配置的属性将会覆盖默认的配置属性。
```

2021-02-23 09:06 UTC, merged