micrometrics
vertx-china/vertx-china.github.io pull request #122
Opened 2021-02-15 16:14 UTC by fofofofoxier

fix #40

2021-02-17 02:15 UTC, Leibnizhu requested changes

2021-02-17 02:15 UTC, Leibnizhu commented on docs/metadata/3.9.0.jsx
> +    description: "使用Micrometer来监控Vert.x core组件，获取运行指标，并提供接口来使用",
表述上有点冗余且不太准确，可以：  
```suggestion
    description: "使用 Micrometer 获取 Vert.x core 组件的监控指标，并将指标对外开放",
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +* 向任何Micrometer支持的后端发送报告
```suggestion
* 向所有 Micrometer 支持的后端发送报告
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +按照 https://docs.influxdata.com/influxdb/latest/introduction/getting_started/[InfluxDb启动和运行说明] 。
```suggestion
按照 https://docs.influxdata.com/influxdb/latest/introduction/getting_started/[说明文档启动并运行 InfluxDb] 。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
>  == InfluxDB
```suggestion
[[_influxdb]]
== InfluxDB
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
>  == Prometheus
```suggestion
[[_prometheus]]
== Prometheus
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +按照 https://prometheus.io/docs/prometheus/latest/getting_started/[Prometheus启动和运行手册] 。
```suggestion
按照 https://prometheus.io/docs/prometheus/latest/getting_started/[手册启动并运行Prometheus] 。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +//=== Getting started
```suggestion
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +您也许需要 _vertx-web_ 来暴露指标。
```suggestion
您也许需要 _vertx-web_ 来开放监控指标。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +在Micrometer中， `step` 是指报告时间区间，以秒为单位。 `domain` 是
```suggestion
在Micrometer中， `step` 是指报告周期，以秒为单位。 `domain` 是
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +== 其他后台或组合
```suggestion
== 其他后端或其组合
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +它使用 link:http://micrometer.io/[Micrometer] 来管理运行指标并向后台报告。
```suggestion
它使用 link:http://micrometer.io/[Micrometer] 来管理运行指标并向后端报告。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +可用的后台包括 Graphite、Ganglia、Atlas、 link:http://micrometer.io/docs[等等] 。
```suggestion
可用的后端包括 Graphite、Ganglia、Atlas link:http://micrometer.io/docs[等等] 。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +它也允许 link:http://micrometer.io/docs/concepts#_composite_registries[Micrometer 组合注册] 从而可以向多个后台报告同一项指标。
```suggestion
它也允许 link:http://micrometer.io/docs/concepts#_composite_registries[Micrometer 组合注册] 从而可以向多个后端报告同一项指标。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +在以下例子中，指标同时被JMX 和 Graphite报告：
```suggestion
在以下例子中，指标同时向 JMX 和 Graphite报告：
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +要计算分位数，则有两个选择。第一种，激活全局分位数分析
```suggestion
要计算分位数，则有两个方案可选择。第一种，激活全局分位数分析，
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +这个选项的优点是可以在 `promql` 中跨维度聚合使用。
```suggestion
这个方案的优点是可以在 `promql` 中跨维度聚合使用。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +第二个选项是创建分析限制，不许跨维度聚合。
```suggestion
第二个方案是创建分析限制，不许跨维度聚合。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +并且让他们为 Prometheus 函数 `histogram_quantile` 所用：
```suggestion
并让 Prometheus 的 `histogram_quantile` 函数可以使用分位数：
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +复用一个已存在的 registry 是可能的（或从Prometheus java客户端获取 `CollectorRegistry` ），
```suggestion
您可以复用一个现存的 registry （或从Prometheus java客户端获取 `CollectorRegistry` ），
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +因为已经提供了对Micrometer registry的原始访问方式，所以利用 Micrometer API 是可能的。
```suggestion
因为已经提供了对Micrometer registry的原始访问方式，所以可以直接使用 Micrometer API 。
```
注意中文习惯

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +_详见link:http://micrometer.io/docs/ref/jvm[Micrometer 文档]。_
```suggestion
_详见 link:http://micrometer.io/docs/ref/jvm[Micrometer 文档]。_
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +在 Vert.x 4 中，默认指标名称出现了变化，目的在于更好的适应于后台约定，
```suggestion
在 Vert.x 4 中，默认指标名称出现了变化，目的在于更好的适应于后端约定，
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +但是用 Vert.x 3.x 名称以求兼容性依旧是可以的：
```suggestion
但是依旧可以用 Vert.x 3.x 的指标名称，以求兼容：
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +Vert.x Micrometer Metrics 定义了一系列label（aka tag 或 field）用于对某一指标提供维度。
```suggestion
Vert.x Micrometer Metrics 定义了一系列label（又称为 tag 或 field），用于对某一指标提供维度。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +例如，和事件总线消息相关的指标有 _address_ label，它允许对一个
```suggestion
例如，和事件总线消息相关的指标有 _address_ label，
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +事件总线地址查询时间序列，或者对比每个地址的时间序列，或者
```suggestion
它允许对一个事件总线地址查询时间序列，或者对比每个地址的时间序列，
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +做各种API允许的聚合操作。
```suggestion
或者做各种API允许的聚合操作。
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +例如，和事件总线消息相关的指标有 _address_ label，它允许对一个
不恰当的换行位置，会导致文档显示会多出很多无意义的空格，这三行是一起改的

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
```suggestion
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
多了一个空行？导致后面几行在review页面显示出来有些错行

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +一个所熟知的 _Measured_ 对象便是
```suggestion
一个所熟知的 _Measured_ 对象便是 `link:../../apidocs/io/vertx/core/Vertx.html[Vertx]` ：
```

2021-02-17 02:15 UTC, Leibnizhu commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +A well known _Measured_ object is simply `link:../../apidocs/io/vertx/core/Vertx.html[Vertx]` ：
```suggestion
```

2021-02-18 01:38 UTC, chengenzhao requested changes

2021-02-18 01:38 UTC, chengenzhao commented on docs/metadata/3.9.0.jsx
> +    description: "使用 Micrometer 获取 Vert.x core 组件的监控指标，并将指标对外开放",
```suggestion
    description: "使用 Micrometer 获取并展示 Vert.x core 组件的监控指标。",
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +Maven用户在pom文件中添加如下依赖：
```suggestion
Maven 用户应在 pom文件中添加如下依赖：
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +Vert.x默认情况下不开启SPI的实现。您必须在Vert.x options中启用它。
```suggestion
Vert.x默认情况下不开启SPI的实现。您必需在Vert.x options中启用。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +Vert.x默认情况下不开启SPI的实现。您必须在Vert.x options中启用它。
```suggestion
Vert.x默认情况下不开启SPI的实现。您必需在Vert.x options中将其启用。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +NOTE: Matchers 在底层使用的是 MeterFilters.
```suggestion
NOTE: Matchers 在底层使用的是 MeterFilters。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|队列中挂起状态的元素数量
```suggestion
|队列中挂起状态的元素数量。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|请求的大小（字节数）
```suggestion
|请求的大小（字节数）。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|当前打开状态的websocket数量
```suggestion
|当前打开状态的websocket数量。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|错误数.
```suggestion
|错误数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|HTTP Server接收的字节数
```suggestion
|HTTP Server接收的字节数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|HTTP Server发送的字节数
```suggestion
|HTTP Server发送的字节数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|HTTP Server开启的连接数
```suggestion
|HTTP Server开启的连接数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|错误数
```suggestion
|错误数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|当前正在执行状态的请求数
```suggestion
|当前正在执行状态的请求数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|执行完毕的请求数
```suggestion
|执行完毕的请求数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|被重置的请求数
```suggestion
|被重置的请求数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|请求大小（字节）
```suggestion
|请求大小（字节）。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|请求执行的时间（秒）
```suggestion
|请求执行的时间（秒）。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|响应大小（字节）
```suggestion
|响应大小（字节）。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|当前开启状态的websocket
```suggestion
|当前开启状态的websocket。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|发送到远程的字节总数
```suggestion
|发送到远程的字节总数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|错误总数
```suggestion
|错误总数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|从事件总线集群读取消息时接收到的总字节数
```suggestion
|从事件总线集群读取消息时接收到的总字节数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|向事件总线集群发送消息的总字节数
```suggestion
|向事件总线集群发送消息的总字节数。
```

2021-02-18 01:38 UTC, chengenzhao commented on docs/translation/vertx-micrometer-metrics/java/index.adoc
> +|接收的消息数
```suggestion
|接收的消息数。
```

2021-02-18 01:52 UTC, Leibnizhu approved these changes

2021-02-19 00:21 UTC, merged