json schema翻译完成以及mqtt的补充
vertx-china/vertx-china.github.io pull request #123
Opened 2021-02-24 06:53 UTC by Linindoo

2021-02-24 07:08 UTC, okou19900722 approved these changes

2021-02-24 07:08 UTC, okou19900722 commented on docs/translation/vertx-json-schema/java/index.adoc
> +* Maven (在`pom.xml`文件中):
```suggestion
* Maven （在 `pom.xml` 文件中）：
```

2021-02-24 07:08 UTC, okou19900722 commented on docs/translation/vertx-json-schema/java/index.adoc
> +* Gradle (在 `build.gradle` 文件中):
```suggestion
* Gradle （在 `build.gradle` 文件中）：
```

2021-02-24 07:08 UTC, okou19900722 commented on docs/translation/vertx-json-schema/java/index.adoc
> +需要注意的是，当使用 $ref` 引用schema或者处理相关的引用时，schema pointer 是必须的，
```suggestion
需要注意的是，当使用 `$ref` 引用schema或者处理相关的引用时，schema pointer 是必须的，
```

2021-02-24 07:08 UTC, okou19900722 commented on docs/translation/vertx-json-schema/java/index.adoc
> +[注意]
```suggestion
[NOTE]
```

2021-02-24 07:08 UTC, okou19900722 commented on docs/translation/vertx-mqtt/java/index.adoc
> +调用 `link:../../apidocs/io/vertx/mqtt/MqttServerOptions.html#setUseWebSocket-boolean-[setUseWebSocket]` 方法并设置参数为 `true`，
```suggestion
调用 `link:../../apidocs/io/vertx/mqtt/MqttServerOptions.html#setUseWebSocket-boolean-[setUseWebSocket]` 方法并设置参数为 `true` ，
```

2021-02-24 07:16 UTC, okou19900722 approved these changes

2021-02-24 07:16 UTC, okou19900722 commented on docs/metadata/4.0.0.jsx
> +  description: `Json模式规范的扩展实现，以异步的方式来校验每一个Json数据结构。`,
```suggestion
  description: "Json模式规范的扩展实现，以异步的方式来校验每一个Json数据结构。",
```

2021-02-24 07:16 UTC, okou19900722 commented on docs/metadata/4.0.2.jsx
> +  description: `Json模式规范的扩展实现，以异步的方式来校验每一个Json数据结构。`,
```suggestion
  description: "Json模式规范的扩展实现，以异步的方式来校验每一个Json数据结构。",
```

2021-02-26 02:38 UTC, Leibnizhu requested changes
问题不大，细节改改

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +为了使用Vert.x Json Schema，需要在构建描述符中添加如下 _依赖_：
```suggestion
为了使用 Vert.x Json Schema ，需要在构建配置文件中添加如下 _依赖_：
```
descriptor应该指描述文件

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +这种校验具有快速失败的特性：一旦遇到校验错误，校验就会直接失败而不再继续
```suggestion
这种校验具有 _快速失败_ 的特性：一旦遇到校验错误，校验就会直接失败而不再继续。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +当处理 `$ref` 的引用或者使用`link:../../apidocs/io/vertx/json/schema/SchemaParser.html[SchemaParser]` 解析新的schema时，这个schema就会被缓存到相应的 `link:../../apidocs/io/vertx/json/schema/SchemaRouter.html[SchemaRouter]` 中去。
```suggestion
当处理 `$ref` 的引用或者使用 `link:../../apidocs/io/vertx/json/schema/SchemaParser.html[SchemaParser]` 解析新的schema时，这个schema就会被缓存到相应的 `link:../../apidocs/io/vertx/json/schema/SchemaRouter.html[SchemaRouter]` 中去。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +当前提供的 `link:../../apidocs/io/vertx/json/schema/SchemaParser.html[SchemaParser]` 有：
```suggestion
当前可用的 `link:../../apidocs/io/vertx/json/schema/SchemaParser.html[SchemaParser]` 有：
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +对于不同的 `SchemaParser` ， 你可以复用同一个 `SchemaRouter` 实例，并且你还可以使用同一个的 `SchemaParser` 来解析不同的 `Schema` 。
```suggestion
对于不同的 `SchemaParser` ， 你可以复用同一个 `SchemaRouter` 实例；而且还可以使用同一个 `SchemaParser` 来解析不同的 `Schema` 。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +当你解析schema时必须要指定一个 **schema pointer**，这个 pointer 是定位schema的一个标识。
```suggestion
解析schema时，必须要指定一个 **schema pointer** ，这个 pointer 是定位 schema 的唯一标识。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +[重要]
```suggestion
[IMPORTANT]
```
固定格式 ，无需翻译。
okou原话：
> 这是固定格式，
> 一种是XXX:xxxxxx
> 一种是
> [XXX]
> ----
> xxxxxx
> ----

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +如果你从文件系统中加载schema并且使用其引用时，**必须提供正确的pointer**，
```suggestion
如果你从文件系统中加载schema并且使用其引用时， **必须提供正确的pointer** ，
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +一个schema可以有两种状态：
原文是“状态”，但结合下文看起来像是“模式”更合适？  
确认一下，如果要改的话，下面好几个地方都要一起改。

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +在下面的例子中，我自定义一个关键词，这个关键词需要校验json对象中的属性数值是否符合给定的多个预设值。
```suggestion
在下面的例子中，我们自定义一个关键词，这个关键词需要校验json对象中的属性数值是否符合给定的多个预设值。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-json-schema/java/index.adoc
> +首先，通过静态导入 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Schemas.html[Schemas]` 和 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Keywords.html[Keywords]` 。
```suggestion
首先，通过静态导入（import static） `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Schemas.html[Schemas]` 和 `link:../../apidocs/io/vertx/json/schema/draft7/dsl/Keywords.html[Keywords]` 。
```

2021-02-26 02:38 UTC, Leibnizhu commented on docs/translation/vertx-mqtt/java/index.adoc
> +如果你想要通过 WebSockets 来进行连接，可以通过 `link:../../apidocs/io/vertx/mqtt/MqttServerOptions.html[MqttServerOptions]` 来启用它，
```suggestion
如果你想要通过 WebSocket 来进行连接，可以通过 `link:../../apidocs/io/vertx/mqtt/MqttServerOptions.html[MqttServerOptions]` 来启用它，
```

2021-02-27 03:27 UTC, chengenzhao commented on docs/translation/vertx-json-schema/java/index.adoc
> +一个schema可以有两种状态：
这个倒不用改，跟原文保持一致即可
模式的话，是pattern
state就字面翻译成状态

2021-02-27 03:44 UTC, chengenzhao approved these changes

2021-02-27 10:57 UTC, merged