完成#23 vertx-core-polyglot的翻译
vertx-china/vertx-china.github.io pull request #124
Opened 2021-02-27 14:12 UTC by Hochikong

完成vertx-core-polyglot groovy的翻译
#23

2021-02-28 03:24 UTC, chengenzhao requested changes

2021-02-28 03:24 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +=== 编写 Verticles
需要添加tag，就像这样
```suggestion
[[_writing_verticles]]
=== 编写 Verticles
```
流程可以看一下
https://github.com/vertx-china/vertx-web-site/blob/master/README.zh-CN.md

2021-02-28 03:24 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +在部署时，默认的，Vert.x将会执行该脚本。此外，你的脚本中也可以提供 `startVertx` 和 `stopVertx` 方法。相应地，这些方法将会在verticle启动或者关闭时被调用：
你统一替换成您
```suggestion
在部署时，默认的，Vert.x将会执行该脚本。此外您的脚本中也可以提供 `startVertx` 和 `stopVertx` 方法。相应地，这些方法将会在verticle启动或者关闭时被调用：
```

2021-02-28 06:26 UTC, chengenzhao requested changes

2021-02-28 06:26 UTC, chengenzhao commented on docs/metadata/4.0.2.jsx
> +  name: "Vert.x 版 Groovy",
```suggestion
  name: "Groovy 版 Vert.x",
```

2021-02-28 10:53 UTC, chengenzhao requested changes

2021-02-28 10:53 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +=== 从verticle中访问vertx实例
```suggestion
[[_accessing_the_vertx_instance_from_a_verticle]]
=== 从verticle中访问vertx实例
```

所有的标题都要加上英文的tag

2021-02-28 10:53 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +=== Verticle的异步启动与关闭
```suggestion
[[_asynchronous_verticle_start_and_stop]]
=== Verticle的异步启动与关闭
```

2021-02-28 10:53 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +注意: 在verticle的stop方法中，您并不需要手动反部署子verticle。Vert.x将会在父verticle被反部署时自动反部署它的所有子verticle。
```suggestion
NOTE: 在verticle的stop方法中，您并不需要手动反部署子verticle。Vert.x将会在父verticle被反部署时自动反部署它的所有子verticle。
```

NOTE:
[[NOTE]]
等大写的标签不用翻译，web系统会统一修改

2021-02-28 10:56 UTC, chengenzhao requested changes

2021-02-28 10:56 UTC, chengenzhao commented on docs/translation/vertx-core/groovy/index.adoc
> +此外您也可以重写verticle的 `stop` 方法，在verticle被反部署时该方法将会被Vert.x所调用，
```suggestion
此外您也可以重写verticle的 `stop` 方法，在verticle被卸载时该方法将会被Vert.x所调用，
```

2021-02-28 13:46 UTC, chengenzhao approved these changes

2021-03-01 02:33 UTC, okou19900722 approved these changes

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +* Maven (在 `pom.xml` 文件中):
```suggestion
* Maven （在 `pom.xml` 文件中）：
```

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +* Gradle (在 `build.gradle` 文件中):
```suggestion
* Gradle （在 `build.gradle` 文件中）：
```

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +在Groovy中有两种方式可以用于创建Verticles:
```suggestion
在Groovy中有两种方式可以用于创建Verticles：
```

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +例如下面的代码片段，是一个有效的Groovy verticle:
```suggestion
例如下面的代码片段，是一个有效的Groovy verticle：
```

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +在部署时，配置信息可以以Map的形式传入verticle:
```suggestion
在部署时，配置信息可以以Map的形式传入verticle：
```

2021-03-01 02:33 UTC, okou19900722 commented on docs/translation/vertx-core/groovy/index.adoc
> +也可以通过"<<"操作符实现：
```suggestion
也可以通过“<<”操作符实现：
```

2021-03-01 02:34 UTC, merged