translation of vertx unit
vertx-china/vertx-china.github.io pull request #132
Opened 2021-03-19 03:46 UTC by fofofofoxier

#61

2021-03-22 11:58 UTC, okou19900722 requested changes

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +[[_introduction]]
锚点加错位置了

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +* Maven (在您的 `pom.xml` 文件):
```suggestion
* Maven （在您的 `pom.xml` 文件）：
```

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +* Gradle (在您的 `build.gradle` 文件):
```suggestion
* Gradle （在您的 `build.gradle` 文件）：
```

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +测试套件会在控制台报告每一步的结果：
多了一行

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +[[_asserting]]
锚点位置错了

2021-03-22 11:58 UTC, okou19900722 commented on docs/translation/vertx-unit/java/index.adoc
> +=== 使用第三方断言框架
锚点位置错误

2021-03-22 12:56 UTC, okou19900722 requested changes
还有几个锚点加到标题下面了

2021-03-25 01:16 UTC, fofofofoxier commented on docs/translation/vertx-unit/java/index.adoc
> +[[_introduction]]
已修复

2021-03-25 01:16 UTC, fofofofoxier commented on docs/translation/vertx-unit/java/index.adoc
> +测试套件会在控制台报告每一步的结果：
已修复

2021-03-25 01:16 UTC, fofofofoxier commented on docs/translation/vertx-unit/java/index.adoc
> +=== 使用第三方断言框架
已修复

2021-03-25 01:17 UTC, fofofofoxier commented
> 还有几个锚点加到标题下面了

锚点均已修复

2021-03-25 01:32 UTC, okou19900722 approved these changes

2021-03-25 02:01 UTC, chengenzhao requested changes

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +在运行套件之前，他们可以声明于任何位置，
```suggestion
然而在运行套件之前，他们可以在任何位置声明，
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +在用例之后声明 _after_ ，然而，
```suggestion
在用例之后声明 _after_ ，
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +用以在每一个测试用例前后执行：
```suggestion
在每一个测试用例前后执行：
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
>  === assertTrue and assertFalse
```suggestion
[[_asserttrue_and_assertfalse]]
=== 断言成功以及断言失败
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +最后（并非不重要），_test_ 提供了一个 _fail_ 方法用来抛出断言错误的异常：
```suggestion
最后但并非最不重要的，_test_ 提供了一个 _fail_ 方法用来抛出断言错误的异常：
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +`失败` 对象本身既可以是 _string_ 也可以是一个 _error_。
```suggestion
`失败` 对象本身既可以是 _string_ 也可以是一个 _error_ 。
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +使用我们提供的 _Handler_ 来进行断言。
```suggestion
使用我们提供的 _处理器（Handler）_ 来执行断言。
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +WARNING: 这个方法不应该从event loop上执行！
```suggestion
WARNING: 该方法不应该在事件循环（event loop）上执行！
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
>  === Event loop
```suggestion
=== 事件循环（Event loop）
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +.Event loop 用处
```suggestion
.事件循环（Event loop）的使用
```

2021-03-25 02:01 UTC, chengenzhao commented on docs/translation/vertx-unit/java/index.adoc
> +配置了event loop的用处：
```suggestion
以配置事件循环（event loop）的使用方式：
```

2021-03-25 02:02 UTC, chengenzhao approved these changes

2021-03-25 02:02 UTC, merged