translation for cassandra client
vertx-china/vertx-china.github.io pull request #134
Opened 2021-03-24 08:06 UTC by fofofofoxier

fix #18

2021-03-24 10:12 UTC, okou19900722 requested changes

2021-03-24 10:12 UTC, okou19900722 commented on docs/translation/vertx-cassandra-client/java/index.adoc
> +//= Cassandra Client for Vert.x
多余的

2021-03-25 01:29 UTC, fofofofoxier commented on docs/translation/vertx-cassandra-client/java/index.adoc
> +//= Cassandra Client for Vert.x
已删

2021-03-25 01:33 UTC, okou19900722 approved these changes

2021-03-25 05:22 UTC, chengenzhao requested changes

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
> +WARNING: 这个模块有 _技术预览_ 状态，这说明API在不同版本之间会有变化。
```suggestion
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
> +WARNING: 这个模块有 _技术预览_ 状态，这说明API在不同版本之间会有变化。
这个应该已经删除了tech preview的标签，我等下提交一个pr给官方

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
>  ==== Bulk fetching
```suggestion
[[_bulk_fetching]]
==== 获取 Bulk 
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
> +CAUTION: 只能在内存足以容纳整个数据块时使用 bulk fetching。
```suggestion
CAUTION: 只能在内存足以容纳整个数据块时获取 bulk 。
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
>  ==== Low level fetch
```suggestion
[[_low_level_fetch]]
==== 低级别获取
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/index.adoc
>  === Prepared queries
```suggestion
[[_prepared_queries]]
=== 已准备好的查询
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/override.adoc
>  ==== Bulk fetching
```suggestion
[[_bulk_fetching]]
==== 获取 Bulk
```

2021-03-25 05:22 UTC, chengenzhao commented on docs/translation/vertx-cassandra-client/java/override/rxjava2.adoc
>  ==== Bulk fetching
```suggestion
[[_bulk_fetching]]
==== 获取 Bulk
```

2021-03-25 07:12 UTC, fofofofoxier commented on docs/translation/vertx-cassandra-client/java/index.adoc
>  === Prepared queries
此处感觉保留原文好一点 PreparedStatement本身就是专有名词。

2021-03-25 12:52 UTC, chengenzhao approved these changes

2021-03-25 12:53 UTC, merged