translation for vertx-junit5
vertx-china/vertx-china.github.io pull request #135
Opened 2021-03-25 07:04 UTC by fofofofoxier

fix #35

2021-03-25 08:03 UTC, okou19900722 approved these changes

2021-03-25 12:57 UTC, chengenzhao commented
鸡鸡把metadata里面的那一句话也给翻译了叭

2021-03-26 01:44 UTC, fofofofoxier commented
> 鸡鸡把metadata里面的那一句话也给翻译了叭

已更新

2021-03-26 02:57 UTC, chengenzhao requested changes

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +测试异步操作需要的工具相比于Junit提供的工具，要求更多。
```suggestion
测试异步操作需要比JUnit之类的测试工具更多的工具。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +对该模块有首要贡献的是 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 对象：
```suggestion
首先对该模块有贡献的是 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 对象：
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +一下是一个很基础的用法：
```suggestion
这是一个很基础的用法：
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +* `link:../../apidocs/io/vertx/junit5/VertxTestContext.html#verify-io.vertx.junit5.VertxTestContext.ExecutionBlock-[verify]` 用来提供断言功能，代码块中抛出的任何异常都被认为测试用例失败。
```suggestion
* `link:../../apidocs/io/vertx/junit5/VertxTestContext.html#verify-io.vertx.junit5.VertxTestContext.ExecutionBlock-[verify]` 提供断言功能，代码块中抛出的任何异常都被认为测试用例失败。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +您可以用 checkpoint 来将某些执行点标记为通过。
```suggestion
您可以用 checkpoint 以标记某些执行点为通过。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +当所有的checkpoint被标记后， `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 将使测试用例通过。
```suggestion
当所有的checkpoint被标记后， `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 将通过测试用例。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +NOTE: `Vertx` 实例默认配置下不是集群模式。如果您需要做一些其他事情，那么请不要使用注入的 `Vertx` 参数，您需要自己提供 `Vertx` 对象。
```suggestion
NOTE: `Vertx` 实例默认配置下并非集群模式。如果您需要做一些其他事情，那么请不要使用注入的 `Vertx` 参数，需要您自己提供 `Vertx` 对象。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +测试用例会被自动的包装到 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 生命周期，所以您不需要自己注入 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html#awaitCompletion-long-java.util.conc
```suggestion
测试用例会被自动的包装到 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html[VertxTestContext]` 生命周期，所以您无需自行注入 `link:../../apidocs/io/vertx/junit5/VertxTestContext.html#awaitCompletion-long-java.util.concurrent.TimeUnit-[awaitCompletion]` ：
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +==== `VertxTestContext` 的作用范围
```suggestion
==== `VertxTestContext` 对象的作用范围
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +然而，任何情况下，我们都建议： `Vertx` 作为第一个参数，并且之后的参数按照您人工创建的顺序去声明。
```suggestion
然而，任何情况下，我们都建议：将 `Vertx` 作为第一个参数，并按照您创建的顺序去声明后续参数。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +您可以结合vertx-junit5，用 `@MethodSource` 来做参数化测试。
```suggestion
您可以结合vertx-junit5，用 `@MethodSource` 做参数化测试。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +因此，您需要在方法定义处的vertx测试参数之前，来声明 method source 参数。
```suggestion
因此，您需要在方法定义的vertx测试参数之前声明 method source 参数。
```

2021-03-26 02:57 UTC, chengenzhao commented on docs/translation/vertx-junit5/java/index.adoc
> +这对于其他 `ArgumentSources` 同样适用。详见 https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/ParameterizedTest.html[ParameterizedTest] 文档的 `Formal Parameter List` 一节。
```suggestion
这同样适用于其它 `ArgumentSources` 。详见 https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/ParameterizedTest.html[ParameterizedTest] 文档的 `Formal Parameter List` 一节。
```

2021-03-26 08:47 UTC, fofofofoxier commented on docs/translation/vertx-junit5/java/index.adoc
> +这对于其他 `ArgumentSources` 同样适用。详见 https://junit.org/junit5/docs/current/api/org.junit.jupiter.params/org/junit/jupiter/params/ParameterizedTest.html[ParameterizedTest] 文档的 `Formal Parameter List` 一节。
已改正

2021-03-26 14:21 UTC, chengenzhao approved these changes

2021-03-26 14:21 UTC, merged