vertx-web翻译
vertx-china/vertx-china.github.io pull request #142
Opened 2021-04-28 08:42 UTC by dreamlikeoceanlmy

2021-04-28 22:55 UTC, chengenzhao requested changes
大改动没有，主要就是格式调整一下
添加标题的锚点，以及尽量保持原文和翻译之后的行数一致

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 路由顺序
```suggestion
[[_route_order]]
== 路由顺序
```

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +你可以使用 `link:../../apidocs/io/vertx/ext/web/Route.html#order-int-[order]`
```suggestion
你可以使用 `link:../../apidocs/io/vertx/ext/web/Route.html#order-int-[order]` 指定一个整数类型的值
```

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +指定一个整数类型的值
```suggestion
```

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +你可以使用 `link:../../apidocs/io/vertx/ext/web/Route.html#order-int-[order]`
跟原文档的行数保持一致，这样等升级时候，就可以自动检查到原文档哪些地方有改动

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 基于请求MIME类型的路由
```suggestion
[[_routing_based_on_mime_type_of_request]]
== 基于请求MIME类型的路由
```

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
```suggestion
```

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
多了一行

2021-04-28 22:55 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 基于VirtualHost的路由
```suggestion
[[_routing_based_on_virtualhost]]
== 基于VirtualHost的路由
```

2021-04-28 23:11 UTC, chengenzhao requested changes

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 基于客户端可接收的MIME类型的路由
```suggestion
[[_routing_based_on_mime_types_acceptable_by_the_client]]
== 基于客户端可接收的MIME类型的路由
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 组合多个路由条件
```suggestion
[[_combining_routing_criteria]]
== 组合多个路由条件
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 启用或者关闭Route
```suggestion
[[_enabling_and_disabling_routes]]
== 启用或者关闭Route
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 对Forward的支持
```suggestion
[[_forward_support]]
== 对Forward的支持
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 上下文数据
```suggestion
[[_context_data]]
== 上下文数据
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 帮手函数
```suggestion
[[_helper_functions]]
== 帮手函数
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +//referrer url或 "/"如果没有referrer。
```suggestion
//referrer url或 "/"如果没有referrer。

```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 重新路由
```suggestion
[[_reroute]]
== 重新路由
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 子路由器
```suggestion
[[_sub_routers]]
== 子路由器
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 本地化
```suggestion
[[_localization]]
== 本地化
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 路由匹配失败
```suggestion
[[_route_match_failures]]
== 路由匹配失败
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 错误处理
```suggestion
[[_error_handling]]
== 错误处理
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 请求体处理
```suggestion
[[_request_body_handling]]
== 请求体处理
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 获取请求体
```suggestion
[[_getting_the_request_body]]
=== 获取请求体
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 限制请求体大小
```suggestion
[[_limiting_body_size]]
=== 限制请求体大小
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 合并表单属性
```suggestion
[[_merging_form_attributes]]
=== 合并表单属性
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 处理文件上传
```suggestion
[[_handling_file_uploads]]
=== 处理文件上传
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 操作 cookies
```suggestion
[[_handling_cookies]]
=== 操作 cookies
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 处理session
```suggestion
[[_handling_sessions]]
== 处理session
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== session储存
```suggestion
[[_session_stores]]
=== session储存
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +==== 本地session储存
```suggestion
[[_local_session_store]]
==== 本地session储存
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +==== 集群session储存器
```suggestion
[[_clustered_session_store]]
==== 集群session储存器
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +==== 其他储存方式
```suggestion
[[_other_stores]]
==== 其他储存方式
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 创建session处理器
```suggestion
[[_creating_the_session_handler]]
=== 创建session处理器
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 使用session
```suggestion
[[_using_the_session]]
=== 使用 session
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== session超时
```suggestion
[[_session_timeout]]
=== session 超时
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 认证/授权
```suggestion
[[_authentication_authorization]]
== 认证 / 授权
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 创建一个身份认证处理器
```suggestion
[[_creating_an_authentication_handler]]
=== 创建一个身份认证处理器
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 在你的程序中处理身份认证
```suggestion
[[_handling_authentication_in_your_application]]
=== 在你的程序中处理身份认证
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +使用basic authentication时，如果用户请求需要身份认证的资源，则basic auth处理器将发送带有标头 `WWW-Authenticate` 的 `401` 响应。
```suggestion
使用basic authentication时，如果用户请求需要身份认证的资源，
则basic auth处理器将发送带有标头 `WWW-Authenticate` 的 `401` 响应。
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +这会提示浏览器显示登录对话框，并提示用户输入用户名和密码。
```suggestion
这会提示浏览器显示登录对话框，
并提示用户输入用户名和密码。
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +用户会再次向资源发出请求，这次设置了 `Authorization` 标头，其中包含以Base64编码的用户名和密码。
```suggestion
用户会再次向资源发出请求，这次设置了 `Authorization` 标头，
其中包含以Base64编码的用户名和密码。
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +当basic auth处理器收到这个信息时，它会用用户名和密码调用配置好的 `link:../../apidocs/io/vertx/ext/auth/authentication/AuthenticationProvider.html[AuthenticationProvider]` 来认证用户。
```suggestion
当basic auth处理器收到该信息后，
它会使用配置好用户名和密码的 `link:../../apidocs/io/vertx/ext/auth/authentication/AuthenticationProvider.html[AuthenticationProvider]` 以认证用户。
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +如果身份认证成功，则允许请求路由继续到应用程序处理器，否则返回 `403` 响应以表示拒绝访问。
```suggestion
如果身份认证成功，则允许请求路由继续到应用程序处理器，
否则返回 `403` 响应拒绝访问。
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 重定向身份认证
```suggestion
[[_redirect_authentication_handler]]
=== 重定向身份认证
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== JWT 认证
```suggestion
[[_jwt_authentication]]
=== JWT 认证
```

2021-04-28 23:11 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 配置授权
```suggestion
[[_configuring_authorization]]
=== 配置授权
```

2021-04-28 23:32 UTC, chengenzhao requested changes

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 链接多个身份验证处理器
```suggestion
[[_chaining_multiple_authentication_handlers]]
=== 链接多个身份验证处理器
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 处理静态资源
```suggestion
[[_serving_static_resources]]
== 处理静态资源
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 配置缓存
```suggestion
[[_configuring_caching]]
=== 配置缓存
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 配置主页
```suggestion
[[_configuring_the_index_page]]
=== 配置主页
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 更改web root
```suggestion
[[_changing_the_web_root]]
=== 更改web root
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 处理隐藏文件
```suggestion
[[_serving_hidden_files]]
=== 处理隐藏文件
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 目录列表
```suggestion
[[_directory_listing]]
=== 目录列表
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 关闭在磁盘上的文件缓存
```suggestion
[[_disabling_file_caching_on_disk]]
=== 关闭在磁盘上的文件缓存
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 跨域处理
```suggestion
[[_cors_handling]]
== 跨域处理
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== 多租户
```suggestion
[[_multi_tenant]]
== 多租户
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 处理事件总线桥事件
```suggestion
[[_handling_event_bus_bridge_events]]
=== 处理事件总线桥事件
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== CSRF跨站请求伪造
```suggestion
[[_csrf_cross_site_request_forgery]]
== CSRF跨站请求伪造
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 使用 AJAX
```suggestion
[[_using_ajax]]
=== 使用 AJAX
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== HSTS处理器
```suggestion
[[_hsts_handler]]
== HSTS 处理器
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== CSP处理器
```suggestion
[[_csp_handler]]
== CSP处理器
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +== XFrame处理器
```suggestion
[[_xframe_handler]]
== XFrame处理器
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 一个真实世界的例子
```suggestion
[[_a_real_world_example]]
=== 一个真实世界的例子
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 将OAuth2和JWT混合使用
```suggestion
[[_mixing_oauth2_and_jwt]]
=== 将OAuth2和JWT混合使用
```

2021-04-28 23:32 UTC, chengenzhao commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +=== 处理HTTP请求方法覆盖
```suggestion
[[_handling_http_method_overriding]]
=== 处理HTTP请求方法覆盖
```

2021-04-28 23:44 UTC, chengenzhao requested changes

2021-04-28 23:44 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +
```suggestion
```

2021-04-28 23:44 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +
```suggestion
```

2021-04-28 23:44 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +Vert.x Web 的大部分特性是使用Handler实现的， 而且您随时可以实现您自己的处理器。我们预计随着时间的推移会有更多的处理器被实现。
```suggestion
Vert.x Web 的大部分特性是使用Handler实现的， 而且您随时可以实现您自己的处理器。
我们预计随着时间的推移会有更多的处理器被实现。
```

2021-04-28 23:44 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> + <version>4.0.2</version>
```suggestion
 <version>4.0.3</version>
```

2021-04-28 23:44 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> + compile 'io.vertx:vertx-web:4.0.2'
```suggestion
 compile 'io.vertx:vertx-web:4.0.3'
```

2021-04-29 00:23 UTC, chengenzhao requested changes
添加4.0.3当前版本的一些内容

2021-04-29 00:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // 但不包括:
```suggestion
  // 但同时：
```

2021-04-29 00:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // `/some/path` 这个路径被限制因为以斜线结尾
```suggestion
  // `/some/path` 最终的斜杆总是可选的并配有通配符，
  // 以保持与许多客户端库的兼容性。
  // 但 **不包括**：
  // `/some/patha`
  // `/some/patha/`

2021-04-29 00:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // `/some/bath`
// 等等……```

2021-04-29 00:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +占位符由 `:` 和参数名构成. 参数名由字母， 数字和下划线构成。
```suggestion
占位符由 `:` 和参数名构成. 参数名由字母， 数字和下划线构成。
在某些情况下，这会受到一定限制，因而用户可以切换至包括2个额外字符“-”和“ $”的扩展名称规则。
扩展参数规则可用如下系统属性启用：

----
-Dio.vertx.web.route.param.extended-pattern=true
----
```

2021-04-29 00:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
参数并不一定是路径段。例如，以下路径参数同样有效：

[source,java]
----
router
  .route(HttpMethod.GET, "/flights/:from-:to")
  .handler(ctx -> {
    // 在处理发送至/flights/AMS-SFO的请求时，将会设置：
    String from = ctx.pathParam("from"); // AMS
    String to = ctx.pathParam("to"); // SFO
    // 记住一点，如果不切换至参数命名的 “extend/扩展” 模式，
    // 这将不会起作用。
    // 因为在那种情况下，“-” 符号并不被认为是分隔符，
    // 而是参数名的一部分。
  });

2021-04-29 00:34 UTC, chengenzhao requested changes

2021-04-29 00:34 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // `/some/bath`
```suggestion
  // 等等……
```

2021-04-29 00:34 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +Vert.x-Web is a great fit for writing RESTful HTTP micro-services, but we don’t force you to write apps like that。
```suggestion
```

2021-04-29 00:34 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
```suggestion

参数并不一定是路径段。例如，以下路径参数同样有效：

[source,java]
----
router
  .route(HttpMethod.GET, "/flights/:from-:to")
  .handler(ctx -> {
    // 在处理发送至/flights/AMS-SFO的请求时，将会设置：
    String from = ctx.pathParam("from"); // AMS
    String to = ctx.pathParam("to"); // SFO
    // 记住一点，如果不切换至参数命名的 “extend/扩展” 模式，
    // 这将不会起作用。
    // 因为在那种情况下，“-” 符号并不被认为是分隔符，
    // 而是参数名的一部分。
});
----

2021-04-29 00:37 UTC, chengenzhao requested changes

2021-04-29 00:37 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +如果您的应用程序需要自定义 HTTP 动词，例如，在一个 `WebDAV` 服务器中，
```suggestion
如果您的应用程序需要自定义 HTTP 动词，例如，基于Web的分布式编写和版本控制（WebDAV）` 服务器中，
```

2021-04-29 00:37 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +== 路由顺序
```suggestion
[[_route_order]]
== 路由顺序
```

2021-04-29 00:42 UTC, chengenzhao requested changes

2021-04-29 00:42 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
>  In this case the route will match with any request with an `accept` header that matches `application/json`.
```suggestion
```

2021-04-29 00:42 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +
```suggestion
```

2021-04-29 01:30 UTC, chengenzhao requested changes

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // 做GET操作
```suggestion
  // 做 GET 相关操作……
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // 做POST操作
```suggestion
  // 做 POST 相关操作……
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // 做GET的操作
```suggestion
  // 做 GET 相关操作……
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +  // 做POST操作
```suggestion
  // 做 POST 相关操作……
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +许多公司和其他服务都限制了它们允许外部使用的REST HTTP方法。
```suggestion
许多公司和其他服务都限制了它们允许外部使用的REST HTTP方法。有些不太严密的可以允许使用任意的方法，大多数仅允许一个很小但不错的集合，有些则只允许GET和POST。造成这种限制的原因各不相同：浏览器或客户端限制或非常严格的公司防火墙。仅具有GET和POST的Web服务不能很好地表达REST的思想。PUT，DELETE，OPTIONS等对于指定对资源执行的操作非常有用。为了解决这个问题，它创建了X-HTTP-METHOD-OVERRIDE HTTP标头作为解决方法。
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +有些不太严密的可以允许使用任意的方法，大多数仅允许一个很小但不错的集合，有些则只允许GET和POST。
```suggestion
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +造成这种限制的原因各不相同：浏览器或客户端限制或非常严格的公司防火墙。仅具有GET和POST的Web服务不能很好地表达REST的思想。
```suggestion
```

2021-04-29 01:30 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +PUT，DELETE，OPTIONS等对于指定对资源执行的操作非常有用。为了解决这个问题，它创建了X-HTTP-METHOD-OVERRIDE HTTP标头作为解决方法。
```suggestion
```

2021-04-29 02:43 UTC, okou19900722 approved these changes

2021-04-29 02:58 UTC, chengenzhao approved these changes

2021-04-29 02:59 UTC, merged

2021-04-29 03:54 UTC, fofofofoxier requested changes

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +如果两个匹配的Route都具有相同的order值，则按照他们添加的属性被调用
```suggestion
如果两个匹配的Route都具有相同的order值，则按照他们添加的顺序被调用
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +客户端将接受 `text/plain` 或 `text/html` ，但更喜欢 `text/html` ，因为它有一个更高的`q` 值(默认q=1.0)：
```suggestion
客户端将接受 `text/plain` 或 `text/html` ，但因为 `text/html` 有一个更高的`q` 值(默认q=1.0)，所以客户端会优先接收 `text/html` ，：
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
>  In this case the route will match with any request with an `accept` header that matches `application/json`.
这行忘记删掉了

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> + 举个例子 `*.vertx.io` 或完全域名为 `www.vertx.io` 。
```suggestion
 举个例子 `*.vertx.io` 或像 `www.vertx.io` 的完整域名。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +你的应用可能位于一个代理服务器之后,比如 `HAProxy`。在此设置下工作时，获取客户端连接细节将不能正确返回预期结果
```suggestion
您的应用可能由Proxy服务器所代理，比如 `HAProxy`。在此设置下工作时，获取客户端连接细节将不能正确返回预期结果
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +//将被考虑，但是来自"Forward"的值优先
```suggestion
//将被解析，但是来自"Forward"的值优先
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +提供一个"附件"，附件是一种响应，它将触发浏览器打开配置为处理特定MIME类型的操作系统应用程序。
```suggestion
提供一个“附件”，附件是一种响应，它将触发浏览器打开配置为处理特定MIME类型的操作系统应用程序。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +//对于目标为”back"有一个特殊的处理。
```suggestion
//对于目标为”back“有一个特殊的处理。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +简单的content-type验证
```suggestion
常规的content-type校验
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +然后移至下一个handler，该处理程序将请求重新路由至 `/some/path/B”，从而终止请求。
```suggestion
然后移至下一个handler，该处理程序将请求重新路由至 `/some/path/B` ，从而终止请求。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +该方法还将静默丢弃并忽略路径中的任何html片段。
```suggestion
该方法还将静默地丢弃并忽略路径中的任何html片段。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +现在，我们可以将子路由器挂载在主路由器上，安装点在本例中为 `/productsAPI`。
```suggestion
现在，我们可以将子路由器挂载在主路由器上，挂载点在本例中为 `/productsAPI`。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 允许使用参数，但不能使用完整的正则表达式模式。
```suggestion
* 允许使用参数，但不能完全的使用正则表达式模式。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 在此调用之前或之后，只能注册1个处理程序（但它们可以在同一路径的新路由对象上注册
```suggestion
* 在此调用之前或之后，只能注册1个处理程序（但它们可以在同一路径的新路由对象上注册）
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 404 如果路径不能匹配
```suggestion
* 404 没有匹配的路径
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 405 如果路径匹配但是请求方法不匹配
```suggestion
* 405 路径匹配但是请求方法不匹配
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 406 如果路径匹配,请求方法匹配但是它无法提供内容类型与 `Accept` 请求头匹配的响应
```suggestion
* 406 路径匹配，请求方法匹配但是它无法提供内容类型与 `Accept` 请求头匹配的响应
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 415 如果路径匹配,请求方法匹配但是它不能接受 `Content-type`
```suggestion
* 415 路径匹配，请求方法匹配但是它不能接受 `Content-type`
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +* 400 如果路径匹配,请求方法匹配但是它接收空方法体
```suggestion
* 400 路径匹配，请求方法匹配但是它接收空方法体
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +Failure handler使用与普通处理程序完全相同的路由匹配条件
```suggestion
Failure handler与普通handler有完全相同的路由匹配条件
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +如果在运行与状态消息头中不允许字符的使用相关的错误处理器时发生错误，
```suggestion
如果在错误处理器执行时在状态消息头中出现非法字符，则发生错误，
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +为了启用在你的应用程序中session，
```suggestion
为了启用您应用程序中session，
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +你必须在应用程序逻辑之前的匹配路由上具有一个 `link:../../apidocs/io/vertx/ext/web/handler/SessionHandler.html[SessionHandler]`
```suggestion
您必须在应用程序逻辑之前的匹配路由上具有一个 `link:../../apidocs/io/vertx/ext/web/handler/SessionHandler.html[SessionHandler]`
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +但是请注意,因为这个机制，它并不保证这个数据在客户端收到相应之前完全保留
```suggestion
但是请注意,因为这个机制，它并不保证这个数据在客户端收到响应之前完全保留
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +在这例子中你可以强制刷新一下
```suggestion
在这个场景中你可以强制刷新一下
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +但是在无cookie session的情况下，session id是URL的一部分，而且这非常容易受到损害
```suggestion
但是在无cookie session的情况下，session id是URL的一部分，而且这非常容易受到攻击
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +通常情况下，PRNG使用混合模式，生成种子的时候会阻塞，生成时并不阻塞
```suggestion
默认情况下，PRNG使用混合模式，生成种子的时候会阻塞，生成时并不阻塞
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +因为你的请求可能会在不知道对应session的服务器上结束。
```suggestion
因为服务器可能会在不知道对应session的情况下，终结您的请求
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +**但是**所有会话数据都将通过Cookie发送回客户端，因此，如果您需要存储私有信息，则不应使用。
```suggestion
**但是** 所有会话数据都将通过Cookie发送回客户端，因此，如果您需要存储私有信息，则不应使用。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +可以在1个以上的源上执行查找，只需继续向处理程序中添加 `addAuthorizationProvider（provider` 即可。
```suggestion
可以在1个以上的源上执行查找，只需继续向处理程序中添加 `addAuthorizationProvider（ `provider` ） 即可。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +// 将http basic认证处理器添加到链中
```suggestion
// 将http basic认证处理器添加到处理器链路中
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +// 将表单重定向认证处理器添加到链中
```suggestion
// 将表单重定向认证处理器添加到处理器链路中
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +因此，当用户发出没有 `Authorization` 标头的请求时，这意味着该链将无法使用basic auth处理器进行身份验证，并将尝试使用重定向处理器进行身份证。
```suggestion
因此，当用户发出没有 `Authorization` 标头的请求时，这意味着该链将无法使用basic auth处理器进行身份验证，
并将尝试使用重定向处理器进行身份证。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +因此，如果你希望回退到浏览器中，使用HTTP Basic身份认证而不是重定向来询问用户凭据，那么您所需要做的就是反转加入到链的顺序
```suggestion
因此，如果你希望回退到浏览器中，使用HTTP Basic身份认证而不是重定向来询问用户凭据，
那么您所需要做的就是反转加入到处理器链路的顺序
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +在这种情况下，basic auth处理器将尝试进行身份认证，如果成功，链将停止，并且vertx-web将继续处理您的处理程序。
```suggestion
在这种情况下，basic auth处理器将尝试进行身份认证，如果成功，处理器链路将停止，并且vertx-web将继续处理您的处理程序。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +如果token无效，例如用户名密码错误，则链将继续至下面的节点。
```suggestion
如果token无效，例如用户名密码错误，则链路将继续执行至下面的节点。
```

2021-04-29 03:54 UTC, fofofofoxier commented on docs/translation/4.0.2/vertx-web/java/index.adoc
> +复杂的链也是可行的，举个例子，创建一个逻辑序列比如：`HandlerA` 或 (`HandlerB` 和 `HandlerC`)
```suggestion
复杂的处理器链路也是可行的，举个例子，创建一个逻辑序列比如：`HandlerA` 或 (`HandlerB` 和 `HandlerC`)
```