translation service proxy
vertx-china/vertx-china.github.io pull request #151
Opened 2021-05-10 02:54 UTC by PassXml

2021-05-14 02:09 UTC, chengenzhao requested changes

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* Gradle (在你的 `build.gradle` 文件):
你 统一替换成 您
```suggestion
* Gradle（在您的 `build.gradle` 文件）：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +JSON Web 令牌是一种简单的方法来发送明文信息（通常是URL），其内容可以被验证为是可信的。 像下面的这些场景JWT是非常适用的：
```suggestion
JSON Web 令牌是一种简单的发送明文信息（通常是URL）的方法，
其内容可被验证为是可信的。 
像下面的这些场景 JWT 是非常适用的：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 在单点登录方案中，需要一个单独的身份验证服务器，然后该服务器可以以受信任的方式发送用户信息.
```suggestion
* 在单点登录方案中，需要一个单独的身份验证服务器，
然后该服务器可以以被信任的方式发送用户信息。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 无状态的API 服务, 非常适合单页应用.
```suggestion
* 无状态的API 服务，非常适合单页应用。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +在决定使用JWT之前, 需要重点注意的是JWT并不加密payload, 沓子对它签名。 你 你不应该使用JWT发送任何私密信息, 相反你应该发送是不是私密的 但要被验证的信息。举个例子, 使用JWT发送一个签名过的用户id来表明这个用户已经登录了的做法非常对的!
```suggestion
在决定使用JWT之前, 需要重点注意的是JWT并不加密payload, 沓子对它签名。
您不应该使用JWT发送任何私密信息，相反应该发送的是非私密的，但要被验证的信息。
举个例子，使用JWT发送一个签名过的用户id来表明这个用户已经登录了的做法非常棒！
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +相反发送一个用户的密码的做法是非常非常错误的.
```suggestion
相反发送一个用户的密码的做法则是非常非常错误的。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +JWT主要的优点有:
```suggestion
JWT主要的优点有：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 它是无状态的.
```suggestion
* 它是无状态的。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +JWT用法的典型流程是，在您的应用程序有一个端点颁发令牌, 这个端点应在 SSL模式下运行, 端点这通过用户名和密码验证完请求用户之后，表示你将这样做生成 令牌:
```suggestion
JWT用法的典型流程是，在您的应用程序有一个端点颁发令牌，这个端点应在 SSL模式下运行，
端点在通过用户名和密码验证完请求用户之后，您应当如此做：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 使用 secrets (对称秘钥)
```suggestion
* 使用 secrets（对称秘钥）
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 使用 OpenSSL 生成的 `pem` 格式文件 (公钥)
```suggestion
* 使用 OpenSSL 生成的 `pem` 格式文件（公钥）
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 使用 Java Keystore 文件 (对称加密公钥)
```suggestion
* 使用 Java Keystore 文件（对称加密公钥）
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +JWT的默认签名方法称为 `HS256`。 `HS` 默认表示为 `HMAC 加密 使用 SHA256`.
```suggestion
JWT的默认签名方法称为 `HS256`。 `HS` 默认表示为 `HMAC 加密 使用 SHA256`。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +这是最简单的加载秘钥方式了. 你只需要将secret与第三方共享, 举个例子 假设 secret 是: `keyboard cat` 那么你可以将Auth配置为:
```suggestion
这便是最简单的加载秘钥方式。你只需要将 secret 与第三方共享，举个例子
假设 secret 是：`keyboard cat` 那么您可将 Auth 配置为：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +在这种情况下secret将被设置为公钥, 因为这是双方都知道的令牌，你可以配置 你的PubSec配置为对称。
```suggestion
在这种情况下secret将被设置为公钥，因为这是双方都知道的令牌，你可以配置 PubSec 密钥为对称的。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +这部分不是 OpenSSL 文档，建议阅读OpenSSL文档了解命令的使用。 我们将 介绍如何生成最通用的密钥以及如何和JWT auth一起使用。
```suggestion
这部分不是 OpenSSL 文档，建议阅读OpenSSL文档了解命令的使用。 
我们将介绍如何生成最通用的密钥以及如何与 JWT auth 一起使用。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +想象一下，你想使用非常常见的 `RS256` 加密算法来保护您的资源。 与你想象 相反, 256 不是秘钥长度而是哈希算法的签名长度.
```suggestion
想象一下，您想使用非常常见的 `RS256` 加密算法来保护您的资源。
与您想象的相反， 256 不是秘钥长度而是哈希算法的签名长度。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +任何RSA秘钥都和JWT 加密算法一期使用.
```suggestion
任何RSA秘钥都可以和JWT 加密算法一期使用。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +这里是信息表:
```suggestion
这是信息表：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +现在可以校验令牌有效性了:
```suggestion
现在可以校验令牌有效性了：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +你会看到类似内容的文件:
```suggestion
你会看到类似内容的文件：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +然后你会看到类似内容的文件了:
```suggestion
然后你会看到类似内容的文件了：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +现在是一个包含类似内容，全新的 `private_key.pem` 秘钥文件了；
```suggestion
现在类似原始文件的新文件 `private_key.pem` 里包含了：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +标准的JDK是无法读取的该文件的，所以我们 **必须** 将它转换成 PKCS8 标准的格式的:
```suggestion
标准的JDK是无法读取的该文件的，所以我们 **必须** 将其转换成 PKCS8 标准格式：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +但是JDK支持此PKCS8格式的，我们必须将它装换；
```suggestion
但是JDK更倾向于使用PKCS8格式，我们必须将其装换：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +然后会看到类似的内容的文件:
```suggestion
然后会看到类似的内容的文件：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +使用私钥你可以生成令牌了:
```suggestion
使用私钥您可生成令牌：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +为了验证令牌你还需要一个公钥：
```suggestion
为了验证令牌您还需要一个公钥：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +现在你可以用它进行全部操作了:
```suggestion
现在您可用它进行全部操作了：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果你喜欢用Java Keystores格式的秘钥文件, 那么下文可以做到这一点.
```suggestion
如果你更倾向于使用 Java Keystores 格式的秘钥文件，那么您也可如此做。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果未提供密钥库，则实现将退回到不安全模式，并且不会验证签名， 这对于通过外部手段对payload进行签名情况很有用。
```suggestion
如果未提供密钥库，则实现将退回到不安全模式，并且不会验证签名，
这对于通过外部手段对 payload 签名会很有用。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +给定别名将在所有的密钥算法中匹配最合适的。 例如 `RS256` 算法是不允许的，`EC` 算法或 `RSA` 算法是允许的，注意 `RSA` 具体为 `SHA1WithRSA` 而不是 `SHA256WithRSA`.
```suggestion
给定别名将在所有的密钥算法中匹配最合适的。 例如 `RS256` 算法是不允许的，`EC` 算法或 `RSA` 算法是允许的，注意 `RSA` 具体为 `SHA1WithRSA` 而不是 `SHA256WithRSA`。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +生成秘钥文件需要唯一的工具是 `keytool`, 您现在可以运行命令行并指定特定的 算法:
```suggestion
生成秘钥文件需要唯一的工具是 `keytool`，您通过以下方式指定算法：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果由第三方发布JWT令牌，而你有没有私钥， 在这种情况下你得公钥必须是PEM格式的。
```suggestion
如果由第三方发布JWT令牌，而您没有私钥，
在这种情况下你得公钥必须是PEM格式的。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +在这种情况下，可以使用HTTP作为使用该API的协议，并且HTTP协议已经定义了应该用于传递授权信息的标头 `Authorization` 。在大多数情况下令牌将以bearer tokens形式发送, 如： `Authorization: Bearer some+base64+string`.
```suggestion
在这种情况下，可以使用HTTP作为使用该API的协议，并且HTTP协议已经定义了应该用于传递授权信息的标头 `Authorization` 。
在大多数情况下令牌将以承载令牌（bearer tokens）的形式发送， 例如：`Authorization: Bearer some+base64+string`。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
>  === Authenticating (AuthN)
```suggestion
=== 鉴权/身份验证 (AuthN)
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +验证 issuer 字段:
```suggestion
验证 issuer 字段：
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
>  === Authorizing (AuthZ)
```suggestion
=== 授权 (AuthZ)
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +一旦令牌被解析并且有效，我们就可以使用它来执行授权任务。最简单的方法是验证用户是否具有特定权限。 最简单的是验证用户是否具有特定权限。 授权将遵循通用 `link:../../apidocs/io/vertx/ext/auth/authorization/AuthorizationProvider.html[AuthorizationProvider]`
```suggestion
一旦令牌被解析并且有效，我们就可以使用它来执行授权任务。最简单的方法是验证用户是否具有特定权限。 
最简单的是验证用户是否具有特定权限。 授权将遵循通用 `link:../../apidocs/io/vertx/ext/auth/authorization/AuthorizationProvider.html[AuthorizationProvider]`
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +API.
```suggestion
API。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +`JWTOptions` 对象.
```suggestion
这是一个 `JWTOptions` 对象。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +生成令牌时，可以提供一个可选的额外参数来控制令牌的生成，这是一个
```suggestion
生成令牌时，可以提供一个可选的额外参数来控制令牌的生成，
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +有时我们发行的令牌会没有时间戳（例如：在测试、开发过程中），在这种情况下 `noTimestamp` 属性应该被设置成ture (默认：false).
```suggestion
有时我们发行的令牌会没有时间戳（例如：在测试、开发过程中），在这种情况下 `noTimestamp` 属性应该被设置成ture (默认：false)。
```

2021-05-14 02:09 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +令牌的过期时间由 `expiresInSeconds` 属性控制，默认情况下不会过期。 然后可以配置其他控制字段 `audience`，`issuer` 以及 `subject` 并将其加入到令牌信息当中
```suggestion
令牌的过期时间由 `expiresInSeconds` 属性控制，默认情况下不会过期。
然后可以配置其他控制字段 `audience`，`issuer` 以及 `subject` 并将其加入到令牌元数据中。
```

2021-05-14 02:24 UTC, chengenzhao requested changes

2021-05-14 02:24 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +当您编写Vert.x程序的时候，您也许想将某处独立服务功能提供给其他程序使用。这时候可以使用服务代理了。 它可以让您在事件总线上公开您的 _服务_ , 因此，任何Vert.x程序只要知道其推送的 _地址_ 就可以消费使用它。
```suggestion
当您编写 Vert.x 程序的时候，您也许想将某处独立服务功能提供给其他程序使用。
此时便使用服务代理。 它可以让您在事件总线上发布您的 _服务_ ，任何Vert.x程序只要知道其 _地址_ 即可使用该服务。
```

2021-05-14 02:24 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +_服务_ 它是遵循Java接口定义，方法定义必须遵循 _异步规范_。更深层次下,
```suggestion
一个 _服务_ 通过 Java 接口描述并遵循 _异步_ 模式。从本质上说，
```

2021-05-14 02:29 UTC, chengenzhao requested changes

2021-05-14 02:29 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +在事件总线上发送请求消息并调用服务响应请求。 但是为了更简单使用,
```suggestion
从本质上说，消息通过事件总线发送调用服务并获取响应。
```

2021-05-14 02:29 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +他会成为一个 _代理_ 可以直接调用 (使用服务接口的API)。
```suggestion
但为了方便使用，它会生成一个 _代理_ ，您可直接使用该代理（用代理提供的服务接口API）。
```

2021-05-16 02:10 UTC, chengenzhao requested changes

2021-05-16 02:10 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* Maven (在你的 `pom.xml`):
```suggestion
* Maven（在您的 `pom.xml`）：
```

2021-05-16 02:23 UTC, chengenzhao requested changes

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 它可以让你验证令牌的真实性。
```suggestion
* 它允许您验证令牌的真实性。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +* 它有一个JSON结构，可以包含任何你想要的变量和大量的数据。
```suggestion
* 它有一个JSON结构，可以包含任何您所需的任意数量的数据。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +你可以使用 `link:../../apidocs/io/vertx/ext/auth/jwt/JWTAuth.html[JWTAuth]` 来创建一个验证器的实例。 并指定一个JSON对象的配置。
```suggestion
您可使用 `link:../../apidocs/io/vertx/ext/auth/jwt/JWTAuth.html[JWTAuth]` 创建一个验证器的实例。 并指定一个格式为 JSON 的配置文件。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +  // 现在，对于任何对受保护资源的请求，你应该
```suggestion
  // 现在，对于任何对受保护资源的请求，您应该
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +这便是最简单的加载秘钥方式。你只需要将 secret 与第三方共享，举个例子
```suggestion
这便是最简单的加载秘钥方式。您只需要将 secret 与第三方共享，举个例子
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +在这种情况下secret将被设置为公钥，因为这是双方都知道的令牌，你可以配置 PubSec 密钥为对称的。
```suggestion
在这种情况下secret将被设置为公钥，因为这是双方都知道的令牌，您可配置 PubSec 密钥为对称的。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果您想生成一个2048位RSA密钥对, 那么你应该(请记住 **不要** 添加密码， JWT auth将无法载入秘钥文件):
```suggestion
如果您想生成一个2048位RSA密钥对，那么您应该（请记住 **不要** 添加密码， JWT auth 将无法载入秘钥文件）：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果你看到类似的文件内容，那么恭喜你秘钥文件正确的生成了；
```suggestion
如您看到类似的文件内容，那么恭喜您，秘钥文件正确的生成了：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果你只验证令牌 (你只需要 private_key.pem 文件) 但是某些时候你需要 签发令牌, 所以你需要一个公钥。在这种情况下你需要从私钥文件中提取公钥文件:
```suggestion
如您只验证令牌（只需要 private_key.pem 文件）那么您需要签发令牌，故而您需要一个公钥。在这种情况下您需要从私钥文件中提取公钥文件：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +你会看到类似内容的文件：
```suggestion
您会见到类似以下内容的文件：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +用法和RSA加密算法极其相似, 首先你需要创建一个公钥：
```suggestion
用法和RSA加密算法极其相似，首先您需要创建一个公钥：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +然后你会看到类似内容的文件了：
```suggestion
然后您会看到类似以下内容的文件了：
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +如果你更倾向于使用 Java Keystores 格式的秘钥文件，那么您也可如此做。
```suggestion
如果您更倾向于使用 Java Keystores 格式的秘钥文件，那么您也可如此做。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +在这种情况下你得公钥必须是PEM格式的。
```suggestion
在这种情况下您的公钥必须是 PEM 格式的。
```

2021-05-16 02:23 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +通常情况下当你开发微服务的时候提供API服务。 这些API通常是提供给程序使用的，因此我们应该删除消费者中认证授权的部分。
```suggestion
通常在开发微服务时，您希望应用程序能够使用 API ​​。 
而这些 API 并不打算让普通人轻易看懂，
因而我们应该删除所有对 API 进行身份验证的交互部分的内容。
```

2021-05-16 02:25 UTC, chengenzhao requested changes

2021-05-16 02:25 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +// 验用户的用户名和密码之后，
```suggestion
// 验用户的用户名和密码之后
```

2021-05-16 02:25 UTC, chengenzhao commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +  // 检查他们的HTTP头中Authorization字符串:
```suggestion
  // 检查他们的HTTP头中Authorization字符串：
```

2021-05-16 02:30 UTC, chengenzhao requested changes

2021-05-16 02:30 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +* Maven (在 `pom.xml` 文件中)：
```suggestion
* Maven（在您的 `pom.xml` 文件中）：
```

2021-05-16 02:30 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +* Gradle (在 `build.gradle` file)：
```suggestion
* Gradle（在您的 `build.gradle` 文件中）：
```

2021-05-16 02:30 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +* Gradle版本小于 5 的情况(在 `build.gradle` 文件中)：
```suggestion
* Gradle < 5 （在您的 `build.gradle` 文件中）：
```

2021-05-16 02:30 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +* Gradle版本大于等于 5 (在 `build.gradle` 文件中)：
```suggestion
* Gradle >= 5（在您的 `build.gradle` 文件中）：
```

2021-05-16 02:30 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +* Maven (在 `pom.xml` 文件中)：
```suggestion
* Maven（在您的 `pom.xml` 文件中）：
```

2021-05-16 02:36 UTC, chengenzhao requested changes

2021-05-16 02:36 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> + // 几个工厂方法用于创建实例
```suggestion
 // 几个工厂方法用于创建实例和代理
```

2021-05-16 02:36 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +// 服务实际的接口订单
```suggestion
// 此处是实际的服务操作……
```

2021-05-16 02:36 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
> +则对应的处理器类命名为 `MyServiceProxyHandler`,对应的服务代理类命名为 MyServiceVertxEBProxy。
```suggestion
则对应的处理器类命名为 `MyServiceProxyHandler`，对应的服务代理类命名为 MyServiceVertxEBProxy。
```

2021-05-16 02:42 UTC, chengenzhao commented
@pigbayspy
有空帮忙看一下这两个翻译

2021-05-16 02:48 UTC, chengenzhao approved these changes

2021-05-16 02:48 UTC, chengenzhao commented on docs/translation/vertx-service-proxy/java/index.adoc
>  = Vert.x Service Proxy
```suggestion
= Vert.x 服务代理
```

2021-05-16 02:57 UTC, pigbayspy commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +  // 我们正在使用keycloak JWT
```suggestion
  // 因为我们正在使用 keycloak JWT 因此我们需要
```

2021-05-16 03:00 UTC, pigbayspy commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +因此，在此示例中，我们将JWT配置为使用Keycloak令牌格式。在这种情况下claims将会检查 `realm_access/roles`
```suggestion
所以在此示例中，我们将 JWT 配置为使用 Keycloak 令牌格式。在这种情况下 `realm_access/roles` 路径下的 claims 会被检查 
```

2021-05-16 03:01 UTC, pigbayspy commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +方法 `authenticate` 被调用，令牌将根据初始化期间 提供的 `JWTOptions` 进行验证。验证步骤如下:
```suggestion
方法 `authenticate` 被调用时，令牌将根据初始化期间提供的 `JWTOptions` 进行
验证。验证步骤如下:
```

2021-05-16 03:07 UTC, pigbayspy commented on docs/translation/vertx-auth-jwt/java/index.adoc
> +JSON Web 令牌是一种简单的发送明文信息（通常是URL）的方法，
```suggestion
JSON Web 令牌是一种简单的以明文（通常是URL）发送信息的方法，
```

2021-05-16 06:16 UTC, merged