vertx shell 翻译完成
vertx-china/vertx-china.github.io pull request #153
Opened 2021-05-10 06:00 UTC by Linindoo

文档翻译+锚点

2021-05-10 06:10 UTC, chengenzhao requested changes

2021-05-10 06:10 UTC, chengenzhao commented on docs/metadata/3.9.0.jsx
> +    description: "使用 CLI 接口与Vert.x应用程序交互。",
```suggestion
    description: "使用 CLI 接口与 Vert.x 应用程序互动。",
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +Vert.x Shell 是一个基于Vert.x支持不同协议的统一终端的命令行接口
```suggestion
Vert.x Shell 是一款基于Vert.x支持不同协议的统一终端的命令行接口。
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +Vert.x Shell 提供了一系列命令来与Vert.x服务进行实时交互
```suggestion
Vert.x Shell 提供了一系列命令来与 Vert.x 服务进行实时互动
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +vertx run -conf '{"telnetOptions":{"port":5000}}' maven:io.vertx:vertx-shell:4.0.2
```suggestion
vertx run -conf '{"telnetOptions":{"port":5000}}' maven:io.vertx:vertx-shell:4.0.3
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +vertx run -conf '{"sshOptions":{"port":4000,"keyPairOptions":{"path":"ssh.jks","password":"secret"},"authOptions":{"provider":"shiro","config":{"properties_path":"file:auth.properties"}}}}' maven:io.
```suggestion
vertx run -conf '{"sshOptions":{"port":4000,"keyPairOptions":{"path":"ssh.jks","password":"secret"},"authOptions":{"provider":"shiro","config":{"properties_path":"file:auth.properties"}}}}' maven:io.vertx:vertx-shell:4.0.3
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +vertx run -conf '{"httpOptions":{"port":8080,"ssl":true,"keyStoreOptions":{"path":"keystore.jks","password":"secret"},"authOptions":{"provider":""shiro,"config":{"properties_path":"file:auth.properti
```suggestion
vertx run -conf '{"httpOptions":{"port":8080,"ssl":true,"keyStoreOptions":{"path":"keystore.jks","password":"secret"},"authOptions":{"provider":""shiro,"config":{"properties_path":"file:auth.properties"}}}}' maven:io.vertx:vertx-shell:4.0.3
```

2021-05-10 06:10 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +NOTE: 当你的 classpath 中已经包含了Vert.x Shell ，你可以使用 `service:io.vertx.ext.shell` 来代替 `maven:io.vertx:vertx-shell:4.0.2`
```suggestion
NOTE: 当你的 classpath 中已经包含了Vert.x Shell ，你可以使用 `service:io.vertx.ext.shell` 来代替 `maven:io.vertx:vertx-shell:4.0.3`
```

2021-05-10 06:14 UTC, chengenzhao requested changes

2021-05-10 06:14 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +`link:../../apidocs/io/vertx/ext/shell/command/CommandProcess.html[CommandProcess]` 对象可以用来与 shell 进行交互。
```suggestion
`link:../../apidocs/io/vertx/ext/shell/command/CommandProcess.html[CommandProcess]` 对象可以用于与 shell 互动。
```

2021-05-10 06:14 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +命令不仅提供了 `link:../../apidocs/io/vertx/ext/shell/command/CommandProcess.html[process]` 与 shell 进行交互，
```suggestion
命令不仅提供了 `link:../../apidocs/io/vertx/ext/shell/command/CommandProcess.html[process]` 与 shell 互动，
```

2021-05-10 06:14 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +来与 terminal 进行交互。
```suggestion
来与 terminal 互动。
```

2021-05-10 06:14 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +当 shell 运行时， `link:../../apidocs/io/vertx/ext/shell/term/Pty.html[Pty]` 伪终端是与命令进行交互的主要手段：
```suggestion
当 shell 运行时， `link:../../apidocs/io/vertx/ext/shell/term/Pty.html[Pty]` 伪终端是与命令互动的主要手段：
```

2021-05-10 06:14 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +当一个远程终端进行连接时，`link:../../apidocs/io/vertx/ext/shell/term/Term.html[Term]` 可以用来与当前连接的终端进行交互。
```suggestion
当一个远程终端进行连接时，`link:../../apidocs/io/vertx/ext/shell/term/Term.html[Term]` 可以用来与当前连接的终端互动。
```

2021-05-10 07:33 UTC, okou19900722 approved these changes

2021-05-11 12:33 UTC, chengenzhao approved these changes

2021-05-11 12:33 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +`link:../../apidocs/io/vertx/ext/shell/term/Term.html[Term]` 可以用来与当前连接的终端进行交互。
```suggestion
`link:../../apidocs/io/vertx/ext/shell/term/Term.html[Term]` 可以用来与当前连接的终端互动。
```

2021-05-11 12:33 UTC, chengenzhao commented on docs/translation/vertx-shell/java/index.adoc
> +`link:../../apidocs/io/vertx/ext/shell/term/Pty.html[Pty]` 伪终端是与命令进行交互的主要手段：
```suggestion
`link:../../apidocs/io/vertx/ext/shell/term/Pty.html[Pty]` 伪终端是与命令互动的主要手段：
```

2021-05-11 12:34 UTC, merged