fix #16
vertx-china/vertx-china.github.io pull request #161
Opened 2021-05-14 15:14 UTC by fofofofoxier

fix #16

2021-05-14 22:30 UTC, chengenzhao requested changes

2021-05-14 22:30 UTC, chengenzhao commented on docs/metadata/4.0.0.jsx
> +    name: "Webauthn 授权",
```suggestion
    name: "Webauthn 鉴权与授权",
```

2021-05-14 22:30 UTC, chengenzhao commented on docs/translation/vertx-auth-webauthn/java/index.adoc
> +那么您需要在编译脚本中添加如下依赖：
```suggestion
您需要在编译脚本中添加如下依赖：
```

2021-05-15 02:07 UTC, okou19900722 approved these changes

2021-05-15 13:38 UTC, chengenzhao approved these changes

2021-05-16 01:19 UTC, merged