完成 【Vertx-Consul-Client】的翻译
vertx-china/vertx-china.github.io pull request #164
Opened 2021-05-22 04:37 UTC by pigbayspy

完成 https://github.com/vertx-china/vertx-web-site/issues/21 的翻译

2021-05-22 09:56 UTC, chengenzhao requested changes

2021-05-22 09:56 UTC, chengenzhao commented on docs/metadata/3.9.0.jsx
> +    description: "Consul 客户端",
```suggestion
    description: "Consul 客户端。",
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +Vert.x 的 Consul 客户端允许应用与 Consul 系统通过阻塞或非阻塞的 HTTP 接口交互。
```suggestion
Vert.x 的 Consul 客户端允许应用通过阻塞或非阻塞的 HTTP 接口与 Consul 系统互动。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +查询参数中携带 "?token" 参数。 如果没有提供，那么签名为空，会使用对应的 '匿名'
```suggestion
查询参数中携带 "?token" 参数。如没有提供，那么签名为空，会使用对应的 '匿名'
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +ACL 策略
```suggestion
ACL 策略。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +查询参数中携带 "?dc" 参数。 如果没有提供，那么会默认查询当前的 Consul agent 的数据中心
```suggestion
查询参数中携带 "?dc" 参数。 如果没有提供，那么会默认查询当前的 Consul agent 的数据中心。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`index`:: 该值用于表示 Consul 客户端期望看到的所请求资源的 index 的变化
```suggestion
`index`:: 该值用于表示 Consul 客户端期望看到的所请求资源的 index 的变化。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +以下是可以使用的接口
```suggestion
以下是可以使用的接口：
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +返回的键值对数据包括以下字段 (参见 https://www.consul.io/docs/agent/http/kv.html#single[文档]):
```suggestion
返回的键值对数据包括以下字段（参考 https://www.consul.io/docs/agent/http/kv.html#single[文档]）：
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`createIndex`:: 内部的创建索引，表示该键值对何时被创建的
```suggestion
`createIndex`:: 内部的创建索引，表示该键值对何时被创建的。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +以下是 `PUT` 请求可以接收的参数
```suggestion
以下是 `PUT` 请求可以接收的参数：
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`flags`:: 可以指定一个无符号数，范围是 `0` 到 `2^64^-1`
```suggestion
`flags`:: 可以指定一个无符号数，范围是 `0` 到 `2^64^-1` 。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +客户端可以选择使用标识位来表示应用业务中的一些信息
```suggestion
客户端可以选择使用标识位来表示应用业务中的一些信息。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +而不用再释放锁并重新获取
```suggestion
而不用再释放锁并重新获取。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +最后， Consul 允许你从存储中删除键值对
```suggestion
最后， Consul 允许你从存储中删除键值对：
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +不同的版本，或者服务的其他不同等级标记
```suggestion
不同的版本，或者服务的其他不同等级标记。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +在 10s 和 86400s 之间。 如果提供该设置，那么如果会话在 TTL 时间到期前仍没有刷新的话会失效
```suggestion
在 10s 和 86400s 之间。 如果提供该设置，那么如果会话在 TTL 时间到期前仍没有刷新的话会失效。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +健康检查列表中需要包含默认的 `serfHealth`
```suggestion
健康检查列表中需要包含默认的 `serfHealth`。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +所有读取会话的接口支持阻塞查询和全一致模式
```suggestion
所有读取会话的接口支持阻塞查询和全一致模式。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`token` :: 指定一个 ACL 签名，每次执行查询都会使用该签名。 预备查询在执行时可以没有 ACL 签名， 因此你需要谨慎使用。 签名本身只对管理签名的客户端可见。 如果签名没有设置或为空字符串，那么会使用客户端的 ACL 签名来决定是否有权限来查询对应服务。 如果客户端无法提供 ACL 签名， 那么会使用一个匿名签名
```suggestion
`token` :: 指定一个 ACL 签名，每次执行查询都会使用该签名。 预备查询在执行时可以没有 ACL 签名， 因此你需要谨慎使用。 签名本身只对管理签名的客户端可见。 如果签名没有设置或为空字符串，那么会使用客户端的 ACL 签名来决定是否有权限来查询对应服务。 如果客户端无法提供 ACL 签名， 那么会使用一个匿名签名。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`session` :: 指定一个现有会话的 ID，这样如果该会话过期后，对应的预备查询语句也会被删除，否则你需要手动删除不再使用的预备查询语句
```suggestion
`session` :: 指定一个现有会话的 ID，这样如果该会话过期后，对应的预备查询语句也会被删除，否则你需要手动删除不再使用的预备查询语句。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`name` :: 一个可选的昵称， 你可以使用该昵称而不是 ID 来指定要使用的预备查询
```suggestion
`name` :: 一个可选的昵称， 你可以使用该昵称而不是 ID 来指定要使用的预备查询。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`service` :: 指定要查询的服务名称，这个参数是必填的
```suggestion
`service` :: 指定要查询的服务名称，这个参数是必填的。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`failover` :: 该参数包括两个字段，都是可选的。 该参数用于指定执行查询时如果本地的数据中心没有处于健康状态下的服务时的行为。通过简单的配置你可以使用其他数据中心上的节点
```suggestion
`failover` :: 该参数包括两个字段，都是可选的。 该参数用于指定执行查询时如果本地的数据中心没有处于健康状态下的服务时的行为。通过简单的配置你可以使用其他数据中心上的节点。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`datacenters` :: 指定要转发的远程数据中心列表。 如果本地没有健康节点可用的话，会转发请求到这些数据中心上。 Consul 会按照列表中的顺序查询数据中心。 如果该选项与 NearestN 一起使用， 那么会首先依据 NearestN 设置的规则， 其次才是 Datacenters 配置的规则。 在失效转移请求的过程中一个数据中心只会使用一次， 即使它都满足 NearestN 和
```suggestion
`datacenters` :: 指定要转发的远程数据中心列表。 如果本地没有健康节点可用的话，会转发请求到这些数据中心上。 Consul 会按照列表中的顺序查询数据中心。 如果该选项与 NearestN 一起使用， 那么会首先依据 NearestN 设置的规则， 其次才是 Datacenters 配置的规则。 在失效转移请求的过程中一个数据中心只会使用一次， 即使它都满足 NearestN 和 Datacenters 配置的条件。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`onlyPassing` :: 指定该查询的健康检查状态的条件。 如果设置为 false， 那么即使服务处于警告状态也会返回。 如果设置为 true， 则只会返回健康检查成功的服务
```suggestion
`onlyPassing` :: 指定该查询的健康检查状态的条件。 如果设置为 false， 那么即使服务处于警告状态也会返回。 如果设置为 true， 则只会返回健康检查成功的服务。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`tags` :: 设置服务标签列表， 查询结果会根据参数列表过滤。 如果设置了该参数，那么只有服务拥有列表中所有的标签才会满足条件， 并且不包含禁止标签 (前缀带有 ! 的为禁止标签)
```suggestion
`tags` :: 设置服务标签列表， 查询结果会根据参数列表过滤。 如果设置了该参数，那么只有服务拥有列表中所有的标签才会满足条件， 并且不包含禁止标签（前缀带有 ! 的为禁止标签）。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`nodeMeta` :: 设置一个自定义的用户键值对列表，可以用于查询节点的元数据过滤返回结果
```suggestion
`nodeMeta` :: 设置一个自定义的用户键值对列表，可以用于查询节点的元数据过滤返回结果。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`dnsTtl` :: 如果查询结果是通过 DNS 服务的话，设置 TTL 的范围。 如果提供了该设置， 那么该设置相比其他设置项是最优先的
```suggestion
`dnsTtl` :: 如果查询结果是通过 DNS 服务的话，设置 TTL 的范围。 如果提供了该设置， 那么该设置相比其他设置项是最优先的。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`templateType` :: 查询类型，用于 `名称前缀匹配` 。 这意味着任何查询，如果它的名称的前缀都与该字段匹配，那么则属于该模板。在以下示例中，任何对 geo-db 的查询都与该查询相匹配。 查询模板使用最长前缀匹配，因此可以使用高级模板，这些高级模板为了一些服务被重写。 静态查询会被首先解析，因此也可以重写查询模板
```suggestion
`templateType` :: 查询类型，用于 `名称前缀匹配` 。 这意味着任何查询，如果它的名称的前缀都与该字段匹配，那么则属于该模板。在以下示例中，任何对 geo-db 的查询都与该查询相匹配。 查询模板使用最长前缀匹配，因此可以使用高级模板，这些高级模板为了一些服务被重写。 静态查询会被首先解析，因此也可以重写查询模板。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +`templateRegexp` :: 一个可选的正则表达式，用于从整个名称字段中匹配提取对应的变量。 如果选择了该模板，在以下示例中正则表达式提取了 "-" 符号后的第一个变量作为数据库的名称而之后的变量均作为标签数据。 参考 RE2 文档以获取正则表达式的更多信息
```suggestion
`templateRegexp` :: 一个可选的正则表达式，用于从整个名称字段中匹配提取对应的变量。 如果选择了该模板，在以下示例中正则表达式提取了 "-" 符号后的第一个变量作为数据库的名称而之后的变量均作为标签数据。 参考 RE2 文档以获取正则表达式的更多信息。
```

2021-05-22 09:56 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +以下示例中， 你可以监视健康检查的状态并当状态不正常时收到通知
```suggestion
以下示例中， 你可以监视健康检查的状态并当状态不正常时收到通知。
```

2021-05-22 12:45 UTC, pigbayspy commented
已经根据 reviewer 的建议完成修改

2021-05-22 12:55 UTC, chengenzhao approved these changes

2021-05-23 07:54 UTC, Leibnizhu commented on docs/translation/vertx-consul-client/java/index.adoc
> +Vert.x 的 Consul 客户端允许应用通过阻塞或非阻塞的 HTTP 接口与 Consul 系统互动。
```suggestion
Vert.x 的 Consul 客户端允许应用通过阻塞或非阻塞的 HTTP 接口与 Consul 系统交互。
```

2021-05-23 08:02 UTC, Leibnizhu commented on docs/translation/vertx-consul-client/java/index.adoc
> +要注意的是，阻塞查询不能 *严格保证* 所返回的数据确实是发生了变化的。
```suggestion
要注意的是，阻塞查询 *不能严格保证* 所返回的数据确实是发生了变化的。
```

2021-05-23 08:20 UTC, chengenzhao commented on docs/translation/vertx-consul-client/java/index.adoc
> +Vert.x 的 Consul 客户端允许应用通过阻塞或非阻塞的 HTTP 接口与 Consul 系统互动。
交互的基本解释是
1、[each other] 互相;彼此。
交互校订译文。
2、[alternately] 交替地。
交互使用两种方法。 

interact翻译成互动比较好，英汉词典直接查互动的英语就是interact
 互动 [动词] interact; mutually engage;

2021-05-23 10:12 UTC, pigbayspy commented
- 已经根据 reviewer 的建议完成修改
- **interact** 我本来翻译的也是交互，这里你们统一一下意见

2021-05-23 10:45 UTC, merged