translation of RxJava1/2
vertx-china/vertx-china.github.io pull request #170
Opened 2021-05-28 13:45 UTC by Leibnizhu

close #49

2021-05-28 13:59 UTC, chengenzhao approved these changes

2021-05-28 16:07 UTC, Leibnizhu commented on docs/translation/vertx-rx/java2/index.adoc
> +只需使用 ``link:../../apidocs/io/vertx/reactivex/core/Vertx.html#vertx--[Vertx.vertx]` 方法：
```suggestion
只需使用 `link:../../apidocs/io/vertx/reactivex/core/Vertx.html#vertx--[Vertx.vertx]` 方法：
```

2021-05-29 01:18 UTC, okou19900722 requested changes

2021-05-29 01:18 UTC, okou19900722 commented on docs/translation/vertx-rx/java2/index.adoc
>  TIP: There is also a `io.vertx.reactivex.WriteStreamObserver` adapter for the non-backpressured `io.reactivex.Observable`.
这段没有翻译

2021-05-29 01:34 UTC, chengenzhao approved these changes

2021-05-29 01:34 UTC, chengenzhao commented on docs/translation/vertx-rx/java2/index.adoc
>  TIP: There is also a `io.vertx.reactivex.WriteStreamObserver` adapter for the non-backpressured `io.reactivex.Observable`.
```suggestion
TIP: 另外也存在用于非回压的 `io.reactivex.Observable` 使用的 `io.vertx.reactivex.WriteStreamObserver` 适配器。
```

2021-05-29 02:09 UTC, okou19900722 approved these changes

2021-05-29 02:09 UTC, merged