http proxy 翻译
vertx-china/vertx-china.github.io pull request #187
Opened 2021-06-02 10:11 UTC by dreamlike-ocean

2021-06-03 09:48 UTC, okou19900722 requested changes

2021-06-03 09:48 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +== 使用 Vert.x Http Proxy
```suggestion
[[_using_vert_x_http_proxy]]
== 使用 Vert.x Http Proxy
```

2021-06-03 09:48 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +== Http Proxy基础
```suggestion
[[_basic_http_proxy]]
== Http Proxy基础
```

2021-06-03 09:48 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +== 源服务器
```suggestion
[[_origin_server]]
== 源服务器
```

2021-06-03 09:48 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +== 使用 `HttpProxy` 的 *代理服务器*
```suggestion
[[_proxy_server_with_httpproxy]]
== 使用 `HttpProxy` 的 *代理服务器* 
```

2021-06-03 09:51 UTC, okou19900722 requested changes

2021-06-03 09:51 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
>  * Maven (in your `pom.xml`):
这里没有翻译，还有下面gradle

2021-06-03 10:30 UTC, chengenzhao requested changes

2021-06-03 10:30 UTC, chengenzhao commented on docs/translation/vertx-http-proxy/java/index.adoc
> +使用 Vert.x Http Proxy之前，请把以下的依赖放到你的构建描述文件的 _依赖_ 部分中
```suggestion
使用 Vert.x Http Proxy之前，请把以下的依赖放到您的构建描述文件的 _依赖_ 部分中
```

2021-06-03 10:30 UTC, chengenzhao commented on docs/translation/vertx-http-proxy/java/index.adoc
> +为了使用Vert.x Http Proxy实现一个反向代理，你需要了解这些名词：
```suggestion
为了使用Vert.x Http Proxy实现一个反向代理，您需要了解这些名词：
```

2021-06-03 10:30 UTC, chengenzhao commented on docs/translation/vertx-http-proxy/java/index.adoc
> +现在，你已经了解了相应的整体概念。
```suggestion
现在，您已经了解了相应的整体概念。
```

2021-06-03 13:33 UTC, chengenzhao approved these changes

2021-06-04 00:54 UTC, okou19900722 approved these changes

2021-06-04 00:54 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +* Maven (在您的  `pom.xml` 文件中):
```suggestion
* Maven （在您的 `pom.xml` 文件中）：
```

2021-06-04 00:54 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +* Gradle (在您的  `build.gradle` 文件中):
```suggestion
* Gradle （在您的 `build.gradle` 文件中）：
```

2021-06-04 00:54 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +创建一个监听在 `8080` 端口的使用 `HttpProxy` 实例的 *代理服务器* 处理相应的反向代理逻辑
```suggestion
创建一个监听在 `8080` 端口的使用 `HttpProxy` 实例的 *代理服务器* 
处理相应的反向代理逻辑
```

2021-06-04 00:54 UTC, okou19900722 commented on docs/translation/vertx-http-proxy/java/index.adoc
> +Vert.x Http Proxy 是一个基于Vert.x的反向代理服务器，其目的是实现可重用的反向代理逻辑
```suggestion
Vert.x Http Proxy 是一个基于Vert.x的反向代理服务器，其目的是实现可重用的反向代理逻辑，
```

2021-06-04 00:55 UTC, merged