翻译SQL-Client 连接池高级配置文档
vertx-china/vertx-china.github.io pull request #209
Opened 2021-07-03 06:54 UTC by shenzhou-6

2021-07-03 10:15 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +你可以使用多个数据库服务列表来配置连接池而不是单个服务。
```suggestion
你可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```

2021-07-03 10:15 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +NOTE: 负载均衡在创建连接时提供的，而不是从池中获取连接时
```suggestion
NOTE: 负载均衡是在创建连接时提供的，而不是在从连接池中获取连接时提供
```

2021-07-03 10:15 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +在连接创建后和返回连接池之前你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]` 来与连接交互
```suggestion
你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]` 方法在连接创建后和连接释放回连接池之前来与数据库连接交互
```

2021-07-03 10:15 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +    // 从连接池中释放连接，以被应用程序继续使用Release the connection to the pool, ready to be used by the application
```suggestion
    //  将连接释放回连接池，以被该应用程序复用
```

2021-07-03 10:15 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接使用完后, 你应该释放该连接以通知连接池该数据库连接可以被使用
```

2021-07-05 01:52 UTC, okou19900722 requested changes
只翻译了 `pool_config.adoc`。

还有 `vertx-mssql-client` 的 `index.adoc` 的252行 以及 `vertx-pg-client` 的 `override/rxjava3.adoc` 没有翻译

2021-07-05 06:52 UTC, okou19900722 approved these changes

2021-07-05 07:06 UTC, chengenzhao requested changes

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +你可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```suggestion
您可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```suggestion
您可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接使用完后，您应该释放该连接以通知连接池该数据库连接可以被使用
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mssql-client/java/index.adoc
> +你可以在插入新数据后使用 `OUTPUT` 子句来获取自增列的值
```suggestion
您可以在插入新数据后使用 `OUTPUT` 子句来获取自增列的值
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mssql-client/java/pool_config.adoc
> +你可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```suggestion
您可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mssql-client/java/pool_config.adoc
> +你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```suggestion
您可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mssql-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后，您应该释放该连接以通知连接池该数据库连接可以被使用
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mysql-client/java/pool_config.adoc
> +你可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```suggestion
您可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mysql-client/java/pool_config.adoc
> +你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```suggestion
您可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-mysql-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后，您应该释放该连接以通知连接池该数据库连接可以被使用
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/pool_config.adoc
> +你可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```suggestion
您可以使用包含多个数据库服务的列表来配置连接池而不是单个数据库服务。
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/pool_config.adoc
> +你可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```suggestion
您可以使用 `link:../../apidocs/io/vertx/sqlclient/Pool.html#connectHandler-io.vertx.core.Handler-[connectHandler]`
```

2021-07-05 07:06 UTC, chengenzhao commented on docs/translation/vertx-pg-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后，您应该释放该连接以通知连接池该数据库连接可以被使用
```

2021-07-05 08:05 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后，您应该释放连接以通知连接池可以继续使用该连接
```

2021-07-05 08:05 UTC, pigbayspy commented on docs/translation/vertx-pg-client/java/override/rxjava3.adoc
> +客户端提供原始API的修订版本
```suggestion
客户端提供了原生 API 的响应式版本
```

2021-07-05 08:18 UTC, okou19900722 commented
`pool_config.adoc` 还是以一个模块的为主，4个模块的，除了一小段代码不同，其他地方都是一样的，所以不管是在review还是翻译，都只以一个为准，然后复制到其他模块去

2021-07-05 14:36 UTC, chengenzhao approved these changes

2021-07-05 15:01 UTC, pigbayspy commented on docs/translation/vertx-db2-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后, 您应该释放连接以通知连接池可以继续使用该连接
```

2021-07-05 15:01 UTC, pigbayspy commented on docs/translation/vertx-mssql-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后, 您应该释放连接以通知连接池可以继续使用该连接
```

2021-07-05 15:01 UTC, pigbayspy commented on docs/translation/vertx-mysql-client/java/pool_config.adoc
> +连接完成后,你应该释放连接以通知连接池可以继续使用该连接
```suggestion
连接完成后, 您应该释放连接以通知连接池可以继续使用该连接
```

2021-07-06 03:20 UTC, pigbayspy approved these changes

2021-07-06 03:40 UTC, merged