core剩下的（除了16-20）
vertx-china/vertx-china.github.io pull request #3
Opened 2020-12-22 13:43 UTC by Leibnizhu

搞上来我自己对比下先

2020-12-24 09:45 UTC, okou19900722 reviewed
两处格式错误

2020-12-24 09:45 UTC, okou19900722 commented on docs/translation/vertx-core/java/index.adoc
> +程序参数中写：`run your-verticle-fully-qualified-name --redeploy=**/*.class
--redeploy=**/*.class
应该是
--redeploy=\**/*.class

2020-12-24 09:45 UTC, okou19900722 commented on docs/translation/vertx-core/java/index.adoc
> +区域（ _Arguments_ 选项卡中），写入 `run your-verticle-fully-qualified-name --redeploy=**/*.java
--redeploy=**/*.class
应该是
--redeploy=\**/*.class

2020-12-27 06:21 UTC, Leibnizhu reviewed
现在剩：
大段没翻译的：
http： Handling cookies，Pumping 响应 最后一段，Handling exceptions，Request and response composition，Server Name Indication (SNI)，Event bus handlers，Handling of other protocols， Using HA PROXY protocol
net: 指定服务端的密钥/证书 最后一段，Server Name Indication (SNI)，
未搬运的：
shareddata.adoc
filesystem.adoc
datagrams.adoc

2020-12-27 06:21 UTC, Leibnizhu commented on docs/translation/vertx-core/java/index.adoc
> -----
此处参考english分支的514行附近，删除 `----` ：
![image](https://user-images.githubusercontent.com/13050963/102950117-d8896200-4504-11eb-9599-aa15a2d60332.png)

2020-12-27 06:21 UTC, Leibnizhu commented on docs/translation/vertx-core/java/index.adoc
>  [[high_avalibability_and_fail_over]]
整个index文档和english分支对比，多了一行，就是在这里加了锚点

2020-12-27 06:23 UTC, Leibnizhu commented on docs/translation/vertx-core/java/index.adoc
> +程序参数中写：`run your-verticle-fully-qualified-name --redeploy=**/*.class
已修复

2020-12-27 13:54 UTC, okou19900722 commented on docs/translation/vertx-core/java/index.adoc
>  [[high_avalibability_and_fail_over]]
@Leibnizhu 不只是这里要加锚点，所有标题都得加锚点，否则锚点定位就全部出问题了。

2020-12-27 13:57 UTC, okou19900722 commented on docs/translation/vertx-core/java/index.adoc
> -----
此处是我特意加的，eclise-vertx/vert.x 仓库的源文件前面有个空格，所以这行正常显示，但是vertx-stack-doc打包之后，空格莫名奇妙的消失，所以我加了这个格式是用来标识这是一段代码的

2021-01-01 08:46 UTC, chengenzhao commented on docs/translation/vertx-core/java/cli.adoc
> +非必填选项可以拥有一个默认选项值，在用户没有输入对应的选项值时，
非必填选项可拥有一个_默认值_
另外，改成选项_缺省值_是不是更好？

2021-01-01 08:53 UTC, chengenzhao commented on docs/translation/vertx-core/java/dns.adoc
> +尝试解析给定名称的所有A（ipv4）记录，这与在unix操作系统上
unix like
-> 类unix
应该linux，mac也算

2021-01-01 08:53 UTC, chengenzhao commented on docs/translation/vertx-core/java/dns.adoc
> +尝试解析给定名称的所有AAAA（ipv6）记录，这与在Unix操作系统上
类unix

2021-01-01 08:53 UTC, chengenzhao commented on docs/translation/vertx-core/java/dns.adoc
> +尝试解析给定名称的所有CNAME记录，这与在Unix操作系统上
同上

2021-01-01 08:55 UTC, chengenzhao commented on docs/translation/vertx-core/java/dns.adoc
> +有关详细信息，请参阅API文档。
详细信息请参阅api文档

2021-01-01 09:11 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +下面是一个增加Cookie的例子：
查询
并增加cookie的例子
querying漏了

2021-01-01 09:12 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +默认情况下解压缩是被禁用的。
禁用
可改为
并未被启用

2021-01-01 09:17 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +==== Pumping 响应
这里应该不是pumping，而是pipe，用管道传送的意思

2021-01-01 09:17 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +它为请求体使用了 Pump，所以即使 HTTP 请求体很大并填满了内存，
使用了管道，而不是pump

2021-01-01 09:18 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +`link:../../apidocs/io/vertx/core/streams/ReadStream.html[ReadStream]` 向其泵送数据，如 `link:../../apidocs/io/vertx/core/file/AsyncFile.html[AsyncFile]`， `link:../../apidocs/io/vertx/core/net/NetSocket.html
向其传送数据

2021-01-01 09:19 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +Vert.x 支持 HTTP 压缩，开箱即用。
支持开箱即用的HTTP压缩

2021-01-01 09:20 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +例如，您可以将磁盘上的文件直接泵送到HTTP 请求体中，如下所示：
泵送 -> 管送

2021-01-01 09:20 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +自己聚合：
自己聚合 ->  自行聚合

2021-01-01 09:23 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +`link:../../apidocs/io/vertx/core/streams/WriteStream.html[WriteStream]` 的实现类，因此可以和泵(pump)一起使用。
pump改了
因此可以和管道（pipe）一起使用

2021-01-01 09:24 UTC, chengenzhao commented on docs/translation/vertx-core/java/http.adoc
> +==== 流式 WebSocket
管道输送 websocket？

2021-01-01 12:34 UTC, chengenzhao reviewed
review index.adoc

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +大多数Vert.x 对象可以从被不同的线程安全地访问， _但_ 在
然而

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +如您坚持使用标准的Vert.x Verticle部署模型，避免在 Verticle 之间分享对象，
坚持改为遵守比较好
如您已经遵守了标准的……

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +事实是，很多，也非所有的库，特别是在JVM生态系统中有很多同步API，这些API中许多方法都是
很多，如果不是多数，的库

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +若您不需要关心您调用 `link:../../apidocs/io/vertx/core/Vertx.html#executeBlocking-io.vertx.core.Handler-boolean-io.vertx.core.Handler-[executeBlocking]` 的顺序，
不需要关心 -> 不关心

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +可以为不同的用途创建不同的池：
池可以加上（pool），上下文中有时翻译，有时不翻译，容易乱

2021-01-01 12:34 UTC, chengenzhao commented on docs/translation/vertx-core/java/index.adoc
> +=== 运行 Verticle
verticles，复数

2021-01-01 12:58 UTC, Leibnizhu commented on docs/translation/vertx-core/java/index.adoc
>  [[high_avalibability_and_fail_over]]
锚点后面改吧，这里先不处理了，看看效果先

2021-01-02 00:05 UTC, chengenzhao reviewed
有一个小typo

2021-01-02 00:05 UTC, chengenzhao commented on docs/translation/vertx-core/java/datagrams.adoc
> +===== B屏蔽多播
多敲了一个B

2021-01-02 13:04 UTC, chengenzhao approved these changes

2021-01-03 08:20 UTC, wkgcass requested changes

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/cli-for-java.adoc
> +如果您的命令行选项存在 `enum` 类型，则会自动计算出一组选择范围。
选择范围 => 可选值

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/cli.adoc
> +Vert.x CLI 提供了一个编程模型用以描述命令行界面，这个编程模型也可以视为一种语法解析器，这个语法解析器支持
原文应该想说的是not only command line interface, but also a parser.
这里可以翻译成：不但提供一个编程模型用以描述命令行界面，还提供一个语法解析器。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/cli.adoc
> +参数没有名称，它们是以从 `0` 开始计数的索引为标识。第一个参数的
它们以从 `0` 开始计数的索引为标识

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/cli.adoc
> +`argName` 是可选的，并且能在使用说明信息中使用。
并且在说明信息中会使用这个字段。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/cli.adoc
> +不会失败，而是有机会检查用户是否在寻求帮助：
而你有机会检查用户是否在寻求帮助

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +唯一的保证是，它既不会被完全接收到，也不会完全不被接收到，
唯一可以保证的是，数据包要么被完整地接收，要么完全收不到

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +因为每一个数据包将会作为一个包发送，所以在通常情况下您不能发送大于网络接口的最大传输单元（MTU）的数据包。
译者注：实际上大于MTU的包是可以发送成功的，只不过数据包会在IP层做分片。由于分片不携带4层信息，所以有些NAT为了性能等因素会丢弃分片报文。而接收分片报文时，需要所有分片在规定时间内全部接收到，才算作收到一个完整的UDP包，所以分片报文的传输失败率会更高。一般不要发送超过`MTU - len(IP.header) - len(UDP.header)`长度的包。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +      //对包进行处理
加个空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +注意，即使 {code AsyncResult} 成功，它只意味着它可能已经写入了网络堆栈，
`{code AsyncResult}`好像不能正确的变成`AsyncResult`。至少官网是这样的。adoc语法问题

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +一个地址并且加入多播组，并加入多播组。
重复了

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/datagrams.adoc
> +转发数据包的每个路由器或网管会递减TTL，
网管 => 网关

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/dns.adoc
> +要查找您常用执行的 "vertx.io" 的所有MX记录：
要查找 "vertx.io" 的所有MX记录，您通常会执行以下操作：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/dns.adoc
> +尝试解析给定名称的PTR记录，PTR记录将 `ipaddress` 映射到名称。
ipaddress => ip地址

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/dns.adoc
> +尝试对ipaddress进行反向查找，这与解析PTR记录类似。但是允许您
ipaddress => ip地址

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/dns.adoc
> +传递非有效PTR查询字符串的ipaddress。
ipaddress => ip地址

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/dns.adoc
> +要做ipaddress 10.0.0.1的反向查找类似的事：
按照类似于下面这种方式来进行ip地址 10.0.0.1 的反向查找：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +阻塞版本的方法名为 `xxxBlocking`，它要么返回结果或直接抛出异常。很多
要么返回结果要么直接抛出异常

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +Vert.x 文件系统支持诸如 copy、move、truncate、chmod 和许多其他文件操作。我们不会在这里列出所有内容，
“诸如”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +`AsyncFile` 实现了 `ReadStream` 和 `WriteStream` 接口，因此您可以将文件和其他流对象配合 _管但_ 工作，
管道

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> + `link:../../apidocs/io/vertx/core/file/AsyncFile.html#flush--[flush]` 方法手动刷新OS缓存中的数据写入。
手动将OS缓存中的数据写入存储设备

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +该方法也可使用一个处理器来调用，这个处理器在 `flush` 完成时被调用。
该方法也可附带一个处理器来调用

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +也会提供原始内容。
也会提供之前的内容。
“原始”用词有迷惑性

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +方法进行设定。如同系统属性中没有预先设置 `vertx.disableFileCaching` ，
如同 => 如果

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/filesystem.adoc
> +如果希望在关闭过后收到通知，您可指定一个处理器作为函数（`close`）参数传入。
如果希望在关闭过后收到通知，您可指定一个处理器作为函数 `close` 的参数。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/override/dns.adoc
> +查询完成后会传入调用Handler并一个 AsyncResult。在出现错误的情况下，通知中将
查询完成后会向其传入一个 AsyncResult。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/override/dns.adoc
> +可用于更详细检查原因。
可帮助你更详细地检查原因

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/override/dns.adoc
> +- `link:../../apidocs/io/vertx/core/dns/DnsResponseCode.html#NOERROR[NOERROR]` 没有找到给定查询的记录
没有找到待查询的记录

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/override/dns.adoc
> +- `link:../../apidocs/io/vertx/core/dns/DnsResponseCode.html#NOTIMPL[NOTIMPL]` DNS 服务器没实现
DNS 服务器未实现

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +记录解析器（Record Parser）允许您轻松解析由字节序列或固定长度带分隔符的记录的协议。
记录解析器（Record Parser）允许您轻松解析由字节序列分割的协议，或者固定长度的协议。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +它将输入缓冲区序列转换为已配置的缓冲区序列（固定大小
它将输入缓冲区序列转换为按照配置重组后的缓冲区序列

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +你可以很容易的解析JSON格式的内容，但是这就要求一次性提供整个JSON内容，
解析JSON结构很容易，但这要求你一次性提供完整的JSON，

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +而如果你要提供一个非常大的JSON，JSON解析器恐怕就不是个方便的方式。
而对于非常大的JSON结构，则并不是特别适合使用JSON解析器来处理。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +它将传输一系列`input buffer`到一系列JSON解析器事件。
它会将一系列的`input buffer`转换为一系列的JSON解析器事件。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +该解析器是非阻塞的，并且由 `input buffer` 驱动触发的事件
该解析器是非阻塞的，并且事件由输入的buffer来驱动触发。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +是不方便的。当你需要的时候，JSON解析器允许你将JSON做为值(`value-mode`)处理。
事件驱动的解析过程提供了更多的控制能力，同时带来了“需要处理细粒度事件”的缺点，有时候不太方便。当你需要的时候，JSON解析器允许你将JSON结构作为值处理。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +`event-mode` 事件和 JSONObject的 `value-mode` 事件之间自由切换。
`value-mode` 可以在解析过程中启用或停用，允许你在细粒度事件与JSON对象事件之间自由切换。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +你也可以反解析到POJO。
你也可以解码为POJO。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/parsetools.adoc
> +  // 捕捉所有的解析/反解析异常
捕捉所有的解析/解码异常

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +顾名思义，`link:../../apidocs/io/vertx/core/shareddata/SharedData.html[共享数据（SharedData）]` API允许您:
顾名思义，`link:../../apidocs/io/vertx/core/shareddata/SharedData.html[共享数据（SharedData）]` API允许您在如下组件中安全地共享数据:

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +网络分区面临的备份（复制）和行为由集群管理器和它的配置来定义。
备份（复制）以及当出现网络分区时的行为，由集群管理器和其配置来决定。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +`link:../../apidocs/io/vertx/core/shareddata/LocalMap.html[Local maps]` 允许您在同一个 Vert.x 实例中的不同 event loops（如不同的 verticles 中）之间安全共享数据。
`link:../../apidocs/io/vertx/core/shareddata/LocalMap.html[Local maps]` 允许您在同一个 Vert.x 实例中的不同事件循环（如不同的 verticle）之间安全地共享数据。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +本地共享Map仅允许将某些数据类型作为键值和值：
仅允许将某些数据类型作为键值和值：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +获取Map的过程是异步的，返回结果可以传给您指定的处理器中。以下是一个例子：
获取Map的过程是异步的，返回结果可以传递给您指定的处理器。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +当 Vert.x 是集群模式时, 你放进map的数据既可本地访问也会保存在集群内其它的成员节点上。
当 Vert.x 是集群模式时, 你放进map的数据，从本地以及从集群中的其他成员那里，都是可以访问到的。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +请注意，相对于异步共享map的操作，延迟在群集中可能比在本地模式下高得多。
请注意，异步共享map操作的延迟，在集群模式下可能比在本地模式下高很多。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +当你的应用不需要和其它任何节点共享数据, 你可以获取一个仅限本地的 map：
如果你的应用不需要和其它任何节点共享数据，那么你可以获取一个仅限本地的 map：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +当您想要在任何时间只在集群一个节点上执行某些操作或访问资源时，这很有用。
异步锁适用于：同一时刻仅在一个节点上执行某些操作或访问某个资源。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +它不会阻塞，但当锁可用时，将 `link:../../apidocs/io/vertx/core/shareddata/Lock.html[Lock]` 的实例传入处理器并调用它，表示您现在拥有该锁。
它不会阻塞，但当锁可用时， `link:../../apidocs/io/vertx/core/shareddata/Lock.html[Lock]` 的实例会被传入处理器，表示您现在拥有该锁。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +若您拥有的锁没有其他调用者，集群上的任何地方都可以获得该锁。
当您持有锁时，无论是本地还是集群中的其他调用者都无法获得该锁。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +您可以为锁设置一个超时，若在超时时间期间无法获取锁，将会进入失败状态，处理器会去处理对应的异常：
您可以为锁设置一个超时时间，若获取锁超时，则会通知处理器获取锁失败：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +请注意，相对于异步共享锁的操作，延迟在群集中可能比在本地模式下高得多。
请注意，异步共享锁的操作的延迟，在集群模式下可能比在本地模式下高很多。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +当你的应用不需要和其它任何节点共享锁，你可以获取一个仅限本地的锁：
当 => 如果

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +在本地或跨越你应用程序的不同节点来维护一个原子计数器通常很有用。
有时你会需要在本地或者在应用节点之间维护一个原子计数器。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +并使用各种方法添加一个值。
在获取了一个实例后，您可以用多种方式获取当前的计数、原子地+1、-1、加某个特定值。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +请注意，相对于异步共享计数器的操作，延迟在群集中可能比在本地模式下高得多。
请注意，异步共享计数器操作的延迟，在集群模式下可能比在本地模式下高很多。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/shareddata.adoc
> +当你的应用不需要和其它任何节点共享计数器, 你可以获取一个仅限本地的计数器：
当 => 如果

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +Vert.x有多个对象可以用于文件的读取和写入。
在Vert.x中，有许多对象可以用于读取和写入。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +名为 `link:../../apidocs/io/vertx/core/streams/ReadStream.html#pipeTo-io.vertx.core.streams.WriteStream-[pipeTo]` 方法替你完成这些繁杂的工作。
名为xxx的方法

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +最终 当pipe最终成功或失败时， `WriteStream` 就会停止。
开头的最终去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +这个对象会暂停源文件流，并在源文件流通过pipe传输到目标时恢复源文件流：
当你处理异步目标时，你可以创建一个 `link:../../apidocs/io/vertx/core/streams/Pipe.html[Pipe]` 对象，
这个对象会暂停源流，并在源流通过pipe传输到目标时恢复源流

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +    // 打开源文件流
打开目标文件

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +        // 用管道传输socket当中的信息到源文件流 并最终关闭源文件流
用管道传输socket当中的信息到文件中，并最终关闭文件

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +由以上看来，默认情况下，stream传输完毕之后，源文件流都会停止。你可以
由以上看来 => 从上面可以看出
源文件流 => 目标流

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +现在我们来看看 `ReadStream` 和 `WriteStream` 的方法。
让我们更进一步，看看 `ReadStream` 和 `WriteStream` 的细节。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +从stream中抓取指定数量的对象，这些对象中任意一个到达目的地之后，都会触发handler，fetch操作
这些对象中任意一个到达目的地之后 => 任意对象抵达stream时

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/streams.adoc
> +判定 `WriteStream` 不会再满时调用。
判定 `WriteStream` 有剩余空间时调用。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +Vert.x允许您很容易编写非阻塞的TCP客户端和服务器。
Vert.x让您轻松编写非阻塞的TCP客户端和服务器。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +写入操作是异步的，可能调用 `write` 方法返回过后一段时间才会发生。
发生 => 执行

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +在 `link:../../apidocs/io/vertx/core/net/NetServer.html#connectHandler-io.vertx.core.Handler-[connectHandler]` 处理连接前发生的所有异常，
在 `link:../../apidocs/io/vertx/core/net/NetServer.html#connectHandler-io.vertx.core.Handler-[connectHandler]` 接受到连接对象前发生的所有异常，

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +`link:../../apidocs/io/vertx/core/streams/WriteStream.html[WriteStream]` 接口，因此您可以将它套用（pump）到其他的
pump => pipe

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +第一种方法是指定包含密钥和证书的Java 密钥库的位置，它只是一个常规的Java 密钥存储。
考虑把Java前面也加上空格？

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +PKCS＃12格式的密钥/证书（ http://en.wikipedia.org/wiki/PKCS_12 ，通常为 `.pfx` 或 `.p12` 扩展名），
`#`没必要换成全角把

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +请记住 `pem` 的配置和私钥是不加密的。
和 => 的

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +您可以在连接socket时，可以提供明确的服务器名称
您可以在连接socket时，提供明确的服务器名称

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/net.adoc
> +依赖于tcnative的实现它需要OpenSSL安装在您的操作系统中。
依赖于tcnative的实现，需要OpenSSL安装在您的操作系统中。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +大多数Vert.x 对象可以从被不同的线程安全地访问， _然而_ 在
“被”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +例如，若您部署了一个创建 `link:../../apidocs/io/vertx/core/net/NetServer.html[NetServer]` 的Verticle，该`NetServer`在处理器中提供了
例如，若您部署了一个创建了 `link:../../apidocs/io/vertx/core/net/NetServer.html[NetServer]` 的Verticle，该`NetServer`在处理器中提供了

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +
这篇里面很多中英文之间没有加空格，可以考虑补下

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +他能使用event-bus 或 `link:../../apidocs/io/vertx/core/Context.html#runOnContext-io.vertx.core.Handler-[runOnContext]` 与verticles交互
他需要能够使用event-bus 或 `link:../../apidocs/io/vertx/core/Context.html#runOnContext-io.vertx.core.Handler-[runOnContext]` 与verticles交互

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +其他Vert.x实例进行集群通信。若没有设置，集群的eventbus会尝试绑定到
开头加个“与”：与其他

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +`link:../../apidocs/io/vertx/core/Launcher.html[Launcher]` ，但您已使用了您自己的 _主类_ 。
我怀疑英文写错了。这句英文都有2处语法错误，我怀疑他想说的是but you can use your own main。
这里直接翻译成 但您也可以使用您自己的主类

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +会增量编译您的文件，重部署工作会顺利进行。
第一个“会”去掉，
随着 Eclipse 在保存时增量编译您的文件，重部署工作会顺利进行。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +--launcher-class=io.vertx.core.Launcher` 。要触发重新部署，您需要显示 _构造_ 项目或
显示 => 显式

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +集群管理器 _不_ 处理Event Bus节点之间的传输，这是由 Vert.x 直接通过TCP连接完成。
“是”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/index.adoc
> +最后，您可以使用 `-Dvertx.disableFileCPResolving=true` 完全禁用高速缓存。这个设置
高速缓存 => 缓存
统一描述

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +sHTTP/2 协议。
开头的s去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +Vert.x支持 TLS `h2` 和TCP `h2c` 之上的 HTTP/2 协议。
Vert.x 通过 TLS 之上的 `h2` 和 TCP 之上的 `h2c` 来支持 HTTP/2 协议。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +HTTP/1.1升级 请求或者直接建立
这样的连接可以使用 HTTP/1.1 升级请求建立，也可以直接建立

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +协议。
通常情况，ALPN会对 `h2` 协议达成一致，不过服务器或客户端仍然可以决定使用 `HTTP/1.1` 协议。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +为了进行调试，网络活动可以打日志。
网络活动可以被记录下来，用于调试。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +要告诉服务器监听传入的请求，您可以使用其中一个 `link:../../apidocs/io/vertx/core/http/HttpServer.html#listen--[listen]`
告诉 => 让

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
>  HttpServer server = vertx.createHttpServer();
例子里并没有配置项。这个可以搞个例子

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +请注意，这是在HTTP 请求中传递的实际URI，它总是一个相对的URI。
HTTP前面加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +使用 `link:../../apidocs/io/vertx/core/http/HttpServerRequest.html#headers--[headers]` 方法获取HTTP 请求中的请求头部信息。
HTTP前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +同一个键支持多个值 —— 因为HTTP允许同一个键支持多个请求头的值。
并且它还允许同个键对应多个值 —— 因为HTTP允许同一个键对应多个请求头的值。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +它的键值不区分大小写，这意味着您可以执行以下操作：
它的键不区分大小写

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +对于 HTTP/1.x 请求返回请求头中的 `host` 值，对于 HTTP/1 请求则返回伪头中的 `:authority` 的值。
原文写错了。pseudo header是HTTP/2的。后面那个HTTP/1改成HTTP/2

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +当整个请求（包括任何正文）已经被完全读取时，请求中的 `link:../../apidocs/io/vertx/core/http/HttpServerRequest.html#endHandler-io.vertx.core.Handler-[endHandler]`
包括任何正文=> 包括所有请求体
body翻译成正文十有八九是看不懂的

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +==== 请求体中读取数据
从请求体中读取数据

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +HTTP请求通常包含我们需要读取的主体。如前所述，当请求头部达到时，
主体 => 请求体

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +以便您可以按照下边的方式进行聚合：
“以便”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +正文 *之前* 调用 `link:../../apidocs/io/vertx/core/http/HttpServerRequest.html#setExpectMultipart-boolean-[setExpectMultipart]` 方法，
正文 => 请求体

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +若您只是想将文件上传到服务器的某个磁盘，可以使用 `link:../../apidocs/io/vertx/core/http/HttpServerFileUpload.html#streamToFileSystem-java.lang.String-io.vertx.core.Handler-[streamToFileSystem]` 方法：
若您只是想将文件上传到服务器磁盘的某个地方

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +取值、域名、路径以及其他cooki的常规属性。
cooki => cookie

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +=== 发回响应
返回响应

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +NOTE: 对于 HTTP/2 中的状态不会在响应中描述 —— 因为协议不会将消息发送
原文有问题，不发送的仅仅是reason，就是OK/Bad Request这种，status是有的，在header里。
这里直接翻译成：
在 HTTP/2 中，状态码的描述信息不会在响应中出现 —— 因为协议不传递该信息。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +不使用HTTP 分块，那么必须在写入响应之前设置 `Content-Length` 头，否则
HTTP前面加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这种情况，它和先调用带String或Buffer参数的 `write` 方法，之后调用无参 `end` 方法一样。例如：
这种方式类似于先调用带String或Buffer参数的 `write` 方法，再调用无参 `end` 方法。例如：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +响应头必须在写入响应正文消息之前进行设置。
响应正文消息=> 响应体

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +默认是不分块的，当处于分块模式，每次调用任意一个 `link:../../apidocs/io/vertx/core/streams/WriteStream.html#write-java.lang.Object-[write]`
当处于分块模式时

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +在分块模式下，您还可以将响应的HTTP 响应附加尾部(trailers)写入响应，这种方式实际上是在写入
HTTP前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +打开并其传送到HTTP 响应中。
打开并将其传送到HTTP 响应中。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +若底层操作系统支持，这会导致操作系统不通过用户空间复制而直接将文件内容中字节数据从
若底层操作系统支持，操作系统可以不拷贝到用户态而直接把数据从文件传输到Socket。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +或者，Vert.x 提供了一种方法，允许您在一个操作中将文件从磁盘或文件系统中读取并提供给HTTP
此外，Vert.x 提供了一种方法，允许您只执行一次操作，即可直接将文件从磁盘或文件系统写入 HTTP 响应。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +Vert.x Web替代。
WARNING: 若您要直接使用 Vert.x 编写 Web 服务器，请注意，不要允许用户滥用请求路径，以此访问服务目录之外的、或者 classpath 之外的路径。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +任何时候它依旧会工作：
所以即使 HTTP 请求体远远超过内存容量，它依旧可以正常工作。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这些帧被立即发送，并且不受流程控制的影响——当这样的帧被发送到那里时，
这些帧被立即发送，并且不受流控的影响 —— 当这样的帧被发送到对端时，

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +当服务器处理请求时，它可以向客户端推送请求/响应：
当服务器处理请求时，它可以向客户端推送一次请求/响应（server push会先推送一条“请求”，然后再推送对应的“响应”）：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +并不在需要它。
推送响应处理器可能会接收到失败，如：客户端可能取消推送，因为在缓存中已经包含了 `main.js`，
不再需要它。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +使用高于 1-2 的压缩级别通常允许仅仅保存一些字节大小 —— 它的增益不是线性的，并取决于要压缩的特定数据
保存 => 节约

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +在每个请求体生成时进行的）,它可生成压缩过的响应数据、并对接收的响应解码（膨胀）—— 和客户端使用的方式一致，
inflating不要翻译

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +`link:../../apidocs/io/vertx/core/http/HttpClientResponse.html#version--[version]` 方法检查响应实际HTTP版本。
检查实际HTTP版本。
这句里的“响应”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +为了进行调试，可以给网络活动打日志：
网络活动可以被记录下来，用于调试。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +如果 `Content-Length` 请求头没有预先设置，会自动设置。
则会自动设置

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +如果 `Content-Length` 请求头没有预先设置，会自动设置。
则会自动设置

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +如果 `Content-Length` 请求头没有预先设置，会设置分块传输的 `Content-Encoding` 请求头。
则会设置分块传输的......

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +若您在使用HTTP 分块模式，则不需要 `Content-Length` 头，因此您不必
HTTP前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这意味着您可以从任何 `link:../../apidocs/io/vertx/core/streams/ReadStream.html[ReadStream]` 实例将数据泵入请求中。
泵不用翻译
将数据pipe到请求中。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +默认情况，发送 `NO_ERROR(0)` 错误代码，可发送另一个代码：
另一个代码 => 其他错误代码

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +来接收到 `link:../../apidocs/io/vertx/core/http/HttpClientResponse.html[HttpClientResponse]` 的实例。
来接收 `link:../../apidocs/io/vertx/core/http/HttpClientResponse.html[HttpClientResponse]` 的实例。

“到”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +您可以泵送数据到任何 `link:../../apidocs/io/vertx/core/streams/WriteStream.html[WriteStream]` 实例。
泵送 => pipe

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +该方法返回的对象是 一个 `link:../../apidocs/io/vertx/core/MultiMap.html[MultiMap]` 实例，因为 HTTP 响应头中单个键可以关联多个值。
多了个空格：该方法返回的对象是一个......

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +要等待很长时间、又或者会花费大量内存。
如果响应中包含响应体，那么响应体可能会在读取完header后，以多个分片的形式到达。我们不会等待所有响应到达才调用响应处理器，因为响应可能会非常大，我们可能会等待很长一段时间，或者因为巨大的响应体而耗尽内存。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +其中传入的 `link:../../apidocs/io/vertx/core/buffer/Buffer.html[Buffer]` 中包含了响应体的这一分片（部分）内容：
“（部分）”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +因此您需要充分了解它的，否则可能会遇到数据争夺
因此您需要充分了解它的工作过程

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +因为如果在event-loop之外设置Future的完成处理器可能会很麻烦。
可能会导致线程竞争。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +在verticle外使用HttpClient进行交互时，可以安全地组合使用，
在verticle外使用HttpClient进行交互时，可以安全地使用“组合”(compose)，

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +* 当返回的是 `Future` 时，请求失败时调用设置的异常处理器
请求失败时将调用设置的异常处理器

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这里的想法是允许服务器在发送大量数据之前授权、接收/拒绝请求，若请求不能被接收，
这里的想法是在发送大量数据之前允许服务器授权、接受/拒绝请求

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +即将丢弃的无用数据中。
并且会让服务器持续读取即将被丢弃的无用数据。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +      // 这可能是长连接最好的
// 长连接情况下最好加上（指的是`Connection: close`）

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +重置流（错误代码 `8` ）。
“流”去掉

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +HTTP/2 是用于 HTTP 请求/响应模型的具有各种帧的一个帧协议，该协议允许
HTTP/2 是一个基于帧的协议，它包含多种类型的帧，适用于 HTTP 请求/响应模型。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +将添加以下头：
要告诉服务器当前客户端支持哪种压缩，请求头将包含一个 `Accept-Encoding` 头，
其值为可支持的压缩算法，（该值可）支持多种压缩算法。Vert.x 会添加以下头：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +服务器将从其中（算法）选择一个，您可以通过服务器发回的响应中响应头
服务器将从其中选择一个算法，您可以通过服务器返回的响应中的响应头

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +客户端还支持连接上的请求管道(pipeline)。
客户端还支持同一条连接上的管道(pipeline)。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +管道不适合所有请求。
管道不是对所有请求都适用的。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +默认禁用管道的。
默认是禁用管道的。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +和同一个服务器的连接分发到客户端的公平性。
这个限制可以保证客户端请求数量在同一服务端的多条连接之间保持平衡。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +设置。
当您使用连接池（而不是单个连接），并希望限制每个连接的多路复用流数量时，可使用......

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +连接的复用限制是在客户端上设置限制单个连接的流数量。
连接的多路复用数量限制是在客户端上设置的流数量限制。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +则有效值可以更低。
设置了下限 => 设置的值比该值更低，
则有效值可以更低 => 则有效值会更低。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这个时间内没有使用的任何连接将被关闭，注意，空闲时间以秒为单位，不是毫秒。
这个时间内没有被使用过的连接将被关闭

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +设置的API。
设置（settings）的API。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +`link:../../apidocs/io/vertx/core/http/HttpConnection.html[HttpConnection]` 接口提供了处理HTTP 连接事件、生命周期、
HTTP前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +接收确认通知：
由于远端可能会发送配置更新的确认，所以可能会在回调中收到通知：

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +基于 HTTP/2 协议之上实现。
处理器只是接到通知，确认无论如何都会自动发送。这个功能是为基于 HTTP/2 实现的其他协议提供的。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +将等待一段时间（默认为30秒），直到所有当前流关闭和连接关闭。
直到所有当前流关闭，然后关闭连接。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +连接尚未关闭。
并且连接尚未关闭。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +当这种情况发生时，Vert.x会检测到并记录下边警告：
下边 => 以下

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +将被不同的Vert.x 线程和上下文调用，这样的上下文会根据需要创建。对于生产环境，
Vert.x前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +这个服务兼通8080端口。那么当verticle被实例化多次，如：
兼通 => 监听

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +以便在多核机器上扩展服务器。
以便 => 就可以

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +vert.x的HttpClient在TLS握手过程中会将实际的主机名作为 _服务名_ 。
_服务名_ => _服务名（server name）_

这里server name是专有名词，SNI=server name indication

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +您可以通过 `link:../../apidocs/io/vertx/core/http/ServerWebSocket.html[ServerWebSocket]` 实例读取在WebSocket 握手中HTTP请求的 `link:../../apidocs/io/vertx/core/http/WebSocketBase.html#headers--[headers]`，
WebSocket前加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +设置的W ebSocket 的帧的最大值，则Vert.x在将其发送到报文之前将其拆分为多个WebSocket 帧。
W ebSocket 空格有问题，第二个也有问题

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +后边跟着零个或多个 _连续_ 帧。
continuation是专有名词

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +WebSocket 消息可以由多个帧组成，在这种情况下，第一帧是 _二进制_ （text）或 _文本_ （binary）帧，
第一帧要么是 _二进制（binary）_ 帧，要么是 _文本（text）_ 帧

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +它只能用于不分割多个帧的二进制帧一起使用的 WebSocket 连接。
它只能用于 WebSocket 连接上连续传输的一组二进制帧（即二进制帧之间不能被其他帧分割）。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +==== Event bus处理器
bus后面加空格

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +只要将数据发送到这两个处理器监听的地址。
只要将数据发送到这两个处理器监听的地址即可。

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +HTTP 客户端支持通过HTTP 代理（如Squid）或 _SOCKS4a_ 或 _SOCKS5_ 代理访问 HTTP/HTTPS 的 URL。
HTTP前面加空格：“ HTTP 代理”

2021-01-03 08:20 UTC, wkgcass commented on docs/translation/vertx-core/java/http.adoc
> +当客户端连接到HTTP URL时，它连接到代理服务器，并在HTTP请求中提供完整URL
它连接到代理服务器 => 它会连接到代理服务器

2021-01-03 14:28 UTC, Leibnizhu commented on docs/translation/vertx-core/java/net.adoc
> +请记住 `pem` 的配置和私钥是不加密的。
改为“中”

2021-01-03 16:01 UTC, merged