翻译到 捕捉路径参数
vertx-china/vertx-china.github.io pull request #72
Opened 2021-01-02 08:39 UTC by sfiloveyou

翻译到 捕捉路径参数

2021-01-02 09:01 UTC, chengenzhao reviewed
没什么太大问题，一些细节符号的修改一下

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +* GraphiQL开发工具被禁用
graph ql
多了一个i，这里应该是原文档的一个bug
可以提交一个pr给官方修正

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +* Gradle (在你的 `build.gradle` 文件中):
你 -> 您
可以统一替换一下你为您

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +注意，所有发生的这些没有线程阻塞.
.改为。
句点改为句号

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +处理器非常强大, 因为它们允许您构建非常复杂的应用程序. 为了保证简单的响应, 例如直接从vert.x API返回异步响应, router 包含一个快捷的处理器:
同上
.改为。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +3. 如果序列化JSON中发生错误，一个适当的错误会返回.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +不过, 如果提供的函数支持调用`write`或`end`, 您还可以将其用于非JSON响应.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +某些时候您可能需要在处理器里执行一些需要阻塞 Event Loop 的操作, 比如调用某个传统的阻塞式 API 或者执行密集计算.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +您不能在普通的处理器里执行这些操作, 因此我们提供了将route设置成阻塞式处理器的功能.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +您可以使用 `link:../../apidocs/io/vertx/ext/web/Route.html#blockingHandler-io.vertx.core.Handler-[blockingHandler]`.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +默认情况下, 在同一个 Context (例如同一个 Verticle 实例) 上执行的所有阻塞式处理器是顺序的, 也就意味着只有一个处理器执行完了才会继续执行下一个. 如果您不关心执行的顺序，并且不介意阻塞式处理器以并行的方式执行, 您可以在使用 `link:../../apidocs/io/vertx/ext/web/Route.html#blockingHandler-io.vertx.c
。
这里可能要切成跟原来相同行数，不过格式可以最后统一处理

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +在下面这个例子中,处理器会被路径为 `/some/path/` 的请求调用. 我们会忽略结尾的 `/`, 所以路径 `/some/path` 或者 `/some/path//` 的请求也是匹配的
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +您经常需要为所有以某些路径开始的请求设置 `Route`. 您可以使用正则表达式来实现, 但更简单的方式是在声明 `Route` 的路径时使用一个 `*` 作为结尾.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +占位符由 `:` 和参数名构成. 参数名由字母, 数字和下划线构成.
。

2021-01-02 09:01 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +在上面的例子中, 如果一个 POST 请求的路径为  `/catalogue/products/tools/drill123/`, 那么会匹配这个 `Route`, 并且会接收参数 `productType` 的值为 `tools`, 参数 `productID` 的值为 `drill123`.
。

2021-01-02 12:45 UTC, Leibnizhu approved these changes

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> +Vert.x Web 的设计是强大的，非侵入式的, 并且是完全可插拔的.您可以只使用您需要的部分. Vert.x Web 不是一个容器.
这种可以按原文的换行的就直接换行吧

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> +Vert.x Web 非常适合编写 **RESTful HTTP 微服务**, 但我们不强制您必须把应用实现成这样.
原文加粗的部分是 “, but we don't force”

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> +Vert.x-Web是基于Vert.x的,用于构建Web应用程序的一系列构建模块. 可以将其视为一把构建现代的,可扩展的Web应用的瑞士军刀.
建议还是用中文符号， @okou19900722 觉得如何？  
包括但不限于：逗号，句号，问号，分号，冒号，目前来看这篇翻译都保留了英文符号

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> +* `ErrorHandler`不显示异常详细信息
` 的代码引用前后请留空格，否则解析不出来

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> +* `StaticHandler`不处理缓存头
` 的代码引用前后请留空格，否则解析不出来  
本文档多处类似的问题，请自行替换，不再赘述

2021-01-02 12:45 UTC, Leibnizhu commented on docs/translation/vertx-web/java/index.adoc
> -== Using blocking handlers
上面 267 行 漏了翻译：
> // in this case, the handler ensures that the connection is ended

2021-01-05 02:01 UTC, sfiloveyou commented
ok

2021-01-05 02:44 UTC, chengenzhao commented
fix #62

2021-01-05 02:51 UTC, okou19900722 requested changes
各级标题均需要增加锚点，方法见README_zh-CN.md

2021-01-05 02:51 UTC, okou19900722 commented on docs/translation/vertx-web/java/index.adoc
> +注意： 您也可以将 * 捕获为路径参数 * 。
Note不要翻译，Note: xxx是asciidoc的格式，统一处理的

2021-01-05 02:51 UTC, okou19900722 commented on docs/translation/vertx-web/java/index.adoc
> +== 使用 Vert.x Web
标题增加锚点，方法见README_zh-CN.md

2021-01-05 09:03 UTC, chengenzhao requested changes
锚点的case有点问题

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_Routingbyexactpath]]
不是这种case，是这种_routing_by_exact_path，点标题前面的#可以在地址栏中看到具体的锚点
<img width="1086" alt="EAF754FD-02ED-463B-B55C-E50886D7EF21" src="https://user-images.githubusercontent.com/5525436/103626831-b4ec0000-4f77-11eb-958b-66f4440f8bee.png">

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_Handlingrequestsandcallingthenexthandler]]
同下

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_Simpleresponses]]
同下

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_basicVertxWebconcepts]]
同下

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_Re-caponVertxcoreHTTPservers]]
同下

2021-01-05 09:03 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +[[_usingVertxWeb]]
看后面的评论

2021-01-06 00:05 UTC, chengenzhao approved these changes

2021-01-06 01:18 UTC, merged