熔断器翻译
vertx-china/vertx-china.github.io pull request #78
Opened 2021-01-07 01:49 UTC by PassXml

Hystrix Dashboard 翻译

有几种选择

* Hystrix仪表盘
* Hystrix控制面板
* Hystrix看板

2021-01-07 01:52 UTC, PassXml commented
#19

2021-01-07 04:50 UTC, okou19900722 requested changes

2021-01-07 04:50 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 准备工作
所有标题（二级，三级等）都需要加上锚点，具体参考[说明](https://github.com/vertx-china/vertx-web-site/blob/master/README.zh-CN.md)

2021-01-07 04:50 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +它用来追踪故障，当失败次数达到阈值时触发熔断，并且可选择性提供失败回调，以保证服务可用或长时间等待。
这里不需要空行，原文这两句话是一段。

2021-01-07 04:50 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 使用熔断器执行代码
建议保留原文的格式

2021-01-07 04:50 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +例如:在下面的例子中，对应的结果就是REST调用的输出：
不要多空一行，原文此处是一段

2021-01-07 05:22 UTC, Leibnizhu requested changes

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +它用来追踪故障，当失败次数达到阈值时触发熔断，并且可选择性提供失败回调，以保证服务可用或长时间等待。
```suggestion
它用来追踪故障，当失败次数达到阈值时 _触发熔断_ ，并且可选择性提供失败回调，以保证服务可用或长时间等待。
```
另外 “以保证服务可用或长时间等待” 这句话从哪来的？

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 使用 `link:../../apidocs/io/vertx/core/Future.html[Future]` 时失败
```suggestion
* 在 `link:../../apidocs/io/vertx/core/Future.html[Future]` 内记录的失败
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 没有完成的``Future``,例如:超时.
```suggestion
* 没有完成的 `Future` （即超时）。
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +熔断器要旨是保护 Vert.x 的 非阻塞 和 异步 的行为，以便受益于Vert.x 执行模型。
```suggestion
熔断器要旨是保障其操作是非阻塞且异步的，以便受益于Vert.x 执行模型。
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +使用Vert.x Circuit Breaker之前，你必须在你得项目当中添加依赖。
```suggestion
使用Vert.x Circuit Breaker之前，必须在项目当中添加以下 _依赖_ ：
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +为了使用熔断器我们需要以下的步骤：
```suggestion
使用熔断器需要按以下步骤进行：
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +**重要！！！** 熔断器应该是稳定的单例，而不是每次使用就重新创建它。
漏了 ：“It is recommended to store the circuit breaker instance in a field.” 没翻译

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +执行结果以 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象返回,其 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象,封装了成功结果集或失败结果集
原文是接收 Future 参数，但看代码好象是返回Future，这块我没用过，确认下吧

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 调用 `execute` 方法时,返回 link:../../apidocs/io/vertx/core/Future.html[Future]`
```suggestion
* 调用 `execute` 方法时,返回 `link:../../apidocs/io/vertx/core/Future.html[Future]`
```

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +每当熔断器熔断的时候,都会调用失败回调(fallback), 或者调用
“或者调用” =》“也可以调用"

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +`link:../../apidocs/io/vertx/circuitbreaker/CircuitBreakerOptions.html#isFallbackOnFailure--[isFallbackOnFailure]` 方法用于开启(关闭)失败回调.
删掉 ”用于“

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +设置重试次数,如果你设置大于0的数值,在失败的情况下,会重试到该数值，如果在最后一次执行得到正确的结果，
```suggestion
设置重试次数。如果设置了大于0的数值,在最终失败前最多会重试设定的次数。如果在最后一次执行得到正确的结果，
```
虽然这样还是不太通顺……自己多读几次吧…………

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +*注意* 如果你设置最大重试次数 `maxRetries` 为2, 那么你得代码在失败的情况将会执行3次，三次分别为初次请求，2次重试次数。
删掉最后的 “次数”

2021-01-07 05:22 UTC, Leibnizhu commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 当操作超时的时候,会抛出`link:../../apidocs/io/vertx/circuitbreaker/TimeoutException.html[TimeoutException]`
```suggestion
* 当操作超时的时候,会抛出 `link:../../apidocs/io/vertx/circuitbreaker/TimeoutException.html[TimeoutException]`
```

2021-01-10 06:45 UTC, PassXml commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +设置重试次数,如果你设置大于0的数值,在失败的情况下,会重试到该数值，如果在最后一次执行得到正确的结果，
如果你设置大于0的数值，失败的情况下会重试，直到重试次数等于该数值，如果其中一次重试成功，
那么会跳过剩下的重试。


这样会不会好点呢

2021-01-10 06:48 UTC, PassXml commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +它用来追踪故障，当失败次数达到阈值时触发熔断，并且可选择性提供失败回调，以保证服务可用或长时间等待。
这个我抄作业复制的。。。我和英文版在核对下一下吧

2021-01-26 14:24 UTC, okou19900722 requested changes

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
```suggestion
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 使用熔断器
```suggestion
[[_using_the_circuit_breaker]]
== 使用熔断器
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 使用熔断器
```suggestion
[[_using_the_circuit_breaker]]
== 使用熔断器
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 创建一个熔断器，并配置成你所需要的超时，最大故障次数等参数
```suggestion
1. 创建一个熔断器，并配置成你所需要的超时，最大故障次数等参数
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 使用熔断器执行代码
```suggestion
2. 使用熔断器执行代码
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +
```suggestion
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 重试（Retries）
```suggestion
[[_retries]]
== 重试（Retries）
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 回调（Callbacks）
```suggestion
[[_callbacks]]
== 回调（Callbacks）
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 事件总线通知
```suggestion
[[_event_bus_notification]]
== 事件总线通知
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 半开状态（half-open）
```suggestion
[[_the_half_open_state]]
== 半开状态（half-open）
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 异常
```suggestion
[[_reported_exceptions]]
== 异常
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 将熔断器指标推送到Hystrix看板（Dashboard）
```suggestion
[[_pushing_circuit_breaker_metrics_to_the_hystrix_dashboard]]
== 将熔断器指标推送到Hystrix看板（Dashboard）
```

2021-01-26 14:24 UTC, okou19900722 commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +== 使用 Netflix Hystrix
```suggestion
[[_using_netflix_hystrix]]
== 使用 Netflix Hystrix
```

2021-01-27 07:05 UTC, okou19900722 approved these changes

2021-01-29 03:12 UTC, PassXml commented
调整之后...大家再看下

2021-01-30 02:30 UTC, chengenzhao approved these changes

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 没有完成的``Future``（即超时）.
```suggestion
* 没有完成的 `Future`（即超时）.
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* Maven (在 `pom.xml` 文件中):
```suggestion
* Maven（在您的 `pom.xml` 文件中）：
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* Gradle (在 `build.gradle` 文件中):
```suggestion
* Gradle（在您的 `build.gradle` 文件中）：
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +  // 如果future在这里被标记为失败，熔断器将自增失败数
```suggestion
  // 如果该 promise 在这里被标记为失败，熔断器将自增失败数
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +执行结果以 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象返回,其 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象,封装了成功结果集或失败结果集
```suggestion
execute代码块接收 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象参数，以标识该操作以及结果的失败或成功。
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +**重要！！！** 熔断器应该是稳定的单例，而不是每次使用就重新创建它。
```suggestion
**重要！！！** 熔断器应该是稳定的单例，而不是每次使用就重新创建它。推荐将该单例存放在某个领域中。
```

2021-01-30 02:30 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
>  // Store the circuit breaker in a field and access it as follows
```suggestion
// 将熔断器存放在某个领域中并像如下方式使用
```

2021-01-30 02:35 UTC, chengenzhao approved these changes

2021-01-30 02:35 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +你可以这样执行它：
```suggestion
您可以这样执行之：
```

2021-01-30 02:35 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +*注意*：这些指标量是由 Vert.x Web Handler 使用 Event Bus 事件通知收集的。
```suggestion
*注意*：这些指标量是由 Vert.x Web Handler 使用 Event Bus 事件通知收集。
```

2021-01-30 02:35 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +如果你不想使用默认的通知地址，请在创建的时候设置。
```suggestion
如您不想使用默认的通知地址，请在创建的时候设置。
```

2021-01-30 02:35 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* `node` : 节点标识 (如果事件总线运行在单节模式，那么该值为：`local`)
```suggestion
* `node` : 节点标识 (如果事件总线并非运行在集群模式中，那么该值为：`local`)
```

2021-01-30 02:35 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* `state` : 熔断器最新的状态 (`OPEN`, `CLOSED`, `HALF_OPEN`)
```suggestion
* `state` : 熔断器最新的状态（`OPEN`, `CLOSED`, `HALF_OPEN`）
```

2021-01-30 02:37 UTC, chengenzhao approved these changes

2021-01-30 02:37 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +execute代码块接收 `link:../../apidocs/io/vertx/core/Future.html[Future]` 对象参数，以标识该操作以及结果的失败或成功。
```suggestion
execute代码块接收 `link:../../apidocs/io/vertx/core/Future.html[Future]` 
对象参数，以标识该操作以及结果的失败或成功。
```

2021-01-30 02:37 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +例如:在下面的例子中，对应的结果就是REST调用的输出：
```suggestion
例如:在下面的例子中，
对应的结果就是REST调用的输出：
```

2021-01-30 02:40 UTC, chengenzhao approved these changes

2021-01-30 02:40 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +使用Vert.x Circuit Breaker之前，你必须在你得项目当中添加 _依赖_ :
```suggestion
使用Vert.x Circuit Breaker之前，
你必须在你得项目当中添加如下  _依赖_ ：
```

2021-01-30 02:40 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +设置重试次数,如果你设置大于0的数值，失败的情况下会重试，直到重试次数等于该数值，如果其中一次重试成功，
```suggestion
设置重试次数,如设置大于0的数值，失败的情况下会重试，直到重试次数等于该数值，如果其中一次重试成功，
```

2021-01-30 02:40 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +*注意* 如果你设置最大重试次数 `maxRetries` 为2, 那么你得代码在失败的情况将会执行3次，三次分别为初次请求，2次重试。
```suggestion
*注意* 如您设置最大重试次数 `maxRetries` 为 2，那么您的代码在失败的情况将会执行3次，分别为初次请求，
以及 2 次重试。
```

2021-01-30 02:43 UTC, chengenzhao approved these changes

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +`link:../../apidocs/io/vertx/circuitbreaker/CircuitBreakerOptions.html#isFallbackOnFailure--[isFallbackOnFailure]` 方法开启(关闭)失败回调.
```suggestion
`link:../../apidocs/io/vertx/circuitbreaker/CircuitBreakerOptions.html#isFallbackOnFailure--[isFallbackOnFailure]` 方法开启(关闭)失败回调。
```

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +调用失败回调的时候,其结果会以 `link:../../apidocs/java/lang/Throwable.html[Throwable]` 为参数返回预期对象.
```suggestion
调用失败回调的时候,其结果会以 `link:../../apidocs/java/lang/Throwable.html[Throwable]` 为参数返回预期对象。
```

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +通过 `link:../../apidocs/io/vertx/circuitbreaker/CircuitBreaker.html[CircuitBreaker]` 设置全局的失败回调方法:
```suggestion
通过 `link:../../apidocs/io/vertx/circuitbreaker/CircuitBreaker.html[CircuitBreaker]` 设置全局的失败回调方法：
```

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +在默认情况下超时时间(timeout)和重试次数(retries)为0,那么将会无延时的一直请求下去,这会导致调用服务负载增加
```suggestion
在默认情况下超时时间（timeout）和重试次数（retries）为0，那么将会无延时的一直请求下去,这会导致调用服务负载增加
```

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +首先，您需要将Hystrix添加到你的依赖中。详细信息请参阅Hystrix页面。然后，您需要使用 Command 隔离“受保护的”调用。
```suggestion
首先，您需要将Hystrix添加到你的依赖中。
详细信息请参阅Hystrix页面。然后，您需要使用 Command 隔离“受保护的”调用。
```

2021-01-30 02:43 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +但是，代码执行是阻塞的，必须使用 `executeBlocking` 方法去执行，或者在Worker Verticle中调用：
```suggestion
但是，代码执行是阻塞的，必须使用 `executeBlocking` 方法去执行，
或在Worker Verticle中调用：
```

2021-01-30 03:04 UTC, chengenzhao approved these changes

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +调用失败回调的时候,其结果会以 `link:../../apidocs/java/lang/Throwable.html[Throwable]` 为参数返回预期对象。
```suggestion
当回退函数被成功设置之后，回退函数将会接收 `link:../../apidocs/java/lang/Throwable.html[Throwable]` 对象为参数并返回预期类型。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +每当熔断器熔断的时候,都会调用失败回调(fallback), 也可以调用
```suggestion
每当熔断器熔断的时候,都会调用失败回退（fallback），也可以调用
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +用于设置重试策略。 该方法接收一个Function<Integer,Long>的函数体(传入参数为重试次数,返回具体超时时间,单位:毫秒),
```suggestion
用于设置重试策略。该方法接收一个Function<Integer,Long>的函数体（传入参数为重试次数，返回具体超时时间，单位：毫秒），
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +允许用户定制更加复杂的延时策略(例如:带抖动的延时补偿)
```suggestion
允许用户定制更加复杂的延时策略，例如：带抖动的延时补偿。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +你可以配置熔断开路(OPEN)/闭路(CLOSE)时回调。
```suggestion
您可以配置熔断开启或关闭时的回调函数：
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 当操作超时的时候,会抛出 `link:../../apidocs/io/vertx/circuitbreaker/TimeoutException.html[TimeoutException]`
```suggestion
* 当操作超时，会抛出 `link:../../apidocs/io/vertx/circuitbreaker/TimeoutException.html[TimeoutException]`
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +* 当熔断器开路(OPEN)的情况,会抛出 `link:../../apidocs/io/vertx/circuitbreaker/OpenCircuitException.html[OpenCircuitException]` 异常
```suggestion
* 当熔断器开启时，会抛出 `link:../../apidocs/io/vertx/circuitbreaker/OpenCircuitException.html[OpenCircuitException]` 
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +        .setFallbackOnFailure(true) // 失败后是否调用回调
```suggestion
        .setFallbackOnFailure(true) // 失败后是否调用回退函数（fallback）
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +        .setResetTimeout(10000) // 从，状态重置时间
```suggestion
        .setResetTimeout(10000) // 在开启状态下，尝试重试之前所需时间
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +也可以增加一个可选参数,用于熔断时进行失败回调(fallback):
```suggestion
也可以增加一个可选参数,用于熔断时进行失败回退（fallback）:
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +异常状态:
```suggestion
回退函数将会接收到：
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +这个 Vert.x Web Handler 提供
```suggestion
该 Vert.x Web 处理器所提供：
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +但是，代码执行是阻塞的，必须使用 `executeBlocking` 方法去执行，
```suggestion
但是，代码执行是阻塞的，所以需要使用 `executeBlocking` 方法执行，
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +Circuit Breaker 是Vert.x熔断模式的实现。
```suggestion
Circuit Breaker 是Vert.x 熔断 _模式_ 的实现。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +它用来追踪故障，当失败次数达到阈值时触发熔断，并且可选择性提供失败回调。
```suggestion
它用来追踪故障，当失败次数达到阈值时 _触发熔断_ ，并提供可选择的失败回退。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +熔断器要旨是保障其操作是非阻塞且异步的，以便受益于Vert.x 执行模型。
```suggestion
熔断器要旨是保障其操作是非阻塞且异步的，
以受益于Vert.x 执行模型。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +`link:../../apidocs/io/vertx/circuitbreaker/CircuitBreakerOptions.html#isFallbackOnFailure--[isFallbackOnFailure]` 方法开启(关闭)失败回调。
```suggestion
`link:../../apidocs/io/vertx/circuitbreaker/CircuitBreakerOptions.html#isFallbackOnFailure--[isFallbackOnFailure]` 方法开启失败回退。
```

2021-01-30 03:04 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +通过 `link:../../apidocs/io/vertx/circuitbreaker/CircuitBreaker.html[CircuitBreaker]` 设置全局的失败回调方法：
```suggestion
通过 `link:../../apidocs/io/vertx/circuitbreaker/CircuitBreaker.html[CircuitBreaker]` 直接设置失败回退方法：
```

2021-01-30 03:09 UTC, chengenzhao approved these changes

2021-01-30 03:09 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +你必须在你得项目当中添加如下  _依赖_ ：
```suggestion
你必须在你的项目中添加如下  _依赖_ ：
```

2021-01-30 03:14 UTC, chengenzhao approved these changes

2021-01-30 03:14 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +在默认情况下超时时间（timeout）和重试次数（retries）为0，那么将会无延时的一直请求下去,这会导致调用服务负载增加
```suggestion
在默认情况下超时时间（timeout）和重试次数（retries）为0，那么将会无延时地一直请求下去，这会导致调用服务负载增加
```

2021-01-30 03:14 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +导致服务恢复时间延长。所以为了减少这种情况设置延时和重试次数。
```suggestion
并导致服务恢复时间延长。所以为了减少这种情况，建议设置延时以及重试次数。
```

2021-01-30 03:15 UTC, chengenzhao commented on docs/translation/vertx-circuit-breaker/java/index.adoc
> +[[_using_the_vert_x_circuit_breaker]]
```suggestion
```

2021-01-30 03:19 UTC, merged