translation of Hazelcast
vertx-china/vertx-china.github.io pull request #82
Opened 2021-01-09 05:36 UTC by Leibnizhu

2021-01-10 07:32 UTC, Leibnizhu commented on docs/translation/vertx-hazelcast/java/index.adoc
> +<2> 实际创建的 Pod 数量 小于等于（期望的 Pod 数量 + maxSurge）
这里不知道有什么比较好的翻译

2021-01-12 01:20 UTC, okou19900722 requested changes

2021-01-12 01:20 UTC, okou19900722 commented on docs/translation/vertx-hazelcast/java/index.adoc
> +[[_Cluster_administration]]
```suggestion
[[_cluster_administration]]
```

2021-01-12 01:51 UTC, Leibnizhu commented on docs/translation/vertx-hazelcast/java/index.adoc
> +<2> 实际创建的 Pod 数量 小于等于（期望的 Pod 数量 + maxSurge）
@chengenzhao @fofofofoxier dalao们路过想想

2021-01-12 03:19 UTC, okou19900722 approved these changes

2021-01-12 09:34 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +<2> 实际创建的 Pod 数量 小于等于（期望的 Pod 数量 + maxSurge）
我感觉这是不符合英语语法的病句，没有谓语动词

2021-01-12 09:39 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +<2> 实际创建的 Pod 数量 小于等于（期望的 Pod 数量 + maxSurge）
1）在升级过程中可能不可用的最大 pods 数
2）允许超过预期创建数量的最大 pods 数

2021-01-13 08:37 UTC, chengenzhao requested changes

2021-01-13 08:37 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +* 在升级过程中yunxu 不可用的最大 Pod 数
这里有拼音

2021-01-13 09:42 UTC, chengenzhao approved these changes

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +IMPORTANT: 要确保 Hazelcast 集群 先于 Vert.x 集群启动，后于 Vert.x 集群关闭。 同时需要禁用 `shutdown hook` （参考上述的 xml 配置，或通过系统变量来实现）。
后于 Vert.x 集群关闭。在这里换行就可以保证跟原来行数一致

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +有关如何配置不同的发现方式，请查阅 Hazelcast 文档。
关于如何配置不同的发现方式，请查阅 Hazelcast 文档。

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +通过编程的方式显式配置 Vert.x 集群管理器， 比如：
通过编程的方式显式配置 Vert.x 集群管理器，例如：

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +NOTE: 如果你使用了其他版本的 Hazelcast core 依赖，请确保与 Kubernetes discovery 插件的兼容性.
NOTE: 如果你使用了其他版本的 Hazelcast core 依赖，请确保兼容 Kubernetes discovery 插件。

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +更多关于配置的详情请参考 https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes 插件页面].
更多关于配置的详情请参考 https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes 插件页面]。

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +==== 使用 Lite Members
==== 使用 Lite 成员

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +IMPORTANT: 您必须事先启动外部数据节点，因为 Hazelcast 不会只使用 _Lite Members_ 节点创建集群。
IMPORTANT: 您必须事先启动外部数据节点，因为 Hazelcast 不会只使用 _Lite 成员_ 节点创建集群。

2021-01-13 09:42 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +可以在XML配置中将Vert.x节点标记为 _Lite Members_ 节点：
可以在XML配置中将Vert.x节点标记为 _Lite 成员_ 节点：

2021-01-13 10:08 UTC, chengenzhao commented on docs/translation/vertx-hazelcast/java/index.adoc
> +有关如何配置不同的发现方式，请查阅 Hazelcast 文档。
```suggestion
关于如何配置不同的发现方式，请查阅 Hazelcast 文档。
```

2021-01-13 10:11 UTC, Leibnizhu commented on docs/translation/vertx-hazelcast/java/index.adoc
> +IMPORTANT: 要确保 Hazelcast 集群 先于 Vert.x 集群启动，后于 Vert.x 集群关闭。 同时需要禁用 `shutdown hook` （参考上述的 xml 配置，或通过系统变量来实现）。
这里又被idea吃了。

2021-01-14 06:20 UTC, closed without merging