【web】守护连接桥部分翻译和校对
vertx-china/vertx-china.github.io pull request #93
Opened 2021-01-22 08:22 UTC by chengenzhao

每天翻译一丢丢，生活也多彩一丢丢

2021-01-22 08:23 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +// 让我们定义 客户x端 -> 客户端 发送消息匹配规则
```suggestion
// 让我们定义 客户端 -> 客户端 发送消息匹配规则
```

2021-01-22 08:37 UTC, okou19900722 requested changes

2021-01-22 08:37 UTC, okou19900722 commented on docs/translation/vertx-web/java/index.adoc
> +// 允许客户端向地址 `demo.orderMgr` 发送
```suggestion
// 允许客户端向地址 `demo.persistor` 发送
```

2021-01-22 09:04 UTC, okou19900722 approved these changes

2021-01-25 13:08 UTC, fofofofoxier approved these changes

2021-01-25 13:08 UTC, fofofofoxier commented on docs/translation/vertx-web/java/index.adoc
> +为了解决这个问题，SockJS 默认会拒绝所有的消息。
SockJs -> SockJs连接桥

2021-01-25 22:00 UTC, chengenzhao commented on docs/translation/vertx-web/java/index.adoc
> +为了解决这个问题，SockJS 默认会拒绝所有的消息。
```suggestion
为了解决这个问题，SockJs连接桥默认会拒绝所有的消息。
```

2021-01-25 22:00 UTC, merged