fix #64 ,translation of vertx-web-api-service
vertx-china/vertx-china.github.io pull request #94
Opened 2021-01-25 12:41 UTC by fofofofoxier

translation of vertx-web-api-service

2021-01-26 08:45 UTC, chengenzhao requested changes
你 需要统一修改为 您

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +Vert.x Web API 服务通过事件总线帮助你处理HTTP请求
```suggestion
Vert.x Web API 服务通过事件总线帮您处理HTTP请求
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +事件总线提供了一些重要特性，例如：负载均衡、通过不同Vert.x实例分发请求
```suggestion
事件总线提供了一些重要特性，例如：负载均衡、通过不同Vert.x实例分发请求。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +我们建议您查看 https://vertx.io/docs/vertx-core/java/#event_bus[Event Bus documentation] 来了解更多信息
```suggestion
我们建议您查看 https://vertx.io/docs/vertx-core/java/#event_bus[Event Bus documentation] 来了解更多信息。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +这个模块提供给你创建Web API 服务的能力，即一个事件总线消息消费者(基于与 https://vertx.io/docs/vertx-service-proxy/java/[Vert.x service proxy] 同样的概念 )
```suggestion
这个模块提供给您以创建Web API 服务的能力，即一个基于与 https://vertx.io/docs/vertx-service-proxy/java/[Vert.x service proxy] 同样的概念的事件总线消息消费者。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +* Maven (在你的 `pom.xml` 文件):
```suggestion
* Maven（在您的 `pom.xml` 文件）：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +* Gradle < 5 (在你的 `build.gradle` 文件):
```suggestion
* Gradle < 5（在您的 `build.gradle` 文件）：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +* Gradle >= 5 (在你的 `build.gradle` 文件):
```suggestion
* Gradle >= 5（在您的 `build.gradle` 文件）：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +你需要引入 `vertx-codegen` 来从被注解修饰的接口中生成代码。
```suggestion
您需要引入 `vertx-codegen` 以从被注解修饰的接口中生成代码。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +如果你只需要 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` ，那么你不需要 `vertx-codegen`。
```suggestion
如果您只需要 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` ，那么不需要 `vertx-codegen`。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +如果你希望用不同语言来调用接口，那么你需要添加 _语言_ 依赖，譬如：
```suggestion
如果您希望用不同语言来调用接口，那么需要添加 _语言_ 依赖，譬如：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +为groovy语言添加 `vertx-lang-groovy` 依赖.
```suggestion
为groovy语言添加 `vertx-lang-groovy` 依赖。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +你可以用 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 来代理发送到事件总线的请求。
```suggestion
您可以用 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 来代理发送到事件总线的请求。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +您也可以定义 `link:../../apidocs/io/vertx/core/eventbus/DeliveryOptions.html[DeliveryOptions]` ，这个option会被用在每次通过事件总线发送消息的时候：
```suggestion
您也可以定义 `link:../../apidocs/io/vertx/core/eventbus/DeliveryOptions.html[DeliveryOptions]` ，每次通过事件总线发送消息的时候会使用该选项：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +IMPORTANT: 在挂载 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 的时候，您 *必须* 同时挂载一个 `link:../../apidocs/io/vertx/ext/web/validation/ValidationHand
```suggestion
IMPORTANT: 在挂载 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 的时候，您 *必须* 同时挂载一个 `link:../../apidocs/io/vertx/ext/web/validation/ValidationHandler.html[ValidationHandler]` ，该验证处理器提取了请求中的参数。否则，不会发送任何请求参数。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +现在我们可以构建用于处理那些终端（endpoint）的 *TransactionService* 接口。对于各个终端 您在构建 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 的时候 需要写一个方法，这个方法名称与指定的 `action`
```suggestion
现在我们可以构建用于处理那些终端（endpoint）的 *TransactionService* 接口。对于各个终端您在构建 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html[RouteToEBServiceHandler]` 时需要写入一个方法，该方法名与指定的 `action` 相关联。
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +当你从 `TransactionService#getTransactionsList` 方法中接收到一个请求，自动生成的服务处理器会从 `link:../../apidocs/io/vertx/ext/web/api/service/ServiceRequest.html[ServiceRequest]` 自动解析出 `from` 和 `to` 参数（如果存在）
```suggestion
当您从 `TransactionService#getTransactionsList` 方法中接收到一个请求，自动生成的服务处理器会从 `link:../../apidocs/io/vertx/ext/web/api/service/ServiceRequest.html[ServiceRequest]` 自动解析出 `from` 和 `to` 参数（如果存在）
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +服务处理器也有自动转换 `JsonObject` 为Vert.x 数据对象的能力，例如，如果你有一个满足上述json schema的 `Transaction` 数据对象，你可以像如下重写 `putTransaction` 方法签名：
```suggestion
服务处理器也有自动转换 `JsonObject` 为Vert.x 数据对象的能力，例如，如您有一个满足上述json schema的 `Transaction` 数据对象，可以像如下方式重写 `putTransaction` 签名：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +你也可以用 `link:../../apidocs/io/vertx/ext/web/validation/RequestParameter.html[RequestParameter]` 来提取参数，如下：
```suggestion
您亦可使用 `link:../../apidocs/io/vertx/ext/web/validation/RequestParameter.html[RequestParameter]` 来提取参数，例如：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +或者当请求失败时：
```suggestion
或当请求失败时：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +`ServiceRequest` 是一个 _可序列化_ 的 `RoutingContext` ，但是 它并不包含 `RoutingContext` 的所有数据。它将如下数据转送到你的服务：
```suggestion
`ServiceRequest` 是一个 _可序列化_ 的 `RoutingContext` ，但是 它并不包含 `RoutingContext` 的所有数据。它将如下数据转送到您的服务：
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +你可以用 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html#extraPayloadMapper-java.util.function.Function-[extraPayloadMapper]` 配置一个lambda表达式来构建额外的 payload
```suggestion
您可使用 `link:../../apidocs/io/vertx/ext/web/api/service/RouteToEBServiceHandler.html#extraPayloadMapper-java.util.function.Function-[extraPayloadMapper]` 配置一个lambda表达式来构建额外的 payload
```

2021-01-26 08:45 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +* 作为payload的请求体。如果你不设置payload或者设置为null，则不会发送响应体。
```suggestion
* 作为payload的请求体。如您不设置payload或者设置为null，则不会发送响应体。
```

2021-01-26 08:58 UTC, okou19900722 requested changes

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +== 使用Vert.x API服务
```suggestion
[[_using_vert_x_api_service]]
== 使用Vert.x API服务
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +== 代理一个HTTP请求 到一个Web API服务
```suggestion
[[_proxy_an_http_request_to_a_web_api_service]]
== 代理一个HTTP请求 到一个Web API服务
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +== 定义您的Web API 服务接口
```suggestion
[[_define_your_web_api_service_interface]]
== 定义您的Web API 服务接口
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +== 实现您自己的Web API服务
```suggestion
[[_implement_your_web_api_service]]
== 实现您自己的Web API服务
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +=== `ServiceRequest` 数据对象
```suggestion
[[_the_servicerequest_data_object]]
=== `ServiceRequest` 数据对象
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +=== `ServiceResponse` 数据对象
```suggestion
[[_the_serviceresponse_data_object]]
=== `ServiceResponse` 数据对象
```

2021-01-26 08:58 UTC, okou19900722 commented on docs/translation/vertx-web-api-service/java/index.adoc
> +== 暴露您的Web API 服务
```suggestion
[[_expose_your_web_api_service]]
== 暴露您的Web API 服务
```

2021-01-27 07:00 UTC, okou19900722 approved these changes

2021-01-28 13:09 UTC, chengenzhao approved these changes

2021-01-28 13:09 UTC, chengenzhao commented on docs/translation/vertx-web-api-service/java/index.adoc
> +* Gradle < 5 (在你的 `build.gradle` 文件):
```suggestion
* Gradle < 5 （在您的 `build.gradle` 文件）：
```

2021-01-28 15:25 UTC, chengenzhao commented
可以merge了

2021-01-28 16:01 UTC, merged