Mysql client translation
vertx-china/vertx-china.github.io pull request #97
Opened 2021-01-28 03:15 UTC by sfiloveyou

Mysql client translation

2021-01-28 05:03 UTC, Leibnizhu requested changes
看了一部分，感觉很机翻，是不是自己没有读过？建议先自己review一遍，很多地方不符合日常中文习惯。

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/cursor.adoc
> +默认情况下，预处理查询执行将获取所有行，您可以使用 `link:../../apidocs/io/vertx/sqlclient/Cursor.html[Cursor]` 控制您想读取的行数量：
```suggestion
默认情况下，执行预处理查询将获取所有行，您可以使用 `link:../../apidocs/io/vertx/sqlclient/Cursor.html[Cursor]` 控制想读取的行数：
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/cursor.adoc
> +游标过早释放时应将其关闭：
```suggestion
游标提前释放时应将其关闭：
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/cursor.adoc
> +当这些行已传递给处理程序时，该流将批量读取50行并将其流化。读取新一批的50行，依此类推。
```suggestion
当这些行已传递给处理程序时，该流将批量读取 `50` 行并将其流化。
然后读取新一批的 `50` 行数据，依此类推。
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/cursor.adoc
> +流可以恢复或暂停，已加载的行将保留在内存中，直到被送达，游标将停止迭代。
```suggestion
流可以恢复或暂停，已加载的行将保留在内存中，直到被送达，
此时游标将停止迭代。
```

“被送达”自己改下？

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +响应式 MySQL 客户端是具有简单易懂的 API，专注于可扩展性和低开销的MySQL的客户端。
```suggestion
响应式 MySQL 客户端具有简单易懂的 API，专注于可扩展性和低开销。
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 游标支持
```suggestion
* 支持游标
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 行流
```suggestion
* 流式行处理
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 直接内存到对象，无需不必要的拷贝
```suggestion
* 支持对象存储在直接内存，避免不必要的拷贝
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 存储过程支持
```suggestion
* 支持存储过程
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* TLS/SSL 支持
```suggestion
* 支持 TLS/SSL
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 丰富的排序和字符集支持
```suggestion
* 丰富的字符排序（collation）和字符集支持
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +== 使用
```suggestion
== 使用方法
```

2021-01-28 05:03 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +若要使用响应式 MySQL 客户端，请将以下依赖项添加到构建描述符的 _dependencies_ 部分
```suggestion
使用响应式 MySQL 客户端，需要将以下依赖项添加到项目构建工具的 _依赖_ 配置中：
```

2021-01-28 05:07 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +* 行流
读到这里我深切的怀疑是机翻而且没有校对过……“行流”估计没几个人能看懂，我搜了下似乎也这个专有名词，但是在google translate 找到了： https://translate.google.cn/?sl=en&tl=zh-CN&text=Row%20streaming&op=translate

2021-01-29 05:39 UTC, Leibnizhu requested changes
中午看了一点点，晚点再看

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +带连接池的客户端使用连接池，任何操作都将借用连接池中的连接来执行该操作并释放到连接池中。
```suggestion
带连接池的客户端使用连接池，任何操作都将借用连接池中的连接来执行该操作，
并将连接释放回连接池中。
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +当您需要在同一连接上执行多个操作时，您需要使用 `link:../../apidocs/io/vertx/mysqlclient/MySQLConnection.html[connection]` 客户端 。
```suggestion
当您需要在同一连接上执行多个操作时，您需要使用 
`link:../../apidocs/io/vertx/mysqlclient/MySQLConnection.html[connection]` 客户端 。
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +由于 JVM 不支持域套接字，因此首先必须向项目添加native transport扩展。
```suggestion
由于 JVM 不支持域套接字，因此首先必须向项目添加本地传输（native transport）扩展。
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +NOTE: ARM64 的原生 `epoll` 支持也可以与分类器 `linux-aarch64` 一起添加。
这里真的是指“分类器”吗？？？

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +NOTE: 如果您的团队中有 Mac 用户，在 `osx-x86_64` 上添加 `netty-transport-native-kqueue` 分类器。
同上面的疑问

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +然后在 `link:../../apidocs/io/vertx/mysqlclient/MySQLConnectOptions.html#setHost-java.lang.String-[MySQLConnectOptions#setHost]` 中设置域套接字的路径：
```suggestion
然后通过 `link:../../apidocs/io/vertx/mysqlclient/MySQLConnectOptions.html#setHost-java.lang.String-[MySQLConnectOptions#setHost]` 设置域套接字的路径：
```  
或  
```suggestion
然后在 `link:../../apidocs/io/vertx/mysqlclient/MySQLConnectOptions.html#setHost-java.lang.String-[MySQLConnectOptions#setHost]` 的参数中设置域套接字的路径：
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关native transports的详细信息，请参阅 [Vert.x documentation](https://vertx.io/docs/vertx-core/java/#_native_transports)。
```suggestion
有关 native transport 的详细信息，请参阅 [Vert.x documentation](https://vertx.io/docs/vertx-core/java/#_native_transports)。
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以为一个连接指定字符集，例如
```suggestion
您可以为数据库连接指定字符集，例如
```

2021-01-29 05:39 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +响应式 MySQL 客户端将 `utf8mb4` 作为默认字符集。字符串值，像密码和错误消息等总是使用 `UTF-8` 字符集解码。
```suggestion
响应式 MySQL 客户端的默认字符集是 `utf8mb4` 。字符串值，如密码和错误消息等，总是使用 `UTF-8` 字符集解码。
```

2021-01-30 13:47 UTC, Leibnizhu requested changes
没看完，真的建议自己先看一遍，很多地方不通顺

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`characterEncoding` 选项用于确定哪个 Java 字符集将用于编码字符串值，例如查询字符串和参数值默认使用 `UTF-8` 字符集，如果它们被设置成 `null` ，客户端将使用 Java 的默认字符集来代替。
```suggestion
`characterEncoding` 选项用于设置字符串（例如查询字符串和参数值）使用的 Java 字符集，默认使用 `UTF-8` 字符集；如果设置为 `null` ，则客户端将使用 Java 的默认字符集。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +请注意，在数据对象上设置字符序将覆盖 *charset* 和 *characterEncoding* 选项。
```suggestion
请注意，在数据对象上设置字符序将覆盖 *charset* 和 *characterEncoding* 选项。

```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +请注意，在数据对象上设置字符序将覆盖 *charset* 和 *characterEncoding* 选项。
少了一个空行吧

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以执行 SQL `SHOW COLLATION;` 或 `SHOW CHARACTER SET;` 获取受服务器支持的字符序和字符集。
```suggestion
您可以执行 SQL `SHOW COLLATION;` 或 `SHOW CHARACTER SET;` 获取服务器支持的字符序和字符集。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以执行 SQL `SHOW COLLATION;` 或 `SHOW CHARACTER SET;` 获取受服务器支持的字符序和字符集。
一般中文少用动词被动态

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关 MySQL 字符集和字符序的更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/charset.html[MySQL Reference Manual]。
```suggestion
有关 MySQL 字符集和字符序的更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/charset.html[MySQL 参考手册]。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +还可以使用 `setProperties` 或 `addProperty` 方法配置连接属性。注意 `setProperties` 将覆盖默认客户端属性。
```suggestion
还可以使用 `setProperties` 或 `addProperty` 方法配置连接属性。注意 `setProperties` 将覆盖客户端的默认属性。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关连接属性的更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html[MySQL Reference Manual]。
```suggestion
有关连接属性的更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/performance-schema-connection-attribute-tables.html[MySQL 参考手册]。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/mysql-affected-rows.html[MySQL Reference Manual]
```suggestion
更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/mysql-affected-rows.html[MySQL 参考手册]
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以配置 `useAffectedRows` 选项以决定是否在连接到服务器时设置标志 `CLIENT_FOUND_ROWS`。如果 `CLIENT_FOUND_ROWS` 标志被指定，则受影响的行计数是找到的行的数量，而不是受影响的行数。
```suggestion
您可以 `useAffectedRows` 选项以决定是否在连接到服务器时设置标志 `CLIENT_FOUND_ROWS`。如果指定了 `CLIENT_FOUND_ROWS` 标志，则受影响的行计数（返回的）是查找到的行数，而不是受影响的行数。
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +==== 使用受影响的行数
这里 `useAffectedRows` 是配置名，是否要翻译？ @okou19900722

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +除了使用 `MySQLConnectOptions` 数据对象进行配置外，我们还另外为您提供了一个使用连接URI进行配置的方法：
```suggestion
除了使用 `MySQLConnectOptions` 数据对象进行配置外，我们还为您提供了另外一种使用连接URI进行配置的方法：
```

2021-01-30 13:47 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关连接字符串格式的有关更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connecting-using-uri[MySQL Reference Manual]。
```suggestion
有关连接字符串格式的有关更多信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html#connecting-using-uri[MySQL 参考手册]。
```

2021-01-30 16:52 UTC, Leibnizhu requested changes
看完了，不过后面的看的比较粗

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +目前，客户端支持连接 uri 中的以下参数关键字（关键字不区分大小写）：
```suggestion
目前，客户端支持以下的连接 uri 参数关键字（不区分大小写）：
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +如果在表中插入一条记录，则可以获得自动递增的值。
```suggestion
往表中插入一条记录后，可以获得自增值。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/getting-unique-id.html[How to Get the Unique ID for the Last Inserted Row]。
```suggestion
更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/getting-unique-id.html[如何获取最近一条插入记录的唯一ID]。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +当前客户端支持以下MySQL类型
```suggestion
当前客户端支持以下 MySQL 类型
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +在Java中，没有无符号数字值的具体表示形式，因此客户端会将无符号值转换为相关的Java类型。
```suggestion
请注意：在Java中，没有无符号数字值的具体表示形式，因此客户端会将无符号值转换为相关的Java类型。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +MySQL数据类型编码将会根据参数值推断，这是类型映射
```suggestion
MySQL 数据类型编码是根据参数值推断的。下面是具体的类型映射：
```
不过话说这里 “ MySQL data type for encoding” 我没看懂 “encoding“ 是指什么

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +在 MySQL 中 `BOOLEAN` 和 `BOOL` 数据类型是 `TINYINT(1)` 的同义词 . 零值视为假，非零值视为真。
```suggestion
在 MySQL 中 `BOOLEAN` 和 `BOOL` 数据类型是 `TINYINT(1)` 的同义词。零值视为 false，非零值视为 true。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`BOOLEAN` 数据类型值以 `java.lang.Byte` 类型存储在 `Row` 或 `Tuple` 中，你可以调用 `Row#getValue` 将其检索为
```suggestion
`BOOLEAN` 数据类型值以 `java.lang.Byte` 类型存储在 `Row` 或 `Tuple` 中，调用 `Row#getValue` 可以获取到 `java.lang.Byte` 类型的值，
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`java.lang.Boolean`
```suggestion
也可以调用 `Row#getBoolean` 获取 `java.lang.Boolean` 类型的值。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +当您想要使用一个 `BOOLEAN` 参数值执行预处理语句时，您可以简单的添加  `java.lang.Boolean` 值到参数列表中即可。
```suggestion
当您想要使用一个 `BOOLEAN` 参数值执行预处理语句时，只要简单地在参数列表中添加  `java.lang.Boolean` 值即可。
```
语病，”可以“和”即可“重复，另外”添加。。。到。。。“不符合中文习惯

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`java.lang.Boolean`
漏翻译了

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`BIT` 是 `java.lang.Long` 类型的映射, 但是Java没有无符号数值的概念, 因此，如果您要插入或更新最大值为 `BIT(64)` 的记录 , 您可以通过一些技巧将参数设置为 `-1L`.
```suggestion
`BIT` 是 `java.lang.Long` 类型的映射, 但是Java没有无符号数值的概念, 因此，如果您要插入或更新一条记录为 `BIT(64)` 的最大值 , 可以将参数设置为 `-1L` 。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +MySQL `TIME` 数据类型可用于表示一天中的时间或范围为 `-838:59:59` 到 `838:59:59` 的时间间隔。再响应式MySQL客户端， `TIME` 数据类型自然的被映射为`java.time.Duration`，但是您还可以通过 `Row#getLocalTime` 访问器以 `java.time.LocalTime` 检索它。
```suggestion
MySQL `TIME` 数据类型可用于表示一天中的时间或范围为 `-838:59:59` 到 `838:59:59` 的时间间隔。在响应式MySQL客户端， `TIME` 数据类型自然的被映射为 `java.time.Duration`，您也可以调用 `Row#getLocalTime` 获取到 `java.time.LocalTime` 类型的值。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以像下面的Java枚举一样检索ENUM列：
```suggestion
您可以将 ENUM 类型的列读取为 Java 的枚举，如以下代码：
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +我们还为您提供了一种在响应式 MySQL 客户端中处理几何数据类型的简单方法。
```suggestion
在响应式 MySQL 客户端中，我们还提供了一种处理几何数据类型的简单方法。

```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +集合类处理不能在 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]` 上保留引用，因为只有一个行用于处理整个集合。
```suggestion
集合类处理不能保留 `link:../../apidocs/io/vertx/sqlclient/Row.html[Row]` 
的引用，因为只有一个 Row 对象用于处理整个集合。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +Java `Collectors` 提供了许多有趣的预定义集合类，例如，您可以直接从行集中轻松创建一个字符串：
```suggestion
Java `Collectors` 提供了许多有趣的预定义集合类，例如，
您可以直接用 Row 中的集合轻松拼接成一个字符串：
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +您可以在查询中运行存储过程。结果将按照 https://dev.mysql.com/doc/dev/mysql-server/8.0.12/page_protocol_command_phase_sp.html[MySQL protocol] 从服务器检索，无需任何魔法。
```suggestion
您可以在查询中运行存储过程。结果将按照 https://dev.mysql.com/doc/dev/mysql-server/8.0.12/page_protocol_command_phase_sp.html[MySQL 协议] 从服务器获取，无需任何魔法。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +`LOAD DATA LOCAL INFILE '<filename>' INTO TABLE <table>;`。 更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/load-data.html[MySQL Reference Manual].
```suggestion
`LOAD DATA LOCAL INFILE '<filename>' INTO TABLE <table>;`。 更多有关信息，请参阅 https://dev.mysql.com/doc/refman/8.0/en/load-data.html[MySQL 参考手册].
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +MySQL 8.0 引入了一种名为 `caching_sha2_password` 的身份验证方法，它被用于默认的身份验证方法。
```suggestion
MySQL 8.0 引入了一种名为 `caching_sha2_password` 的身份验证方法，它是默认的身份验证方法。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +为了使用此新的身份验证方法连接到服务器，您需要使用安全连接（例如 启用 TLS/SSL）或使用 RSA 密钥对交换加密密码，以避免密码泄漏。RSA 密钥对在通信过程中会自动交换，但服务器 RSA 公钥可能会在这个过程中被黑客攻击，因为它通过不安全的连接传输。因此，如果您使用不安全的连接，并且希望避免暴露服务器 RSA 公钥的风险，可以这样设置服务器 RSA 公钥：
```suggestion
为了使用此新的身份验证方法连接到服务器，您需要使用安全连接（例如 启用 TLS/SSL）或使用 RSA 密钥对交换加密密码，以避免密码泄漏。RSA 密钥对在通信过程中会自动交换，但服务器 RSA 公钥可能会在这个过程中被黑客攻击，因为它通过不安全的连接传输。
因此，如果您使用不安全的连接，并且希望避免暴露服务器 RSA 公钥的风险，可以这样设置服务器 RSA 公钥：
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关 `caching_sha2_password` 身份验证方法的更多信息，请参见 https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html[MySQL Reference Manual].
```suggestion
有关 `caching_sha2_password` 身份验证方法的更多信息，请参见 https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html[MySQL 参考手册].
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +配置客户端使用SSL连接, 您可以像 Vert.x `NetClient` 一样配置 `link:../../apidocs/io/vertx/mysqlclient/MySQLConnectOptions.html[MySQLConnectOptions]` 。
```suggestion
配置客户端使用SSL连接, 您可以像 Vert.x `NetClient` 一样配置
`link:../../apidocs/io/vertx/mysqlclient/MySQLConnectOptions.html[MySQLConnectOptions]` 。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +所有 https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode[SSL modes] 都被支持并且您能够配置 `sslmode`. 客户端默认在 `DISABLED` SSL 模式。
```suggestion
响应式 MySQL 客户端 支持所有 https://dev.mysql.com/doc/refman/8.0/en/connection-options.html#option_general_ssl-mode[SSL 模式] ，而且您能够配置 `sslmode`. 客户端默认设置为 `DISABLED` SSL 模式。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +== MySQL 和 MariaDB 版本支持矩阵
```suggestion
== MySQL 和 MariaDB 版本支持情况
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +| 版本 | 支持 | 版本 | 支持
```suggestion
| 版本 | 是否支持 | 版本 | 是否支持
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +- 重置连接实用程序命令在 MySQL 5.5、5.6 和 MariaDB 10.1 中不起作用
```suggestion
- 重置连接实用程序命令在 MySQL 5.5、5.6 和 MariaDB 10.1 中不可用
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +缓解这种情况的最佳方法是启用预处理语句缓存，因此可以重用具有相同 SQL 字符串的预处理语句，并且客户端不必为每个请求创建全新的预处理语句。执行语句后，预处理语句将自动关闭。这样，虽然无法完全消除，但达到极限的机会可以大大减少。
```suggestion
缓解这种情况的最佳方法是启用预处理语句缓存，因此可以重用具有相同 SQL 字符串的预处理语句，并且客户端不必为每个请求创建全新的预处理语句。
执行语句后，预处理语句将自动关闭。
这样，虽然无法完全消除错误，但达到极限的机会可以大大减少。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/index.adoc
> +当您要将数据批量插入到数据库中时，您可以使用 `PreparedQuery#executeBatch` ，它提供了一个简单的 API 来处理此问题。请记住，MySQL 原生不支持批处理协议，因此 API 只是语法糖，一个接一个执行预处理语句，这意味着比执行一个预处理语句插入多条带有值列表的记录，需要更多的网络往返行程。
```suggestion
当您要将数据批量插入到数据库中时，您可以使用 `PreparedQuery#executeBatch` ，它提供了一个简单的 API 来处理此问题。
请记住，MySQL 原生不支持批处理协议，因此 API 只是语法糖，一个接一个执行预处理语句，这意味着比执行一个预处理语句插入多条带有值列表的记录，需要更多的网络往返耗时。
```

2021-01-30 16:52 UTC, Leibnizhu commented on docs/translation/vertx-mysql-client/java/transactions.adoc
> +当数据库服务器报告当前事务失败时（例如，臭名昭著的 _current transaction is aborted, commands ignored until end of transaction block_），事务被回滚，并且 `link:../../apidocs/io/vertx/sqlclient/Transaction.html#completion--[completion]`
```suggestion
当数据库服务器报告当前事务失败时（例如，臭名昭著的 _current transaction is aborted, commands ignored until end of transaction block_），
事务被回滚，此时 `link:../../apidocs/io/vertx/sqlclient/Transaction.html#completion--[completion]` Future 会失败，
并返回 `link:../../apidocs/io/vertx/sqlclient/TransactionRollbackException.html[TransactionRollbackException]` 异常：
```

2021-02-01 08:39 UTC, counter2015 commented on docs/translation/vertx-mysql-client/java/index.adoc
> +NOTE: ARM64 的原生 `epoll` 支持也可以与分类器 `linux-aarch64` 一起添加。
根据上下文应该是说`maven classifier`

2021-02-01 09:22 UTC, okou19900722 commented on docs/translation/vertx-mysql-client/java/index.adoc
> +==== 使用受影响的行数
```suggestion
==== 配置 `useAffectedRows`
```
如果是配置名的话，是否可以这么翻译

2021-02-02 05:05 UTC, Leibnizhu approved these changes

2021-02-02 09:29 UTC, okou19900722 approved these changes

2021-02-02 09:29 UTC, okou19900722 commented on docs/translation/vertx-mysql-client/java/cursor.adoc
>  A stream API is also available for cursors, which can be more convenient, specially with the Rxified version.
```suggestion
```

2021-02-02 09:29 UTC, okou19900722 commented on docs/translation/vertx-mysql-client/java/index.adoc
> +有关 native transport 的详细信息，请参阅 [Vert.x 文档](https://vertx.io/docs/vertx-core/java/#_native_transports)。
```suggestion
有关 native transport 的详细信息，请参阅 https://vertx.io/docs/vertx-core/java/#_native_transports[Vert.x 文档] 。
```

2021-02-02 09:29 UTC, okou19900722 approved these changes

2021-02-02 12:05 UTC, cpdyj commented on docs/translation/vertx-mysql-client/java/index.adoc
> +请注意，在数据对象上设置字符序将覆盖 *charset* 和 *characterEncoding* 选项。
啊，完全没意识到还可以靠补空行占位，我一直傻乎乎的在标点处诡异地断行

2021-02-03 09:49 UTC, Leibnizhu approved these changes

2021-02-04 11:20 UTC, merged