Vertx tcp eventbus brige
vertx-china/vertx-china.github.io pull request #99
Opened 2021-01-28 15:09 UTC by mm0rz

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +Vert.x-tcp-eventbus-bridge 是连接 Vert.x EventBus 的 TCP bridge。要使用此项目, 请先加入以下依赖到您的 build 描述 dependencies 部分:
TCP bridge -> TCP 连接桥，不过保持原文也合理，此处仅为建议

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +Vert.x-tcp-eventbus-bridge 是连接 Vert.x EventBus 的 TCP bridge。要使用此项目, 请先加入以下依赖到您的 build 描述 dependencies 部分:
```suggestion
Vert.x-tcp-eventbus-bridge 是连接 Vert.x EventBus 的 TCP bridge。要使用此项目, 请先加入以下依赖:
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +Vert.x-tcp-eventbus-bridge 是连接 Vert.x EventBus 的 TCP bridge。要使用此项目, 请先加入以下依赖到您的 build 描述 dependencies 部分:
意思明确即可，此处没有必要按语法完整翻译

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +因为整个 HTTP WebSockets 已经替换为纯TCP套接字, 所以 TCP bridge 与 SockJS bridge 的主要使用场景是资源受限的轻量化应用程序。
+ _versus_ 即 VS，有对比的意思，个人感觉应该强调一下对比关系： TCP bridge 相比于 SockJS bridge，其使用场景blabla
+ "资源受限"是否考虑换成"有限资源"

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +即使是对于没有严格资源限制的应用程序, 协议仍然有用: 该协议足够简单, 容易与非JVM程序集成。
```suggestion
即使是对于没有严格资源限制的应用程序, 协议仍然有用: 该协议足够简单, 容易与非JVM程序高效集成。
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +即使是对于没有严格资源限制的应用程序, 协议仍然有用: 该协议足够简单, 容易与非JVM程序集成。
原来翻译没有突出efficiently

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +带有该字段的消息, 期望从服务端收到一条返回消息, 返回消息中`address`的值是原始`replyAddress`的值。
原文 _eventually_ 加了斜体表示强调，此处翻译未体现，不过目前还比较通顺，如果没有合适的措辞，则维持现状即可。

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +1. `message`发送或者发布到`address`,
```suggestion
1. `message` 响应 `send` 或者 `publish` 到 `address` 的消息
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +1. `send`发送消息到`address`,
```suggestion
1.  `send` 发送消息到 `address` ，
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +2. `publish`发布消息到`address`,
```suggestion
2.  `publish` 发布消息到 `address` ，
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +3. `register`订阅发送或发布到`address`的消息,
```suggestion
3. `register` 订阅发送或发布到 `address` 的消息，
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +4. `unregister`退订已经发送或发布到`address`的消息,
```suggestion
4. `unregister` 退订已经发送或发布到 `address` 的消息，
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +5. `ping`发送`ping`请求到 bridge 。
```suggestion
5. `ping` 发送 `ping` 请求到 bridge 。
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +请注意, `replyAddress`字段是可选的, 并且只能用于`send`消息。
```suggestion
请注意， `replyAddress` 字段是可选的，并且只能用于`send`消息。
```

2021-01-28 15:58 UTC, fofofofoxier commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +2. `err`报告错误(`body`应该包含详细信息),
```suggestion
2. `err` 报告错误( `body` 应该包含详细信息)，
```

2021-01-29 01:46 UTC, okou19900722 requested changes

2021-01-29 01:46 UTC, okou19900722 commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +TCP 客户端可以发送如下`type`的消息:
```suggestion
TCP 客户端可以发送如下 `type` 的消息:
```

2021-01-29 01:46 UTC, okou19900722 commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +带有该字段的消息, 期望从服务端收到一条返回消息, 返回消息中`address`的值是原始`replyAddress`的值。
```suggestion
带有该字段的消息, 期望从服务端收到一条返回消息, 返回消息中 `address` 的值是原始 `replyAddress` 的值。
```

2021-01-29 01:46 UTC, okou19900722 commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +3. `pong`响应客户端发送的`ping`请求。
```suggestion
3. `pong` 响应客户端发送的 `ping` 请求。
```

2021-01-29 08:13 UTC, chengenzhao approved these changes

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +TCP客户端可以发送如下 `type` 的消息:
```suggestion
TCP客户端可以发送如下 `type` 的消息：
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +服务端返回到客户端的消息可以是如下的 `type` :
```suggestion
服务端返回到客户端的消息可以是如下的 `type` ：
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +关于如何开始使用此birdge的示例如下:
```suggestion
关于如何开始使用此birdge的示例如下：
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +Vert.x-tcp-eventbus-bridge是连接Vert.x EventBus的TCP bridge。要使用此项目，请先加入以下依赖:
```suggestion
Vert.x-tcp-eventbus-bridge是连接Vert.x EventBus的TCP bridge。要使用此项目，请先加入以下依赖：
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
>  Maven (in your `pom.xml`):
```suggestion
Maven（在您的 `pom.xml`）：
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +TCP EventBus bridge建立在TCP之上，任何能够创建TCP套接字的应用程序都可以通过它的EventBus与远端的Vert.x程序进行交互。
```suggestion
TCP EventBus bridge建立在TCP之上，任何能够创建TCP套接字的应用程序都可以通过它的EventBus与远端的Vert.x程序沟通。
```

2021-01-29 08:13 UTC, chengenzhao commented on docs/translation/vertx-tcp-eventbus-bridge/java/index.adoc
> +即使是对于没有严格资源限制的应用程序，协议仍然有用: 该协议足够简单，容易与非JVM程序高效集成。
```suggestion
即使是对于没有严格资源限制的应用程序，协议仍然有用: 该协议足够简单，便于与非JVM程序高效集成。
```

2021-01-29 08:14 UTC, merged